const {chromium}=require(process.env.QA_PLAYWRIGHT||'C:/Users/jplop/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const {locales,base}=require('./qa-gis-ux-2026-10-06.cjs');const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const c=await b.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Mexico_City'});assert.equal((await c.request.post(base+'/api/auth/sesiones',{headers:{Origin:base},form:{username:process.env.QA_USER,password:process.env.QA_PASSWORD}})).status(),200);const who=(await (await c.request.get(base+'/api/auth/sesion')).json()).user;const p=await c.newPage(),errors=[],writes=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>{errors.push('Diálogo nativo');d.dismiss()});await p.route('**/api/**',route=>{if(route.request().method()!=='GET'){writes.push(route.request().url());return route.abort();}return route.continue();});await locales(p);
let geoMode='ok';const imp={id_importacion:990001,id_proyecto:4,tipo_objetivo:'nucleo_agrario_gpkg',nombre_original:'Previsualización QA',formato_detectado:'gpkg',estado:'previsualizado',total_features:1,validos:1,advertencias:0,errores:0,srid_trabajo:4326,crs_original:'EPSG:4326',reporte:{capas:['Núcleos']}};
await p.route('**/api/proyectos/4/mapa',r=>r.fulfill({json:{type:'FeatureCollection',features:[]}}));await p.route('**/api/importaciones/990001',r=>r.fulfill({json:imp}));await p.route('**/features/991001/geometria',r=>geoMode==='403'?r.fulfill({status:403,json:{detail:'Sin permiso'}}):geoMode==='404'?r.fulfill({status:404,json:{detail:'Ausente'}}):geoMode==='red'?r.abort():r.fulfill({json:{type:'Feature',properties:{},geometry:geoMode==='null'?null:{type:'Polygon',coordinates:[[[-110,28],[-109.99,28],[-109.99,28.01],[-110,28]]]}}}));
await p.route('**/js/vendor/leaflet-1.9.4/leaflet.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync('frontend-ssalfer/js/vendor/leaflet-1.9.4/leaflet.js','utf8')+'\n;{const original=L.map;L.map=function(...args){const m=original(...args);window.qaMapa=m;return m;};}'}));
await p.goto(base+'/pages/mapa.html?id_proyecto=4&id_importacion=990001&id_feature=991001');await p.getByText('Mostrando solo la previsualización, aún no confirmada.',{exact:true}).waitFor();await p.waitForLoadState('networkidle');const state=await p.evaluate(()=>({center:qaMapa.getCenter(),zoom:qaMapa.getZoom(),visible:qaMapa.getBounds().contains([28.005,-109.995])}));assert.ok(state.visible&&state.zoom>=12,JSON.stringify(state));await p.screenshot({path:'frontend-ssalfer/deploy/qa-ronda6-previsualizacion.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.reload();await p.waitForLoadState('networkidle');assert.ok(await p.evaluate(()=>qaMapa.getBounds().contains([28.005,-109.995])));await p.screenshot({path:'frontend-ssalfer/deploy/qa-ronda6-previsualizacion-movil.png',fullPage:true});
for(const mode of ['null','403','404','red']){geoMode=mode;await p.reload();await p.waitForLoadState('networkidle');assert.match(await p.locator('main').innerText(),mode==='null'?/no tiene geometría disponible/:mode==='403'?/no tiene permiso/:mode==='404'?/ya no está disponible/:/Comprueba la conexión/);}
await p.goto(base+'/pages/mapa.html');await p.waitForLoadState('networkidle');assert.equal(await p.locator('#selectorProyectoMapa.mapa-elegir-proyecto').count(),1);assert.match(await p.locator('main').innerText(),/Elige un proyecto para ver su mapa/);
// Empty mini map and no-match explanation. All GIS responses are fixtures; no uploads/decisions.
geoMode='null';await p.route('**/api/importaciones/990001/resumen',r=>r.fulfill({json:{registros_administrativos:0,features_archivo:1,features_sin_destino:1,candidatos:0,confirmados:0}}));await p.route('**/api/importaciones/990001/features?*',r=>r.fulfill({json:[{id_importacion_feature:991001,indice_feature:0,atributos_originales:{NombreNucl:'Núcleo sin coincidencia de prueba'},estado_conciliacion:'sin_coincidencia',estado:'valido',advertencias:[],errores:[],transformaciones:[]}]}));for(const tail of ['candidatos','decisiones'])await p.route('**/features/991001/'+tail,r=>r.fulfill({json:[]}));await p.route('**/api/importaciones/990001/conciliaciones?*',r=>r.fulfill({json:[]}));await p.goto(base+'/pages/gestionGeoespacial.html?id_proyecto=4');await p.waitForLoadState('networkidle');await p.evaluate(r=>SSALFER_GIS.mostrar(r),imp);await p.locator('.gis-diagnostico').waitFor();await p.getByRole('button',{name:'Revisar elemento'}).click();await p.getByText('No hay geometría disponible para previsualizar.',{exact:true}).waitFor();assert.match(await p.locator('.gis-diagnostico').innerText(),/Núcleos vinculados al proyecto/);await p.screenshot({path:'frontend-ssalfer/deploy/qa-ronda6-sin-coincidencias.png',fullPage:true});for(const mode of ['403','404','red']){geoMode=mode;await p.getByRole('button',{name:'Revisar elemento'}).click();await p.locator('[data-gis-elemento] [role=alert]').waitFor();assert.ok((await p.locator('[data-gis-elemento] [role=alert]').innerText()).length>10);}geoMode='null';
// Pure-number CSV, full name retained in CSV/modal, real null-date QA response.
await p.setViewportSize({width:1440,height:1000});await p.goto(base+'/pages/derechosColectivos.html?id_proyecto_nucleo=150');await p.locator('[data-exportar]:not([disabled])').waitFor();assert.equal(await p.locator('[name="anio"] option').count(),1);assert.match(await p.locator('[data-sin-fecha]').innerText(),/1 convenio\(s\) sin fecha/);await p.locator('[data-ver-convenio]').first().click();await p.getByRole('dialog').waitFor();assert.match(await p.getByRole('dialog').innerText(),/Consecutivo|Ámbito/);await p.screenshot({path:'frontend-ssalfer/deploy/qa-ronda6-convenio.png'});await p.keyboard.press('Escape');assert.equal(await p.getByRole('dialog').count(),0);
let download=p.waitForEvent('download');await p.locator('[data-exportar]').click();let file=await (await download).path();const csv=fs.readFileSync(file,'utf8');assert.match(csv,/"1000000\.00"/);assert.match(csv,/"1\.2"/);assert.match(csv,/MXN, no aditivo/);assert.doesNotMatch(csv,/"\$1,000,000|"1\.2 ha"/);fs.writeFileSync('frontend-ssalfer/deploy/qa-ronda6-destinos.csv',csv);
download=p.waitForEvent('download');await p.getByRole('button',{name:'Exportar pantalla completa (CSV)'}).click();file=await (await download).path();const completo=fs.readFileSync(file,'utf8');assert.match(completo,/"1000000"/);assert.match(completo,/Superficie \(ha\)/);fs.writeFileSync('frontend-ssalfer/deploy/qa-ronda6-colectivos.csv',completo);
for(const name of ['tipo_convenio','tipo_cop_operativo','destino_superficie'])await p.locator(`[name="${name}"]`).selectOption({index:1});await p.locator('#reporteColectivo button[type="submit"]').click();await p.locator('[data-exportar]:not([disabled])').waitFor();assert.equal(await p.locator('[name="anio"] option').count(),1);assert.match(await p.locator('[data-sin-fecha]').innerText(),/1 convenio/);
// Dated fixture checks month/quarter and CSV protection for text with a formula prefix.
const datos=await(await c.request.get(base+'/api/reportes/convenios/colectivos-destino?id_proyecto=4')).json();await p.route('**/api/reportes/convenios/colectivos-destino?*',r=>r.fulfill({json:datos.map(d=>({...d,fecha_firma:'2026-05-15',anio:2026,mes:5,trimestre:2,destino_superficie:'=SUM(1)'}))}));await p.reload();await p.locator('[data-exportar]:not([disabled])').waitFor();assert.equal(await p.locator('[name="mes"] option[value="5"]').innerText(),'mayo');assert.equal(await p.locator('[name="trimestre"] option[value="2"]').innerText(),'Trimestre 2');download=p.waitForEvent('download');await p.locator('[data-exportar]').click();file=await (await download).path();assert.match(fs.readFileSync(file,'utf8'),/'=SUM\(1\)/i);
// Inactive project record, technical fields and user IDs only inside collapsed detail.
await p.route('**/api/auditoria/cambios?*',r=>r.fulfill({json:{total:1,items:[{id_bitacora:998001,fecha_hora:'2026-10-07T23:01:00Z',usuario:who,id_proyecto:998002,entidad_tipo:'proyecto',entidad_id:998002,accion:'update',accion_descripcion:'Baja',cambios:[{campo:'nombre_proyecto',anterior:'QA Baja de prueba',nuevo:null},{campo:'activo',anterior:true,nuevo:false},{campo:'fecha_baja',anterior:null,nuevo:'2026-10-07T23:01:00Z'},{campo:'id_usuario_baja',anterior:null,nuevo:who.id_usuario},{campo:'motivo_baja',anterior:null,nuevo:'QA baja'}]}]}}));await p.route('**/api/proyectos/998002',r=>r.fulfill({status:404,json:{detail:'No disponible'}}));await p.goto(base+'/pages/auditoria.html');await p.getByRole('button',{name:'Ver detalle'}).first().click();await p.getByText('Campos modificados',{exact:true}).waitFor();const modal=p.locator('#modalAuditoriaDetalle');const visible=await modal.innerText();assert.match(visible,/Jonathan Ponce dio de baja/);assert.match(visible,/Activo: Sí → No/);assert.match(visible,/07-10-2026 17:01/);assert.doesNotMatch(visible,/998001|998002|id_usuario_baja|fecha_baja|\bupdate\b/);assert.match(visible,/QA Baja de prueba/);await p.screenshot({path:'frontend-ssalfer/deploy/qa-ronda6-auditoria.png'});await p.setViewportSize({width:390,height:844});assert.ok(await p.locator('#modalAuditoriaTitulo').evaluate(e=>{const r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.x+10,r.y+10));}));await p.screenshot({path:'frontend-ssalfer/deploy/qa-ronda6-auditoria-movil.png'});await p.keyboard.press('Escape');assert.equal(await modal.isVisible(),false);
// >200 projects: three pages and full-list sorting, date descending with ID tie-break.
const requests=[];const projects=Array.from({length:405},(_,i)=>({id_proyecto:i+1,nombre_proyecto:'Proyecto '+(i+1),creado_en:i<200?'2026-01-01T00:00:00Z':'2026-10-01T00:00:00Z'}));await p.route('**/api/proyectos?*',r=>{const u=new URL(r.request().url());const skip=Number(u.searchParams.get('skip'));requests.push(skip);return r.fulfill({json:projects.slice(skip,skip+Number(u.searchParams.get('limit')))});});const sorted=await p.evaluate(async()=> (await ProyectosAPI.listar()).map(x=>x.id_proyecto));assert.equal(sorted.length,405);assert.deepEqual(requests,[0,200,400]);assert.deepEqual(sorted.slice(0,3),[405,404,403]);assert.equal(sorted.at(-1),1);assert.deepEqual(writes,[]);assert.deepEqual(errors,[]);console.log('RONDA6_OK: mapa centrado escritorio/móvil, vacíos y errores, mini mapa, diagnóstico GIS, CSV real y fechado, modal, auditoría legible y paginación de 405 proyectos; cero escrituras.');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
