/* Catálogo derivado de backend/app/models.py. Los códigos permanecen en el detalle técnico. */
(() => {
 const entidades = {
  "entidad_federativa": "Entidad federativa",
  "municipio": "Municipio",
  "catalogo_operativo": "Catálogo operativo",
  "catalogo_operativo_alias": "Catálogo operativo alias",
  "usuario": "Usuario",
  "estado_autenticacion_usuario": "Estado de acceso del usuario",
  "sesion_usuario": "Sesión de usuario",
  "evento_acceso": "Evento acceso",
  "proyecto": "Proyecto",
  "nucleo_agrario": "Núcleo agrario",
  "proyecto_nucleo": "Núcleo vinculado al proyecto",
  "proyecto_nucleo_responsable": "Responsable del núcleo",
  "proyecto_nucleo_referencia": "Referencia del núcleo",
  "persona": "Persona",
  "orv": "Órgano de representación",
  "orv_integrante": "Integrante del órgano de representación",
  "padron_historial": "Historial de padrones",
  "parcela": "Parcela",
  "parcela_titular": "Parcela titular",
  "actividad_campo": "Actividad de campo",
  "afectacion": "Afectación",
  "unidad_agraria": "Unidad agraria",
  "unidad_agraria_titular": "Unidad agraria titular",
  "afectacion_unidad_agraria": "Unidad agraria afectada",
  "asamblea": "Asamblea",
  "asamblea_convocatoria": "Asamblea convocatoria",
  "convenio": "Convenio",
  "convenio_afectacion": "Afectación vinculada al convenio",
  "convenio_compareciente": "Convenio compareciente",
  "tramite_ran": "Trámite ran",
  "tramite_ran_evento": "Trámite ran evento",
  "tramite_fifonafe": "Trámite fifonafe",
  "tramite_fifonafe_evento": "Trámite fifonafe evento",
  "tramite_fifonafe_interviniente": "Trámite fifonafe interviniente",
  "tramite_fifonafe_afectacion": "Trámite fifonafe afectación",
  "indemnizacion": "Indemnización",
  "pago": "Pago",
  "documento": "Documento",
  "documento_version": "Versión de documento",
  "documento_vinculo": "Vínculo de documento",
  "seguimiento_evento": "Seguimiento evento",
  "trazabilidad_fuente": "Trazabilidad fuente",
  "requisito_documental": "Requisito documental",
  "expediente_requisito": "Expediente requisito",
  "importacion_tabular": "Importación tabular",
  "importacion_tabular_celda": "Importación tabular celda",
  "usuario_proyecto": "Asignación de usuario a proyecto",
  "bitacora": "Registro de auditoría",
  "trazo_proyecto": "Trazo del proyecto",
  "derecho_via_proyecto": "Derecho de vía del proyecto",
  "perfil_mapeo_importacion": "Perfil mapeo importación",
  "catalogo_alias_territorial": "Catálogo alias territorial",
  "importacion_archivo": "Importación archivo",
  "importacion_feature": "Elemento del archivo geográfico",
  "vw_orv_estado": "Vista órgano de representación estado",
  "vw_proyecto_nucleo_resumen": "Vista proyecto núcleo resumen",
  "vw_dashboard_kpi": "Vista dashboard kpi",
  "vw_reporte_avance_periodo": "Vista reporte avance periodo",
  "vw_reporte_snapshot_actual": "Vista reporte snapshot actual",
  "vw_fifonafe_cobertura_008": "Vista fifonafe cobertura 008",
  "vw_fifonafe_indicador_institucional_008": "Vista fifonafe indicador institucional 008",
  "vw_convenio_valor_declarado": "Vista convenio valor declarado",
  "vw_convenio_impacto": "Vista convenio impacto",
  "vw_reporte_convenio_impacto_periodo": "Vista reporte convenio impacto periodo",
  "vw_convenio_cobertura_impacto": "Vista convenio cobertura impacto",
  "vw_convenio_colectivo_destino": "Vista convenio colectivo destino",
  "proyecto_configuracion_gis": "Sistema de coordenadas del proyecto",
  "importacion_feature_candidato": "Destino propuesto del elemento",
  "importacion_feature_decision": "Decisión sobre el elemento",
  "proyecto_nucleo_geometria": "Geometría del núcleo en el proyecto",
  "proyecto_parcela_geometria": "Geometría de parcela en el proyecto",
  "importacion_conciliacion_ciclo": "Ciclo de conciliación",
  "importacion_conciliacion_resultado": "Resultado de conciliación",
  "revision_cambio_gis": "Revisión de cambio geográfico",
  "revision_cambio_gis_decision": "Decisión de revisión geográfica"
};
 const campos = {
  "entidad_federativa": {
    "id_entidad": "Id entidad",
    "clave_inegi": "Clave inegi",
    "nombre": "Nombre",
    "activo": "Activo"
  },
  "municipio": {
    "id_municipio": "Id municipio",
    "id_entidad": "Id entidad",
    "clave_inegi": "Clave inegi",
    "nombre": "Nombre",
    "activo": "Activo"
  },
  "catalogo_operativo": {
    "id_catalogo_opcion": "Id catálogo opcion",
    "tipo_catalogo": "Tipo catálogo",
    "codigo": "Codigo",
    "nombre": "Nombre",
    "descripcion": "Descripcion",
    "orden": "Orden",
    "fuente": "Fuente",
    "vigencia_inicio": "Vigencia inicio",
    "vigencia_fin": "Vigencia fin"
  },
  "catalogo_operativo_alias": {
    "id_catalogo_alias": "Id catálogo alias",
    "id_catalogo_opcion": "Id catálogo opcion",
    "alias": "Alias",
    "alias_normalizado": "Alias normalizado",
    "fuente": "Fuente"
  },
  "usuario": {
    "id_usuario": "Usuario",
    "nombre": "Nombre",
    "apellido_paterno": "Apellido paterno",
    "apellido_materno": "Apellido materno",
    "correo": "Correo",
    "contrasena_hash": "Contrasena hash",
    "rol": "Rol",
    "activo": "Activo",
    "fecha_alta": "Fecha alta",
    "fecha_baja": "Fecha de baja",
    "id_usuario_baja": "Usuario que dio de baja",
    "motivo_baja": "Motivo de la baja",
    "fecha_reactivacion": "Fecha reactivacion",
    "id_usuario_reactivacion": "Id usuario reactivacion",
    "motivo_reactivacion": "Motivo reactivacion",
    "observaciones": "Observaciones"
  },
  "estado_autenticacion_usuario": {
    "id_usuario": "Usuario",
    "intentos_fallidos": "Intentos fallidos",
    "bloqueado_hasta": "Bloqueado hasta",
    "ultimo_acceso_en": "Ultimo acceso en",
    "actualizado_en": "Última modificación"
  },
  "sesion_usuario": {
    "id_sesion": "Id sesión",
    "id_usuario": "Usuario",
    "token_hash": "Token hash",
    "csrf_hash": "Csrf hash",
    "fecha_creacion": "Fecha creacion",
    "ultima_actividad": "Ultima actividad",
    "expira_en": "Expira en",
    "revocada_en": "Revocada en",
    "id_usuario_revoca": "Id usuario revoca",
    "motivo_revocacion": "Motivo revocacion",
    "ip_creacion": "Ip creacion",
    "user_agent_creacion": "User agent creacion"
  },
  "evento_acceso": {
    "id_evento": "Id evento",
    "id_usuario": "Usuario",
    "id_usuario_actor": "Usuario que realizó la acción",
    "id_sesion": "Id sesión",
    "tipo_evento": "Tipo evento",
    "motivo_codigo": "Motivo codigo",
    "detalle": "Detalle",
    "fecha_hora": "Fecha hora",
    "ip_origen": "Ip origen",
    "user_agent": "User agent",
    "txid_registro": "Txid registro"
  },
  "proyecto": {
    "id_proyecto": "Proyecto",
    "clave_proyecto": "Clave proyecto",
    "nombre_proyecto": "Nombre del proyecto",
    "descripcion": "Descripcion",
    "fecha_inicio": "Fecha inicio",
    "fecha_fin": "Fecha fin"
  },
  "nucleo_agrario": {
    "id_nucleo": "Núcleo",
    "id_municipio": "Id municipio",
    "nombre_nucleo": "Nombre núcleo",
    "id_tipo_tenencia": "Id tipo tenencia",
    "comunidad_indigena": "Comunidad indigena",
    "geometria_poligono": "Geometría poligono",
    "fuente_geometria": "Fuente geometría",
    "fecha_fuente_geometria": "Fecha fuente geometría",
    "fuente_datos": "Fuente datos",
    "id_entidad_fuente": "Id entidad fuente",
    "id_municipio_fuente": "Id municipio fuente",
    "id_nucleo_fuente": "Id núcleo fuente",
    "alcance_identidad_fuente": "Alcance identidad fuente"
  },
  "proyecto_nucleo": {
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_proyecto": "Proyecto",
    "id_nucleo": "Núcleo",
    "id_residencia": "Id residencia",
    "total_cops_planeados": "Total cops planeados",
    "afecta_tuc": "Afecta tuc",
    "id_motivo_no_afecta_tuc": "Id motivo no afecta tuc",
    "motivo_no_afecta_tuc_detalle": "Motivo no afecta tuc detalle",
    "tuc_revision_pendiente": "Tuc revisión pendiente",
    "tuc_revision_detalle": "Tuc revisión detalle"
  },
  "proyecto_nucleo_responsable": {
    "id_responsable": "Id responsable",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "nombre": "Nombre",
    "cargo": "Cargo",
    "contacto": "Contacto",
    "vigencia_inicio": "Vigencia inicio",
    "vigencia_fin": "Vigencia fin",
    "es_principal": "Es principal"
  },
  "proyecto_nucleo_referencia": {
    "id_referencia": "Id referencia",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "tipo_referencia": "Tipo referencia",
    "valor": "Valor",
    "es_principal": "Es principal"
  },
  "persona": {
    "id_persona": "Id persona",
    "curp": "Curp",
    "rfc": "Rfc",
    "nombre": "Nombre",
    "apellido_paterno": "Apellido paterno",
    "apellido_materno": "Apellido materno",
    "telefono": "Telefono",
    "correo_electronico": "Correo electronico",
    "datos_identidad_incompletos": "Datos identidad incompletos",
    "origen_registro": "Origen registro"
  },
  "orv": {
    "id_orv": "Id órgano de representación",
    "id_nucleo": "Núcleo",
    "numero_orv": "Numero órgano de representación",
    "inicio_vigencia": "Inicio vigencia",
    "fin_vigencia": "Fin vigencia",
    "estatus_fuente": "Estatus fuente",
    "id_estado_registral": "Id estado registral"
  },
  "orv_integrante": {
    "id_orv_integrante": "Id órgano de representación integrante",
    "id_orv": "Id órgano de representación",
    "id_persona": "Id persona",
    "id_organo": "Id organo",
    "id_cargo": "Id cargo",
    "id_calidad": "Id calidad",
    "fecha_inicio": "Fecha inicio",
    "fecha_fin": "Fecha fin",
    "id_tipo_fin": "Id tipo fin",
    "detalle_fin": "Detalle fin"
  },
  "padron_historial": {
    "id_padron": "Id padrón",
    "id_nucleo": "Núcleo",
    "fecha_padron": "Fecha padrón",
    "numero_ejidatarios_comuneros": "Numero ejidatarios comuneros",
    "fuente": "Fuente",
    "id_documento": "Id documento"
  },
  "parcela": {
    "id_parcela": "Id parcela",
    "id_nucleo": "Núcleo",
    "tipo_parcela": "Tipo parcela",
    "no_parcela": "Número de parcela",
    "certificado_parcelario": "Certificado parcelario",
    "folio_derechos": "Folio derechos",
    "constancia_vigencia_fecha": "Constancia vigencia fecha",
    "geometria_poligono": "Geometría poligono",
    "fuente_geometria": "Fuente geometría",
    "fecha_fuente_geometria": "Fecha fuente geometría"
  },
  "parcela_titular": {
    "id_parcela_titular": "Id parcela titular",
    "id_parcela": "Id parcela",
    "id_persona": "Id persona",
    "tipo_derecho": "Tipo derecho",
    "porcentaje_participacion": "Porcentaje participacion",
    "fecha_inicio": "Fecha inicio",
    "fecha_fin": "Fecha fin"
  },
  "actividad_campo": {
    "id_actividad": "Id actividad",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_afectacion": "Id afectación",
    "tipo_actividad": "Tipo actividad",
    "contexto_actividad": "Contexto actividad",
    "id_tipo_cop_operativo": "Id tipo cop operativo",
    "fecha_programada": "Fecha programada",
    "fecha_realizada": "Fecha realizada",
    "responsable": "Responsable",
    "resultado": "Resultado"
  },
  "afectacion": {
    "id_afectacion": "Id afectación",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "tipo_afectacion": "Tipo afectación",
    "superficie_preliminar_ha": "Superficie preliminar ha",
    "superficie_afectada_ha": "Superficie afectada ha",
    "situacion": "Situacion",
    "condicion_especial": "Condicion especial",
    "descripcion_condicion": "Descripcion condicion",
    "avaluo_monto": "Avaluo monto",
    "avaluo_fecha": "Avaluo fecha",
    "avaluo_referencia": "Avaluo referencia",
    "avaluo_institucion": "Avaluo institucion",
    "id_tipo_cop_operativo": "Id tipo cop operativo",
    "tipo_cop_revision_pendiente": "Tipo cop revisión pendiente",
    "tipo_cop_revision_detalle": "Tipo cop revisión detalle"
  },
  "unidad_agraria": {
    "id_unidad_agraria": "Id unidad agraria",
    "id_nucleo": "Núcleo",
    "id_tipo_tierra": "Id tipo tierra",
    "id_tipo_gestion": "Id tipo gestion",
    "id_destino_superficie": "Id destino superficie",
    "id_tipo_titularidad": "Id tipo titularidad",
    "id_parcela": "Id parcela",
    "referencia_alfanumerica": "Referencia alfanumerica",
    "referencia_normalizada": "Referencia normalizada",
    "detalle": "Detalle",
    "fuente": "Fuente",
    "requiere_revision": "Requiere revisión",
    "motivo_revision": "Motivo revisión"
  },
  "unidad_agraria_titular": {
    "id_unidad_titular": "Id unidad titular",
    "id_unidad_agraria": "Id unidad agraria",
    "id_persona": "Id persona",
    "id_parcela_titular": "Id parcela titular",
    "porcentaje_participacion": "Porcentaje participacion",
    "es_principal": "Es principal"
  },
  "afectacion_unidad_agraria": {
    "id_afectacion_unidad": "Id afectación unidad",
    "id_afectacion": "Id afectación",
    "id_unidad_agraria": "Id unidad agraria",
    "superficie_preliminar_ha": "Superficie preliminar ha",
    "superficie_afectada_ha": "Superficie afectada ha",
    "superficie_valor_original": "Superficie valor original",
    "superficie_formato_origen": "Superficie formato origen",
    "fuente": "Fuente"
  },
  "asamblea": {
    "id_asamblea": "Id asamblea",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_padron": "Id padrón",
    "id_tipo_asamblea": "Id tipo asamblea",
    "id_contexto_asamblea": "Id contexto asamblea",
    "id_tipo_cop_operativo": "Id tipo cop operativo",
    "proposito": "Proposito",
    "resultado": "Resultado"
  },
  "asamblea_convocatoria": {
    "id_convocatoria": "Id convocatoria",
    "id_asamblea": "Id asamblea",
    "ordinal": "Ordinal",
    "fecha_expedicion": "Fecha expedicion",
    "fecha_programada": "Fecha programada",
    "fecha_realizacion": "Fecha realizacion",
    "id_resultado": "Id resultado",
    "observaciones_resultado": "Observaciones resultado",
    "id_documento": "Id documento"
  },
  "convenio": {
    "id_convenio": "Id convenio",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "ambito": "Ambito",
    "tipo_instrumento": "Tipo instrumento",
    "tipo_convenio": "Tipo convenio",
    "modalidad_especial": "Modalidad especial",
    "descripcion_modalidad": "Descripcion modalidad",
    "descripcion_instrumento": "Descripcion instrumento",
    "consecutivo": "Consecutivo",
    "id_convenio_padre": "Id convenio padre",
    "id_asamblea_autorizacion": "Id asamblea autorizacion",
    "fecha_programada_firma": "Fecha programada firma",
    "fecha_firma": "Fecha de firma",
    "monto_90": "Monto 90",
    "monto_100": "Monto 100",
    "monto_bdt": "Monto bdt",
    "superficie_ha": "Superficie ha",
    "efecto_monto": "Efecto monto",
    "monto_90_impacto": "Monto 90 impacto",
    "monto_100_impacto": "Monto 100 impacto",
    "monto_bdt_impacto": "Monto bdt impacto",
    "estado_antecedente": "Estado antecedente"
  },
  "convenio_afectacion": {
    "id_convenio_afectacion": "Id convenio afectación",
    "id_convenio": "Id convenio",
    "id_afectacion": "Id afectación",
    "rol": "Rol",
    "efecto_superficie": "Efecto superficie",
    "superficie_impacto_ha": "Superficie impacto ha"
  },
  "convenio_compareciente": {
    "id_compareciente": "Id compareciente",
    "id_convenio": "Id convenio",
    "id_persona": "Id persona",
    "id_parcela_titular": "Id parcela titular",
    "id_tipo_calidad": "Id tipo calidad",
    "id_tipo_acreditacion": "Id tipo acreditacion",
    "referencia_acreditacion": "Referencia acreditacion",
    "fecha_acreditacion": "Fecha acreditacion",
    "nombre_en_instrumento": "Nombre en instrumento",
    "es_firmante": "Es firmante",
    "es_beneficiario_pago": "Es beneficiario pago",
    "requiere_revision": "Requiere revisión",
    "motivo_revision": "Motivo revisión"
  },
  "tramite_ran": {
    "id_tramite_ran": "Id trámite ran",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_nucleo": "Núcleo",
    "id_asamblea": "Id asamblea",
    "id_convenio": "Id convenio",
    "id_orv": "Id órgano de representación",
    "fecha_programada_ingreso": "Fecha programada ingreso",
    "referencia_expediente": "Referencia expediente"
  },
  "tramite_ran_evento": {
    "id_evento_ran": "Id evento ran",
    "id_tramite_ran": "Id trámite ran",
    "ordinal": "Ordinal",
    "id_tipo_evento": "Id tipo evento",
    "fecha_evento": "Fecha evento",
    "numero_solicitud": "Numero solicitud",
    "resultado": "Resultado",
    "calificacion": "Calificacion",
    "folio_referencia": "Folio referencia",
    "id_documento": "Id documento"
  },
  "tramite_fifonafe": {
    "id_tramite_fifonafe": "Id trámite fifonafe",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "ambito": "Ambito",
    "estatus": "Estatus",
    "acuse_fifonafe_fecha": "Acuse fifonafe fecha",
    "hay_conflictos": "Hay conflictos",
    "resultado_no_conflictos": "Resultado no conflictos",
    "referencia_expediente": "Referencia expediente",
    "version_flujo": "Versión flujo",
    "id_asamblea_retiro": "Id asamblea retiro"
  },
  "tramite_fifonafe_evento": {
    "id_evento_fifonafe": "Id evento fifonafe",
    "id_tramite_fifonafe": "Id trámite fifonafe",
    "ordinal": "Ordinal",
    "id_tipo_evento": "Id tipo evento",
    "origen": "Origen",
    "destino": "Destino",
    "numero_oficio": "Numero oficio",
    "fecha_oficio": "Fecha oficio",
    "id_documento": "Id documento",
    "ciclo_consulta": "Ciclo consulta",
    "fecha_evento": "Fecha evento",
    "conflicto_impide_retiro": "Conflicto impide retiro"
  },
  "tramite_fifonafe_interviniente": {
    "id_interviniente_fifonafe": "Id interviniente fifonafe",
    "id_tramite_fifonafe": "Id trámite fifonafe",
    "id_persona": "Id persona",
    "rol": "Rol",
    "id_evento_fifonafe": "Id evento fifonafe",
    "id_orv_integrante": "Id órgano de representación integrante"
  },
  "tramite_fifonafe_afectacion": {
    "id_tramite_fifonafe_afectacion": "Id trámite fifonafe afectación",
    "id_tramite_fifonafe": "Id trámite fifonafe",
    "id_afectacion": "Id afectación"
  },
  "indemnizacion": {
    "id_indemnizacion": "Id indemnización",
    "id_afectacion": "Id afectación",
    "estatus": "Estatus",
    "descripcion_estatus": "Descripcion estatus",
    "fecha_programada": "Fecha programada",
    "fecha_resolucion": "Fecha resolucion",
    "fecha_entrega_expediente_pa": "Fecha entrega expediente pa"
  },
  "pago": {
    "id_pago": "Id pago",
    "id_indemnizacion": "Id indemnización",
    "fecha_pago": "Fecha pago",
    "monto": "Monto",
    "id_persona_beneficiaria": "Id persona beneficiaria",
    "beneficiario_nombre": "Beneficiario nombre",
    "referencia": "Referencia",
    "medio_pago": "Medio pago"
  },
  "documento": {
    "id_tipo_documento": "Tipo documental",
    "id_documento": "Id documento",
    "tipo_documento": "Tipo documento",
    "estado": "Estado",
    "titulo": "Titulo",
    "fecha_documento": "Fecha documento",
    "numero_folio": "Numero folio",
    "descripcion": "Descripcion"
  },
  "documento_version": {
    "id_documento_version": "Id documento versión",
    "id_documento": "Id documento",
    "numero_version": "Numero versión",
    "hash_sha256": "Hash sha256",
    "tamano_bytes": "Tamano bytes",
    "nombre_original": "Nombre original",
    "ruta_almacenamiento": "Ruta almacenamiento",
    "tipo_mime": "Tipo mime",
    "fecha_carga": "Fecha carga",
    "id_usuario_carga": "Id usuario carga"
  },
  "documento_vinculo": {
    "id_documento_vinculo": "Id documento vínculo",
    "id_documento": "Id documento",
    "entidad_tipo": "Entidad tipo",
    "entidad_id": "Entidad id"
  },
  "seguimiento_evento": {
    "id_seguimiento_evento": "Id seguimiento evento",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "entidad_tipo": "Entidad tipo",
    "entidad_id": "Entidad id",
    "ambito": "Ambito",
    "id_tipo_evento": "Id tipo evento",
    "id_motivo": "Id motivo",
    "fecha_evento": "Fecha evento",
    "detalle": "Detalle",
    "id_documento": "Id documento",
    "fuente": "Fuente"
  },
  "trazabilidad_fuente": {
    "id_trazabilidad": "Id trazabilidad",
    "entidad_tipo": "Entidad tipo",
    "entidad_id": "Entidad id",
    "archivo": "Archivo",
    "hoja": "Hoja",
    "fila": "Fila",
    "columna": "Columna",
    "valor_original": "Valor original",
    "valor_normalizado": "Valor normalizado",
    "tratamiento": "Tratamiento",
    "mensajes": "Mensajes",
    "id_importacion_tabular": "Id importación tabular",
    "registrado_en": "Registrado en",
    "id_usuario_registro": "Id usuario registro"
  },
  "requisito_documental": {
    "id_requisito": "Id requisito",
    "codigo": "Codigo",
    "nombre": "Nombre",
    "descripcion": "Descripcion",
    "contexto": "Contexto",
    "obligatorio": "Obligatorio",
    "orden": "Orden",
    "fuente": "Fuente",
    "vigencia_inicio": "Vigencia inicio",
    "vigencia_fin": "Vigencia fin"
  },
  "expediente_requisito": {
    "id_expediente_requisito": "Id expediente requisito",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "entidad_tipo": "Entidad tipo",
    "entidad_id": "Entidad id",
    "id_requisito": "Id requisito",
    "id_estado": "Id estado",
    "id_documento": "Id documento",
    "detalle": "Detalle"
  },
  "importacion_tabular": {
    "id_importacion_tabular": "Id importación tabular",
    "id_proyecto": "Proyecto",
    "archivo": "Archivo",
    "sha256": "Sha256",
    "hoja": "Hoja",
    "filas_detectadas": "Filas detectadas",
    "filas_procesadas": "Filas procesadas",
    "advertencias": "Advertencias",
    "errores": "Errores",
    "estado": "Estado"
  },
  "importacion_tabular_celda": {
    "id_importacion_celda": "Id importación celda",
    "id_importacion_tabular": "Id importación tabular",
    "fila": "Fila",
    "columna": "Columna",
    "encabezado": "Encabezado",
    "valor_original": "Valor original",
    "valor_normalizado": "Valor normalizado",
    "tratamiento": "Tratamiento",
    "mensajes": "Mensajes",
    "entidad_tipo": "Entidad tipo",
    "entidad_id": "Entidad id",
    "registrado_en": "Registrado en",
    "id_usuario_registro": "Id usuario registro"
  },
  "usuario_proyecto": {
    "id_usuario_proyecto": "Id usuario proyecto",
    "id_usuario": "Usuario",
    "id_proyecto": "Proyecto",
    "asignado_por": "Asignado por",
    "fecha_asignacion": "Fecha asignacion"
  },
  "bitacora": {
    "id_bitacora": "Id bitácora",
    "id_usuario": "Usuario",
    "id_proyecto": "Proyecto",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_nucleo": "Núcleo",
    "entidad_tipo": "Entidad tipo",
    "entidad_id": "Entidad id",
    "accion": "Accion",
    "valor_anterior": "Valor anterior",
    "valor_nuevo": "Valor nuevo",
    "fecha_hora": "Fecha hora",
    "ip_origen": "Ip origen",
    "user_agent": "User agent"
  },
  "trazo_proyecto": {
    "id_trazo": "Id trazo",
    "id_proyecto": "Proyecto",
    "version": "Versión",
    "geometria_linea": "Geometría linea",
    "fuente": "Fuente",
    "fecha_fuente": "Fecha fuente",
    "fecha_vigencia_inicio": "Fecha vigencia inicio",
    "fecha_vigencia_fin": "Fecha vigencia fin"
  },
  "derecho_via_proyecto": {
    "id_derecho_via": "Id derecho via",
    "id_proyecto": "Proyecto",
    "version": "Versión",
    "es_vigente": "Es vigente",
    "geometria_poligono": "Geometría poligono",
    "fuente": "Fuente",
    "fecha_fuente": "Fecha fuente",
    "id_importacion": "Id importación",
    "sha256": "Sha256",
    "srid_trabajo": "Sistema de coordenadas",
    "geometria_trabajo": "Geometría trabajo"
  },
  "perfil_mapeo_importacion": {
    "id_perfil": "Id perfil",
    "id_proyecto": "Proyecto",
    "nombre": "Nombre",
    "fuente": "Fuente",
    "tipo_objetivo": "Tipo objetivo",
    "mapeo": "Mapeo",
    "opciones": "Opciones",
    "id_usuario_creacion": "Id usuario creacion"
  },
  "catalogo_alias_territorial": {
    "id_alias": "Id alias",
    "id_entidad": "Id entidad",
    "alias_nombre": "Alias nombre",
    "alias_normalizado": "Alias normalizado",
    "alias_clave": "Alias clave",
    "id_municipio_destino": "Id municipio destino",
    "fuente": "Fuente",
    "fecha_vigencia_inicio": "Fecha vigencia inicio",
    "fecha_vigencia_fin": "Fecha vigencia fin",
    "id_usuario_aprobador": "Id usuario aprobador"
  },
  "importacion_archivo": {
    "id_importacion": "Id importación",
    "id_proyecto": "Proyecto",
    "tipo_objetivo": "Tipo objetivo",
    "nombre_original": "Nombre original",
    "nombre_almacenado": "Nombre almacenado",
    "formato_detectado": "Formato detectado",
    "tamano_bytes": "Tamano bytes",
    "sha256": "Sha256",
    "fuente": "Fuente",
    "fecha_fuente": "Fecha fuente",
    "version_pipeline": "Versión pipeline",
    "srid_trabajo": "Sistema de coordenadas",
    "crs_fuente_wkt": "Crs fuente wkt",
    "alcance_entrega": "Alcance entrega",
    "id_importacion_anterior": "Id importación anterior",
    "crs_original": "Crs original",
    "crs_destino": "Crs destino",
    "columnas_detectadas": "Columnas detectadas",
    "mapeo": "Mapeo",
    "opciones_mapeo": "Opciones mapeo",
    "id_perfil": "Id perfil",
    "estado": "Estado",
    "total_features": "Total features",
    "features_procesados": "Features procesados",
    "validos": "Validos",
    "advertencias": "Advertencias",
    "errores": "Errores",
    "importados": "Importados",
    "descartados": "Descartados",
    "id_usuario_carga": "Id usuario carga",
    "fecha_carga": "Fecha carga",
    "fecha_procesamiento_inicio": "Fecha procesamiento inicio",
    "fecha_procesamiento_fin": "Fecha procesamiento fin",
    "confirmacion_explicita": "Confirmacion explicita",
    "fecha_confirmacion": "Fecha confirmacion",
    "id_usuario_confirmacion": "Id usuario confirmacion",
    "error_codigo": "Error codigo",
    "error_detalle": "Error detalle",
    "reporte": "Reporte",
    "version_control": "Versión control"
  },
  "importacion_feature": {
    "id_importacion_feature": "Id importación feature",
    "id_importacion": "Id importación",
    "indice_feature": "Indice feature",
    "capa_origen": "Capa origen",
    "id_externo": "Id externo",
    "tipo_geometria": "Tipo geometría",
    "atributos_originales": "Atributos originales",
    "atributos_normalizados": "Atributos normalizados",
    "geometria_normalizada": "Geometría normalizada",
    "geometria_original": "Geometría original",
    "geometria_trabajo": "Geometría trabajo",
    "crs_fuente": "Crs fuente",
    "dimension_fuente": "Dimension fuente",
    "estado_conciliacion": "Estado conciliación",
    "estado": "Estado",
    "errores": "Errores",
    "advertencias": "Advertencias",
    "transformaciones": "Transformaciones",
    "advertencias_aceptadas": "Advertencias aceptadas",
    "id_usuario_revision": "Id usuario revisión",
    "fecha_revision": "Fecha revisión",
    "registro_destino_id": "Registro destino id",
    "fecha_procesamiento": "Fecha procesamiento",
    "fecha_importacion": "Fecha importación"
  },
  "vw_orv_estado": {
    "id_orv": "Id órgano de representación",
    "id_nucleo": "Núcleo",
    "numero_orv": "Numero órgano de representación",
    "inicio_vigencia": "Inicio vigencia",
    "fin_vigencia": "Fin vigencia",
    "id_estado_registral": "Id estado registral",
    "estado_registral_codigo": "Estado registral codigo",
    "estado_registral_nombre": "Estado registral nombre",
    "fecha_inscripcion_ran": "Fecha inscripcion ran",
    "estado_vigencia": "Estado vigencia",
    "activo": "Activo"
  },
  "vw_proyecto_nucleo_resumen": {
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_proyecto": "Proyecto",
    "nombre_proyecto": "Nombre del proyecto",
    "id_nucleo": "Núcleo",
    "nombre_nucleo": "Nombre núcleo",
    "id_tipo_tenencia": "Id tipo tenencia",
    "tipo_tenencia_codigo": "Tipo tenencia codigo",
    "tipo_tenencia_nombre": "Tipo tenencia nombre",
    "id_residencia": "Id residencia",
    "residencia_codigo": "Residencia codigo",
    "residencia_nombre": "Residencia nombre",
    "id_municipio": "Id municipio",
    "municipio": "Municipio",
    "id_entidad": "Id entidad",
    "entidad": "Entidad",
    "responsable_nombre": "Responsable nombre",
    "responsable_cargo": "Responsable cargo",
    "responsable_contacto": "Responsable contacto",
    "tipo_referencia": "Tipo referencia",
    "referencia_principal": "Referencia principal",
    "total_parcelas": "Total parcelas",
    "total_afectaciones": "Total afectaciones",
    "afectaciones_colectivas": "Afectaciones colectivas",
    "afectaciones_individuales": "Afectaciones individuales",
    "superficie_preliminar_ha": "Superficie preliminar ha",
    "superficie_afectada_ha": "Superficie afectada ha",
    "total_asambleas": "Total asambleas",
    "total_convenios": "Total convenios",
    "total_unidades_afectadas": "Total unidades afectadas",
    "total_cops_planeados": "Total cops planeados",
    "afecta_tuc": "Afecta tuc",
    "id_motivo_no_afecta_tuc": "Id motivo no afecta tuc",
    "motivo_no_afecta_tuc_detalle": "Motivo no afecta tuc detalle",
    "tuc_revision_pendiente": "Tuc revisión pendiente",
    "tuc_revision_detalle": "Tuc revisión detalle",
    "activo": "Activo",
    "creado_en": "Fecha de registro",
    "creado_por": "Usuario que registró",
    "actualizado_en": "Última modificación",
    "actualizado_por": "Usuario que modificó",
    "fecha_baja": "Fecha de baja",
    "id_usuario_baja": "Usuario que dio de baja",
    "motivo_baja": "Motivo de la baja",
    "observaciones": "Observaciones"
  },
  "vw_dashboard_kpi": {
    "id_proyecto": "Proyecto",
    "anio": "Anio",
    "indicador": "Indicador",
    "programado": "Programado",
    "realizado": "Realizado",
    "cantidad": "Cantidad",
    "superficie_ha": "Superficie ha",
    "monto": "Monto"
  },
  "vw_reporte_avance_periodo": {
    "id_proyecto": "Proyecto",
    "id_entidad": "Id entidad",
    "ambito": "Ambito",
    "tipo_cop_operativo": "Tipo cop operativo",
    "tipo_convenio": "Tipo convenio",
    "destino_superficie": "Destino superficie",
    "anio": "Anio",
    "mes": "Mes",
    "trimestre": "Trimestre",
    "indicador": "Indicador",
    "programado": "Programado",
    "realizado": "Realizado",
    "cantidad": "Cantidad",
    "superficie_ha": "Superficie ha",
    "monto": "Monto"
  },
  "vw_reporte_snapshot_actual": {
    "id_proyecto": "Proyecto",
    "id_entidad": "Id entidad",
    "ambito": "Ambito",
    "indicador": "Indicador",
    "tipo_cop_operativo": "Tipo cop operativo",
    "destino_superficie": "Destino superficie",
    "cantidad": "Cantidad",
    "superficie_ha": "Superficie ha",
    "monto": "Monto"
  },
  "vw_fifonafe_cobertura_008": {
    "id_proyecto": "Proyecto",
    "ambito": "Ambito",
    "universo_solicitudes": "Universo solicitudes",
    "solicitudes_recibidas_acreditadas": "Solicitudes recibidas acreditadas",
    "eventos_consulta_sin_ciclo": "Eventos consulta sin ciclo",
    "respuestas_sin_soporte": "Respuestas sin soporte",
    "actuaciones_sin_soporte": "Actuaciones sin soporte",
    "completos_integrales": "Completos integrales",
    "pendientes_integrales": "Pendientes integrales"
  },
  "vw_fifonafe_indicador_institucional_008": {
    "id_proyecto": "Proyecto",
    "anio": "Anio",
    "solicitudes_recibidas": "Solicitudes recibidas",
    "solicitudes_resueltas_positivas": "Solicitudes resueltas positivas",
    "porcentaje": "Porcentaje"
  },
  "vw_convenio_valor_declarado": {
    "id_convenio": "Id convenio",
    "concepto": "Concepto",
    "id_proyecto": "Proyecto",
    "id_entidad": "Id entidad",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "ambito": "Ambito",
    "tipo_cop_operativo": "Tipo cop operativo",
    "tipo_convenio": "Tipo convenio",
    "unidad": "Unidad",
    "valor_declarado": "Valor declarado",
    "fecha_instrumento_reportada": "Fecha instrumento reportada",
    "firma_acreditada": "Firma acreditada"
  },
  "vw_convenio_impacto": {
    "clave_impacto": "Clave impacto",
    "id_proyecto": "Proyecto",
    "id_entidad": "Id entidad",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_convenio": "Id convenio",
    "id_convenio_afectacion": "Id convenio afectación",
    "id_afectacion": "Id afectación",
    "ambito": "Ambito",
    "tipo_cop_operativo": "Tipo cop operativo",
    "tipo_convenio": "Tipo convenio",
    "concepto": "Concepto",
    "unidad": "Unidad",
    "efecto": "Efecto",
    "fecha_efecto": "Fecha efecto",
    "valor_impacto": "Valor impacto",
    "pendiente": "Pendiente",
    "firma_acreditada": "Firma acreditada"
  },
  "vw_reporte_convenio_impacto_periodo": {
    "id_proyecto": "Proyecto",
    "id_entidad": "Id entidad",
    "ambito": "Ambito",
    "tipo_cop_operativo": "Tipo cop operativo",
    "tipo_convenio": "Tipo convenio",
    "concepto": "Concepto",
    "unidad": "Unidad",
    "efecto": "Efecto",
    "anio": "Anio",
    "mes": "Mes",
    "trimestre": "Trimestre",
    "cantidad": "Cantidad",
    "valor_impacto": "Valor impacto"
  },
  "vw_convenio_cobertura_impacto": {
    "id_proyecto": "Proyecto",
    "id_entidad": "Id entidad",
    "ambito": "Ambito",
    "concepto": "Concepto",
    "unidad": "Unidad",
    "universo": "Universo",
    "clasificados": "Clasificados",
    "pendientes": "Pendientes",
    "sin_firma_acreditada": "Sin firma acreditada"
  },
  "vw_convenio_colectivo_destino": {
    "id_convenio": "Id convenio",
    "destino_superficie": "Destino superficie",
    "id_proyecto": "Proyecto",
    "id_entidad": "Id entidad",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_asamblea": "Id asamblea",
    "ambito": "Ambito",
    "tipo_convenio": "Tipo convenio",
    "tipo_cop_operativo": "Tipo cop operativo",
    "superficie_ha": "Superficie ha",
    "superficie_declarada_ha": "Superficie declarada ha",
    "monto_declarado": "Monto declarado",
    "fecha_firma": "Fecha de firma",
    "anio": "Anio",
    "mes": "Mes",
    "trimestre": "Trimestre"
  },
  "proyecto_configuracion_gis": {
    "id_proyecto": "Proyecto",
    "srid_trabajo": "Sistema de coordenadas"
  },
  "importacion_feature_candidato": {
    "id_candidato": "Id candidato",
    "id_ciclo": "Id ciclo",
    "id_importacion": "Id importación",
    "id_importacion_feature": "Id importación feature",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_parcela": "Id parcela",
    "criterio": "Criterio",
    "clasificacion": "Clasificacion",
    "coincidencias": "Coincidencias",
    "estado": "Estado",
    "id_usuario_revision": "Id usuario revisión",
    "fecha_revision": "Fecha revisión",
    "geometria_previa_hash": "Geometría previa hash"
  },
  "importacion_feature_decision": {
    "id_decision": "Id decision",
    "id_ciclo": "Id ciclo",
    "id_importacion_feature": "Id importación feature",
    "id_candidato": "Id candidato",
    "accion": "Accion",
    "motivo": "Motivo",
    "creado_por": "Usuario que registró",
    "creado_en": "Fecha de registro"
  },
  "proyecto_nucleo_geometria": {},
  "proyecto_parcela_geometria": {
    "id_parcela": "Id parcela"
  },
  "importacion_conciliacion_ciclo": {
    "id_ciclo": "Id ciclo",
    "id_importacion": "Id importación",
    "numero_ciclo": "Numero ciclo",
    "tipo_ciclo": "Tipo ciclo",
    "motivo": "Motivo",
    "estado": "Estado",
    "fecha_inicio": "Fecha inicio",
    "fecha_fin": "Fecha fin",
    "id_usuario": "Usuario",
    "version_algoritmo": "Versión algoritmo",
    "universo_destinos": "Universo destinos",
    "resumen": "Resumen",
    "clave_solicitud": "Clave solicitud",
    "creado_en": "Fecha de registro"
  },
  "importacion_conciliacion_resultado": {
    "id_ciclo": "Id ciclo",
    "id_importacion_feature": "Id importación feature",
    "estado_matching": "Estado matching",
    "creado_en": "Fecha de registro"
  },
  "revision_cambio_gis": {
    "id_revision": "Id revisión",
    "clave_comparacion": "Clave comparacion",
    "id_proyecto": "Proyecto",
    "objetivo": "Objetivo",
    "id_proyecto_nucleo": "Núcleo del proyecto",
    "id_parcela": "Id parcela",
    "id_feature_nueva": "Id feature nueva",
    "id_importacion_anterior": "Id importación anterior",
    "id_importacion_nueva": "Id importación nueva",
    "id_nucleo_geometria_anterior": "Id núcleo geometría anterior",
    "id_nucleo_geometria_nueva": "Id núcleo geometría nueva",
    "id_parcela_geometria_anterior": "Id parcela geometría anterior",
    "id_parcela_geometria_nueva": "Id parcela geometría nueva",
    "id_ddv_anterior": "Id ddv anterior",
    "id_ddv_nueva": "Id ddv nueva",
    "tipo_cambio": "Tipo cambio",
    "subtipo_cambio": "Subtipo cambio",
    "srid_medicion": "Srid medicion",
    "area_anterior_m2": "Area anterior m2",
    "area_nueva_m2": "Area nueva m2",
    "area_diferencia_m2": "Area diferencia m2",
    "porcentaje_diferencia": "Porcentaje diferencia",
    "metricas": "Metricas",
    "creado_en": "Fecha de registro",
    "creado_por": "Usuario que registró"
  },
  "revision_cambio_gis_decision": {
    "id_decision": "Id decision",
    "id_revision": "Id revisión",
    "accion": "Accion",
    "motivo": "Motivo",
    "clave_solicitud": "Clave solicitud",
    "id_seguimiento_evento": "Id seguimiento evento",
    "creado_por": "Usuario que registró",
    "creado_en": "Fecha de registro"
  }
};
 const comunes = {"activo": "Activo", "fecha_baja": "Fecha de baja", "id_usuario_baja": "Usuario que dio de baja", "motivo_baja": "Motivo de la baja", "creado_por": "Usuario que registró", "actualizado_por": "Usuario que modificó", "creado_en": "Fecha de registro", "actualizado_en": "Última modificación", "id_usuario": "Usuario", "id_usuario_actor": "Usuario que realizó la acción", "id_proyecto": "Proyecto", "nombre_proyecto": "Nombre del proyecto", "id_nucleo": "Núcleo", "id_proyecto_nucleo": "Núcleo del proyecto", "srid_trabajo": "Sistema de coordenadas", "fecha_firma": "Fecha de firma", "no_parcela": "Número de parcela"};
 const humanizar = v => {const t=String(v??'').replaceAll('_',' ').trim();return t ? t[0].toUpperCase()+t.slice(1) : '—';};
 const acciones={insert:'Alta',create:'Alta',update:'Modificación',delete:'Baja',login_exitoso:'Inicio de sesión',login_fallido:'Inicio de sesión fallido',logout:'Cierre de sesión',cuenta_bloqueada:'Cuenta bloqueada',sesion_revocada:'Sesión cerrada por revocación',sesion_expirada:'Sesión vencida',cambio_correo:'Cambio de correo',restablecimiento_contrasena:'Restablecimiento de contraseña',cambio_contrasena:'Cambio de contraseña',reset_contrasena_admin:'Restablecimiento de contraseña',desbloqueo:'Desbloqueo',bloqueo:'Bloqueo de acceso'};
 const entidad=v=>entidades[v]||humanizar(v);
 const campo=(tipo,v)=>comunes[v]||campos[tipo]?.[v]||humanizar(v);
 const accion=v=>acciones[v]||humanizar(v);
 const fecha=v=>{if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);const z=n=>String(n).padStart(2,'0');return `${z(d.getDate())}-${z(d.getMonth()+1)}-${d.getFullYear()} ${z(d.getHours())}:${z(d.getMinutes())}`;};
 function valor(v,k,resolver){if(v==null||v==='')return '—';if(typeof v==='boolean')return v?'Sí':'No';if(/usuario|creado_por|actualizado_por/.test(k)&&/^\d+$/.test(String(v)))return resolver(Number(v))||'Usuario sin nombre disponible';if(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(v))return fecha(v);if(typeof v==='object')return Array.isArray(v)?v.map(x=>valor(x,k,resolver)).join('; '):Object.entries(v).map(([a,b])=>`${humanizar(a)}: ${valor(b,a,resolver)}`).join('; ');if(k.startsWith('id_'))return 'Referencia registrada (ver detalle técnico)';return typeof v==='string'&&v.includes('_')?humanizar(v):String(v);}
 window.SSALFER_AUDITORIA={entidades,entidad,campo,accion,fecha,valor,humanizar};
})();
