-- Historia funcional auditada de los seguimientos provenientes de Excel.
-- Las migraciones 001, 002 y 003 son inmutables.
SET search_path = public, pg_catalog;
SELECT set_config('app.current_user_id', COALESCE((SELECT min(id_usuario)::text FROM usuario),'1'), false);

CREATE TABLE IF NOT EXISTS seguimiento_evento (
    id_seguimiento_evento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto_nucleo integer NOT NULL REFERENCES proyecto_nucleo(id_proyecto_nucleo),
    entidad_tipo varchar(50),
    entidad_id bigint,
    ambito varchar(20) NOT NULL,
    id_tipo_evento bigint NOT NULL REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_motivo bigint REFERENCES catalogo_operativo(id_catalogo_opcion),
    fecha_evento date,
    detalle text,
    id_documento integer REFERENCES documento(id_documento),
    fuente varchar(250),
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT now(),
    creado_por integer REFERENCES usuario(id_usuario),
    actualizado_en timestamptz,
    actualizado_por integer REFERENCES usuario(id_usuario),
    fecha_baja timestamptz,
    id_usuario_baja integer REFERENCES usuario(id_usuario),
    motivo_baja text,
    observaciones text,
    CONSTRAINT chk_seguimiento_evento_ambito CHECK (ambito IN ('general','colectivo','individual')),
    CONSTRAINT chk_seguimiento_evento_objetivo CHECK (
        (entidad_tipo IS NULL AND entidad_id IS NULL) OR
        (entidad_tipo IN ('proyecto_nucleo','afectacion','parcela','parcela_titular',
                          'unidad_agraria','asamblea','asamblea_convocatoria','convenio',
                          'tramite_ran','tramite_ran_evento','tramite_fifonafe',
                          'tramite_fifonafe_evento','orv','padron_historial','indemnizacion')
         AND entidad_id IS NOT NULL)
    ),
    CONSTRAINT chk_seguimiento_evento_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL) OR
        (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
         AND NULLIF(btrim(motivo_baja),'') IS NOT NULL)
    )
);
CREATE INDEX IF NOT EXISTS ix_seguimiento_evento_pn_fecha
    ON seguimiento_evento(id_proyecto_nucleo, fecha_evento DESC, id_seguimiento_evento DESC)
    WHERE activo;
CREATE INDEX IF NOT EXISTS ix_seguimiento_evento_objetivo
    ON seguimiento_evento(entidad_tipo, entidad_id) WHERE activo;

ALTER TABLE catalogo_operativo DISABLE TRIGGER trg_audit_catalogo_operativo;
INSERT INTO catalogo_operativo(tipo_catalogo,codigo,nombre,descripcion,orden,fuente)
SELECT 'tipo_evento_seguimiento', v.codigo, v.nombre, v.descripcion, v.orden, 'Excel seguimiento funcional 2026'
FROM (VALUES
 ('inicio','Inicio','Inicio de seguimiento',10),
 ('suspension','Suspensión','Suspensión funcional del seguimiento',20),
 ('reapertura','Reapertura','Reanudación explícita del seguimiento',30),
 ('cierre','Cierre','Cierre funcional del seguimiento',40),
 ('cambio_alcance','Cambio de alcance','Cambio de afectación o alcance',50),
 ('reunion','Reunión','Reunión de seguimiento',60),
 ('negociacion','Negociación','Negociación',70),
 ('consulta_indigena','Consulta indígena','Consulta o proceso indígena',80),
 ('continuacion_asamblea','Continuación de asamblea','Continuación de una asamblea permanente',90),
 ('medicion_bdt','Medición BDT','Medición o actualización BDT',100),
 ('otro','Otro','Otro evento funcional',999)
) AS v(codigo,nombre,descripcion,orden)
WHERE NOT EXISTS (SELECT 1 FROM catalogo_operativo c WHERE c.tipo_catalogo='tipo_evento_seguimiento' AND c.codigo=v.codigo);
INSERT INTO catalogo_operativo(tipo_catalogo,codigo,nombre,descripcion,orden,fuente)
SELECT 'motivo_seguimiento', v.codigo, v.nombre, v.descripcion, v.orden, 'Excel seguimiento funcional 2026'
FROM (VALUES
 ('expropiacion_directa','Expropiación directa','Seguimiento suspendido o cambiado por expropiación directa',10),
 ('no_afectacion','No afectación','Sin afectación en el alcance informado',20),
 ('comunidad_indigena','Comunidad indígena','Motivo funcional vinculado a comunidad o consulta',30),
 ('dominio_pleno','Dominio pleno','Salida o cambio de seguimiento agrario individual',40),
 ('juicio_agrario','Juicio agrario','Juicio agrario o TUA',50),
 ('conflicto_titularidad','Conflicto de titularidad','Conflicto, doble asignación o posesión en revisión',60),
 ('rechazo','Rechazo','Rechazo del procedimiento',70),
 ('cambio_trazo','Cambio de trazo','Nueva presentación o cambio de trazo',80),
 ('nueva_informacion','Nueva información','Información posterior que reabre o cambia alcance',90),
 ('calificacion_negativa','Calificación negativa','Resultado registral negativo',100),
 ('falta_pago','Falta de pago','Pendiente de pago',110),
 ('otro','Otro','Otro motivo; exige detalle',999)
) AS v(codigo,nombre,descripcion,orden)
WHERE NOT EXISTS (SELECT 1 FROM catalogo_operativo c WHERE c.tipo_catalogo='motivo_seguimiento' AND c.codigo=v.codigo);
INSERT INTO catalogo_operativo(tipo_catalogo,codigo,nombre,descripcion,orden,fuente)
SELECT 'estado_requisito_documental',v.codigo,v.nombre,v.descripcion,v.orden,'Excel seguimiento funcional 2026'
FROM (VALUES
 ('parcial','Parcial','Documentación disponible sólo parcialmente',35),
 ('pendiente_validacion','Pendiente de validación','Archivo disponible pendiente de revisión o inconsistencia',36)
) AS v(codigo,nombre,descripcion,orden)
WHERE NOT EXISTS (SELECT 1 FROM catalogo_operativo c WHERE c.tipo_catalogo='estado_requisito_documental' AND c.codigo=v.codigo);
ALTER TABLE catalogo_operativo ENABLE TRIGGER trg_audit_catalogo_operativo;

ALTER TABLE requisito_documental DISABLE TRIGGER trg_audit_requisito_documental;
INSERT INTO requisito_documental(codigo,nombre,descripcion,contexto,obligatorio,orden,fuente)
SELECT v.codigo,v.nombre,v.descripcion,'general',false,v.orden,'Excel seguimiento funcional 2026'
FROM (VALUES
 ('validacion_pa_sict','Validación PA/SICT','Validación funcional PA/SICT',900),
 ('oficio_ran_parcelas_afectacion','Oficio RAN de parcelas con afectación','Oficio RAN relativo a parcelas afectadas',910),
 ('acta_complementaria','Acta complementaria','Acta complementaria de seguimiento',920)
) AS v(codigo,nombre,descripcion,orden)
WHERE NOT EXISTS (SELECT 1 FROM requisito_documental r WHERE r.codigo=v.codigo);
ALTER TABLE requisito_documental ENABLE TRIGGER trg_audit_requisito_documental;

CREATE OR REPLACE FUNCTION fn_objetivo_seguimiento_en_pn(p_tipo text, p_id bigint, p_pn integer)
RETURNS boolean LANGUAGE plpgsql STABLE AS $$
BEGIN
    -- 002 ya contiene las relaciones canónicas de todos los objetivos de 004.
    RETURN fn_objetivo_requisito_en_pn(p_tipo,p_id,p_pn);
END;
$$;

CREATE OR REPLACE FUNCTION fn_validar_seguimiento_evento() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_tipo text; v_motivo text;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW.id_proyecto_nucleo <> OLD.id_proyecto_nucleo THEN
            RAISE EXCEPTION 'No se permite cambiar el ProyectoNucleo de un evento de seguimiento';
        END IF;
        IF NEW.ambito <> OLD.ambito THEN
            RAISE EXCEPTION 'No se permite cambiar el ámbito de un evento de seguimiento';
        END IF;
        IF NEW.id_tipo_evento <> OLD.id_tipo_evento THEN
            RAISE EXCEPTION 'No se permite reescribir el tipo de evento; la transición debe registrarse mediante un nuevo evento';
        END IF;
        IF NEW.id_motivo IS DISTINCT FROM OLD.id_motivo THEN
            RAISE EXCEPTION 'No se permite cambiar el motivo de un evento de seguimiento';
        END IF;
        IF (NEW.entidad_tipo IS DISTINCT FROM OLD.entidad_tipo) OR (NEW.entidad_id IS DISTINCT FROM OLD.entidad_id) THEN
            RAISE EXCEPTION 'No se permite cambiar el objetivo de un evento de seguimiento';
        END IF;
    END IF;

    IF NOT fn_opcion_catalogo_valida(NEW.id_tipo_evento,'tipo_evento_seguimiento') THEN
        RAISE EXCEPTION 'Tipo de evento de seguimiento inválido';
    END IF;
    IF NEW.id_motivo IS NOT NULL AND NOT fn_opcion_catalogo_valida(NEW.id_motivo,'motivo_seguimiento') THEN
        RAISE EXCEPTION 'Motivo de seguimiento inválido';
    END IF;
    IF NEW.entidad_tipo IS NOT NULL
       AND NOT fn_objetivo_seguimiento_en_pn(NEW.entidad_tipo,NEW.entidad_id,NEW.id_proyecto_nucleo) THEN
        RAISE EXCEPTION 'El objetivo de seguimiento no existe, está inactivo o no pertenece al ProyectoNucleo';
    END IF;
    SELECT codigo INTO v_tipo FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_tipo_evento;
    SELECT codigo INTO v_motivo FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_motivo;
    IF v_tipo='suspension' AND NEW.id_motivo IS NULL THEN
        RAISE EXCEPTION 'La suspensión requiere motivo';
    END IF;
    IF v_tipo='reapertura' AND NULLIF(btrim(NEW.detalle),'') IS NULL THEN
        RAISE EXCEPTION 'La reapertura requiere detalle';
    END IF;
    IF v_tipo IN ('cierre','cambio_alcance') AND (NEW.id_motivo IS NULL OR NULLIF(btrim(NEW.detalle),'') IS NULL) THEN
        RAISE EXCEPTION '% requiere motivo y detalle', v_tipo;
    END IF;
    IF v_motivo='otro' AND NULLIF(btrim(NEW.detalle),'') IS NULL THEN
        RAISE EXCEPTION 'El motivo otro requiere detalle';
    END IF;
    IF v_tipo='continuacion_asamblea' AND NEW.entidad_tipo NOT IN ('asamblea','asamblea_convocatoria') THEN
        RAISE EXCEPTION 'La continuación de asamblea requiere objetivo asamblea o convocatoria';
    END IF;
    IF v_motivo='dominio_pleno' AND (NEW.ambito <> 'individual' OR NEW.entidad_tipo NOT IN ('parcela','afectacion','unidad_agraria')) THEN
        RAISE EXCEPTION 'Dominio pleno sólo admite ámbito individual y objetivo parcela, afectación o unidad agraria';
    END IF;
    IF v_motivo IN ('conflicto_titularidad','juicio_agrario') AND (NEW.ambito <> 'individual' OR NEW.entidad_tipo NOT IN ('parcela','parcela_titular','afectacion','unidad_agraria')) THEN
        RAISE EXCEPTION 'Conflicto de titularidad o juicio agrario sólo admite objetivo individual compatible';
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_validar_seguimiento_evento ON seguimiento_evento;
CREATE TRIGGER trg_validar_seguimiento_evento BEFORE INSERT OR UPDATE ON seguimiento_evento
FOR EACH ROW EXECUTE FUNCTION fn_validar_seguimiento_evento();
DROP TRIGGER IF EXISTS trg_audit_seguimiento_evento ON seguimiento_evento;
CREATE TRIGGER trg_audit_seguimiento_evento AFTER INSERT OR UPDATE ON seguimiento_evento
FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_seguimiento_evento');
DROP TRIGGER IF EXISTS trg_prevent_delete_seguimiento_evento ON seguimiento_evento;
CREATE TRIGGER trg_prevent_delete_seguimiento_evento BEFORE DELETE ON seguimiento_evento
FOR EACH ROW EXECUTE FUNCTION fn_prevenir_delete_fisico();

CREATE OR REPLACE VIEW vw_seguimiento_estado_actual AS
WITH transicion AS (
  SELECT se.*, co.codigo AS tipo_evento_codigo, mo.codigo AS motivo_codigo,
         row_number() OVER (
             PARTITION BY se.id_proyecto_nucleo, coalesce(se.entidad_tipo,'proyecto_nucleo'),
                          coalesce(se.entidad_id,se.id_proyecto_nucleo)
             ORDER BY se.fecha_evento DESC NULLS LAST, se.id_seguimiento_evento DESC
         ) AS rn
  FROM seguimiento_evento se
  JOIN catalogo_operativo co ON co.id_catalogo_opcion=se.id_tipo_evento
  LEFT JOIN catalogo_operativo mo ON mo.id_catalogo_opcion=se.id_motivo
  WHERE se.activo AND co.codigo IN ('inicio','suspension','reapertura','cierre')
)
SELECT id_proyecto_nucleo, entidad_tipo, entidad_id,
       CASE tipo_evento_codigo WHEN 'suspension' THEN 'suspendido' WHEN 'cierre' THEN 'cerrado' ELSE 'activo' END AS estado_actual,
       tipo_evento_codigo AS tipo_ultimo_evento, motivo_codigo AS motivo_actual,
       fecha_evento AS fecha_ultimo_evento, detalle, ambito
FROM transicion WHERE rn=1;
