-- Derecho de Via poligonal, versionado por proyecto. No altera trazo_proyecto.
SET search_path = public, pg_catalog;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM schema_migrations
         WHERE version = '020'
           AND checksum_sha256 = 'cfa4dadb2e8b5bb9b8cddddf617c34132380ad49a660de9037de43850263f4c8'
    ) THEN
        RAISE EXCEPTION '021 requiere la migracion 020 exacta';
    END IF;
    IF EXISTS (SELECT 1 FROM schema_migrations WHERE version = '021') THEN
        RAISE EXCEPTION '021 ya se encuentra registrada';
    END IF;
END $$;

SELECT pg_advisory_xact_lock(
    hashtextextended('software-pa:021:derecho-via-proyecto', 0)
);

CREATE TABLE derecho_via_proyecto (
    id_derecho_via integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto integer NOT NULL REFERENCES proyecto(id_proyecto),
    version integer NOT NULL,
    es_vigente boolean NOT NULL DEFAULT false,
    geometria_poligono geometry(MULTIPOLYGON, 4326) NOT NULL,
    fuente varchar(250) NOT NULL,
    fecha_fuente date,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT now(),
    creado_por integer REFERENCES usuario(id_usuario),
    actualizado_en timestamptz,
    actualizado_por integer REFERENCES usuario(id_usuario),
    fecha_baja timestamptz,
    id_usuario_baja integer REFERENCES usuario(id_usuario),
    motivo_baja text,
    observaciones text,
    CONSTRAINT uq_derecho_via_proyecto_version UNIQUE (id_proyecto, version),
    CONSTRAINT chk_derecho_via_version CHECK (version > 0),
    CONSTRAINT chk_derecho_via_fuente CHECK (NULLIF(btrim(fuente), '') IS NOT NULL),
    CONSTRAINT chk_derecho_via_geometria CHECK (
        NOT ST_IsEmpty(geometria_poligono)
        AND ST_IsValid(geometria_poligono)
        AND ST_SRID(geometria_poligono) = 4326
        AND GeometryType(geometria_poligono) = 'MULTIPOLYGON'
    ),
    CONSTRAINT chk_derecho_via_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    ),
    CONSTRAINT chk_derecho_via_vigente_activo CHECK (NOT es_vigente OR activo)
);

CREATE UNIQUE INDEX uq_derecho_via_proyecto_vigente
    ON derecho_via_proyecto (id_proyecto) WHERE es_vigente;
CREATE INDEX idx_derecho_via_proyecto_geom
    ON derecho_via_proyecto USING gist (geometria_poligono);

CREATE TRIGGER trg_audit_derecho_via_proyecto
AFTER INSERT OR UPDATE ON derecho_via_proyecto
FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_derecho_via');

CREATE TRIGGER trg_prevent_delete_derecho_via_proyecto
BEFORE DELETE ON derecho_via_proyecto
FOR EACH ROW EXECUTE FUNCTION fn_prevenir_delete_fisico();

COMMENT ON TABLE derecho_via_proyecto IS
    'Derecho de Via poligonal por proyecto; conserva versiones historicas activas.';
COMMENT ON COLUMN derecho_via_proyecto.es_vigente IS
    'Version cartografica vigente. Independiente de activo, que indica baja logica.';

GRANT SELECT, INSERT, UPDATE ON derecho_via_proyecto TO software_pa_app;
GRANT USAGE, SELECT ON SEQUENCE derecho_via_proyecto_id_derecho_via_seq TO software_pa_app;
