-- GIS complementa destinos administrativos existentes. No crea afectaciones.
SET search_path = public, pg_catalog;
DO $$ BEGIN
 IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version='024'
 AND checksum_sha256='15f36ea78a591aeb0f587a84e7e2bddb21f53de455d80daaf8532422796bc2d6') THEN
  RAISE EXCEPTION '025 requiere la migracion 024 exacta';
 END IF;
 IF EXISTS (SELECT 1 FROM schema_migrations WHERE version='025') THEN
  RAISE EXCEPTION '025 ya se encuentra registrada';
 END IF;
END $$;
SELECT pg_advisory_xact_lock(hashtextextended('software-pa:025:conciliacion-gis-proyecto',0));

CREATE TABLE proyecto_configuracion_gis (
 id_proyecto integer PRIMARY KEY REFERENCES proyecto,
 srid_trabajo integer NOT NULL REFERENCES spatial_ref_sys(srid),
 activo boolean NOT NULL DEFAULT true,
 creado_en timestamptz NOT NULL DEFAULT now(), creado_por integer REFERENCES usuario,
 actualizado_en timestamptz, actualizado_por integer REFERENCES usuario,
 fecha_baja timestamptz, id_usuario_baja integer REFERENCES usuario, motivo_baja text, observaciones text
);
COMMENT ON TABLE proyecto_configuracion_gis IS
 'CRS de trabajo explícito por proyecto; sin configuración se trabaja en 4326. No hay UTM nacional.';

ALTER TABLE importacion_archivo
 ADD COLUMN version_pipeline varchar(40) NOT NULL DEFAULT 'legacy-v1',
 ADD COLUMN srid_trabajo integer NOT NULL DEFAULT 4326 REFERENCES spatial_ref_sys(srid),
 ADD COLUMN crs_fuente_wkt text;
DROP INDEX uq_importacion_idempotente;
CREATE UNIQUE INDEX uq_importacion_idempotente ON importacion_archivo
 (id_proyecto,tipo_objetivo,sha256,version_pipeline,srid_trabajo) WHERE activo;
COMMENT ON COLUMN importacion_archivo.version_pipeline IS
 'Identidad del procesamiento; el SHA original se puede reprocesar con otra versión o CRS de trabajo.';

ALTER TABLE importacion_feature
 ADD COLUMN geometria_original geometry,
 ADD COLUMN geometria_trabajo geometry(MULTIPOLYGON),
 ADD COLUMN crs_fuente text,
 ADD COLUMN dimension_fuente varchar(8),
 ADD COLUMN estado_conciliacion varchar(30) NOT NULL DEFAULT 'pendiente',
 ADD CONSTRAINT uq_feature_importacion_id UNIQUE(id_importacion_feature,id_importacion),
 ADD CONSTRAINT chk_feature_conciliacion CHECK(estado_conciliacion IN
 ('pendiente','coincidencia_exacta','candidato','ambiguo','sin_coincidencia','confirmado','rechazado','ignorado')),
 ADD CONSTRAINT chk_feature_dimension CHECK(dimension_fuente IS NULL OR dimension_fuente IN ('XY','XYZ','XYM','XYZM')),
 ADD CONSTRAINT chk_feature_trabajo CHECK(geometria_trabajo IS NULL OR
 (ST_IsValid(geometria_trabajo) AND NOT ST_IsEmpty(geometria_trabajo) AND ST_NDims(geometria_trabajo)=2));
CREATE INDEX idx_feature_conciliacion ON importacion_feature(id_importacion,estado_conciliacion);
CREATE INDEX idx_feature_trabajo ON importacion_feature USING gist(geometria_trabajo);

-- Únicamente relaciones administrativas preexistentes acreditan parcelas del proyecto.
CREATE VIEW vw_gis_parcela_proyecto AS
 SELECT DISTINCT pn.id_proyecto,pn.id_proyecto_nucleo,p.id_parcela,p.id_nucleo
 FROM proyecto_nucleo pn JOIN proyecto pr USING(id_proyecto)
 JOIN nucleo_agrario n USING(id_nucleo)
 JOIN afectacion a USING(id_proyecto_nucleo)
 JOIN afectacion_unidad_agraria au USING(id_afectacion)
 JOIN unidad_agraria u USING(id_unidad_agraria)
 JOIN parcela p ON p.id_parcela=u.id_parcela AND p.id_nucleo=pn.id_nucleo AND u.id_nucleo=pn.id_nucleo
 WHERE pn.activo AND pr.activo AND n.activo AND a.activo AND au.activo AND u.activo AND p.activo;
COMMENT ON VIEW vw_gis_parcela_proyecto IS
 'Universo GIS de parcelas: sólo vínculos administrativos activos por afectación; ST_Intersects no interviene.';

CREATE TABLE importacion_feature_candidato (
 id_candidato bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_importacion bigint NOT NULL REFERENCES importacion_archivo,
 id_importacion_feature bigint NOT NULL,
 id_proyecto_nucleo integer NOT NULL REFERENCES proyecto_nucleo,
 id_parcela integer REFERENCES parcela,
 criterio varchar(80) NOT NULL,
 clasificacion varchar(20) NOT NULL CHECK(clasificacion IN('exacta','fuerte','revision')),
 coincidencias jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(coincidencias)='array'),
 estado varchar(20) NOT NULL DEFAULT 'propuesto' CHECK(estado IN('propuesto','seleccionado','rechazado','confirmado')),
 id_usuario_revision integer REFERENCES usuario, fecha_revision timestamptz,
 geometria_previa_hash text,
 activo boolean NOT NULL DEFAULT true,
 creado_en timestamptz NOT NULL DEFAULT now(), creado_por integer REFERENCES usuario,
 actualizado_en timestamptz, actualizado_por integer REFERENCES usuario,
 fecha_baja timestamptz, id_usuario_baja integer REFERENCES usuario, motivo_baja text, observaciones text,
 FOREIGN KEY(id_importacion_feature,id_importacion) REFERENCES importacion_feature(id_importacion_feature,id_importacion),
 UNIQUE(id_candidato,id_importacion_feature)
);
CREATE UNIQUE INDEX uq_candidato_destino ON importacion_feature_candidato
 (id_importacion_feature,id_proyecto_nucleo,COALESCE(id_parcela,0));
CREATE UNIQUE INDEX uq_candidato_seleccion_feature ON importacion_feature_candidato
 (id_importacion_feature) WHERE estado IN('seleccionado','confirmado');
CREATE UNIQUE INDEX uq_candidato_seleccion_nucleo ON importacion_feature_candidato
 (id_importacion,id_proyecto_nucleo) WHERE id_parcela IS NULL AND estado IN('seleccionado','confirmado');
CREATE UNIQUE INDEX uq_candidato_seleccion_parcela ON importacion_feature_candidato
 (id_importacion,id_proyecto_nucleo,id_parcela) WHERE id_parcela IS NOT NULL AND estado IN('seleccionado','confirmado');
CREATE INDEX idx_candidato_importacion ON importacion_feature_candidato(id_importacion,estado);

CREATE TABLE importacion_feature_decision (
 id_decision bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_importacion_feature bigint NOT NULL REFERENCES importacion_feature,
 id_candidato bigint,
 accion varchar(20) NOT NULL CHECK(accion IN('seleccionar','confirmar','rechazar','ignorar')),
 motivo varchar(250), creado_por integer NOT NULL REFERENCES usuario,
 creado_en timestamptz NOT NULL DEFAULT now(),
 FOREIGN KEY(id_candidato,id_importacion_feature) REFERENCES importacion_feature_candidato(id_candidato,id_importacion_feature),
 CHECK((accion='ignorar' AND id_candidato IS NULL) OR (accion<>'ignorar' AND id_candidato IS NOT NULL))
);
CREATE INDEX idx_decision_feature ON importacion_feature_decision(id_importacion_feature,creado_en);
CREATE FUNCTION fn_gis_decision_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN RAISE EXCEPTION 'Las decisiones GIS son append-only'; END $$;
CREATE TRIGGER trg_gis_decision_inmutable BEFORE UPDATE OR DELETE ON importacion_feature_decision
 FOR EACH ROW EXECUTE FUNCTION fn_gis_decision_inmutable();

CREATE TABLE proyecto_nucleo_geometria (
 id_geometria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_proyecto_nucleo integer NOT NULL REFERENCES proyecto_nucleo,
 id_importacion_feature bigint NOT NULL UNIQUE REFERENCES importacion_feature,
 version integer NOT NULL CHECK(version>0), es_vigente boolean NOT NULL DEFAULT true,
 geometria_poligono geometry(MULTIPOLYGON,4326) NOT NULL,
 geometria_trabajo geometry(MULTIPOLYGON) NOT NULL,
 srid_trabajo integer NOT NULL REFERENCES spatial_ref_sys(srid),
 fuente varchar(250) NOT NULL CHECK(NULLIF(btrim(fuente),'') IS NOT NULL), fecha_fuente date,
 activo boolean NOT NULL DEFAULT true,
 creado_en timestamptz NOT NULL DEFAULT now(), creado_por integer REFERENCES usuario,
 actualizado_en timestamptz, actualizado_por integer REFERENCES usuario,
 fecha_baja timestamptz, id_usuario_baja integer REFERENCES usuario, motivo_baja text, observaciones text,
 UNIQUE(id_proyecto_nucleo,version),
 CHECK(NOT es_vigente OR activo),
 CHECK(ST_IsValid(geometria_poligono) AND NOT ST_IsEmpty(geometria_poligono)),
 CHECK(ST_IsValid(geometria_trabajo) AND NOT ST_IsEmpty(geometria_trabajo)
 AND ST_SRID(geometria_trabajo)=srid_trabajo AND ST_NDims(geometria_trabajo)=2)
);
CREATE TABLE proyecto_parcela_geometria (
 id_geometria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_proyecto_nucleo integer NOT NULL REFERENCES proyecto_nucleo,
 id_parcela integer NOT NULL REFERENCES parcela,
 id_importacion_feature bigint NOT NULL UNIQUE REFERENCES importacion_feature,
 version integer NOT NULL CHECK(version>0), es_vigente boolean NOT NULL DEFAULT true,
 geometria_poligono geometry(MULTIPOLYGON,4326) NOT NULL,
 geometria_trabajo geometry(MULTIPOLYGON) NOT NULL,
 srid_trabajo integer NOT NULL REFERENCES spatial_ref_sys(srid),
 fuente varchar(250) NOT NULL CHECK(NULLIF(btrim(fuente),'') IS NOT NULL), fecha_fuente date,
 activo boolean NOT NULL DEFAULT true,
 creado_en timestamptz NOT NULL DEFAULT now(), creado_por integer REFERENCES usuario,
 actualizado_en timestamptz, actualizado_por integer REFERENCES usuario,
 fecha_baja timestamptz, id_usuario_baja integer REFERENCES usuario, motivo_baja text, observaciones text,
 UNIQUE(id_proyecto_nucleo,id_parcela,version),
 CHECK(NOT es_vigente OR activo),
 CHECK(ST_IsValid(geometria_poligono) AND NOT ST_IsEmpty(geometria_poligono)),
 CHECK(ST_IsValid(geometria_trabajo) AND NOT ST_IsEmpty(geometria_trabajo)
 AND ST_SRID(geometria_trabajo)=srid_trabajo AND ST_NDims(geometria_trabajo)=2)
);
CREATE UNIQUE INDEX uq_nucleo_geometria_vigente ON proyecto_nucleo_geometria(id_proyecto_nucleo) WHERE es_vigente;
CREATE UNIQUE INDEX uq_parcela_geometria_vigente ON proyecto_parcela_geometria(id_proyecto_nucleo,id_parcela) WHERE es_vigente;
CREATE INDEX idx_proyecto_nucleo_geometria ON proyecto_nucleo_geometria USING gist(geometria_poligono);
CREATE INDEX idx_proyecto_nucleo_geometria_trabajo ON proyecto_nucleo_geometria USING gist(geometria_trabajo);
CREATE INDEX idx_proyecto_parcela_geometria ON proyecto_parcela_geometria USING gist(geometria_poligono);
CREATE INDEX idx_proyecto_parcela_geometria_trabajo ON proyecto_parcela_geometria USING gist(geometria_trabajo);

ALTER TABLE derecho_via_proyecto
 ADD COLUMN id_importacion bigint REFERENCES importacion_archivo,
 ADD COLUMN sha256 char(64),
 ADD COLUMN srid_trabajo integer REFERENCES spatial_ref_sys(srid),
 ADD COLUMN geometria_trabajo geometry(MULTIPOLYGON),
 ADD CONSTRAINT chk_ddv_trabajo CHECK(geometria_trabajo IS NULL OR
 (ST_IsValid(geometria_trabajo) AND NOT ST_IsEmpty(geometria_trabajo)
 AND ST_SRID(geometria_trabajo)=srid_trabajo AND ST_NDims(geometria_trabajo)=2));
CREATE INDEX idx_ddv_trabajo ON derecho_via_proyecto USING gist(geometria_trabajo);

CREATE FUNCTION fn_gis_validar_candidato() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE v_proyecto integer; v_objetivo text; v_version text;
 BEGIN
 SELECT id_proyecto,tipo_objetivo,version_pipeline INTO v_proyecto,v_objetivo,v_version
 FROM importacion_archivo WHERE id_importacion=NEW.id_importacion AND activo;
 IF v_proyecto IS NULL OR v_version='legacy-v1' OR NOT EXISTS(
 SELECT 1 FROM proyecto_nucleo pn JOIN nucleo_agrario n USING(id_nucleo) JOIN proyecto pr USING(id_proyecto)
 WHERE pn.id_proyecto_nucleo=NEW.id_proyecto_nucleo AND pn.id_proyecto=v_proyecto AND pn.activo AND n.activo AND pr.activo)
 THEN RAISE EXCEPTION 'Candidato fuera del universo administrativo del proyecto'; END IF;
 IF v_objetivo IN('parcela','parcela_gpkg') THEN
  IF NEW.id_parcela IS NULL OR NOT EXISTS(SELECT 1 FROM vw_gis_parcela_proyecto
   WHERE id_proyecto_nucleo=NEW.id_proyecto_nucleo AND id_parcela=NEW.id_parcela AND id_proyecto=v_proyecto)
  THEN RAISE EXCEPTION 'Parcela sin vinculo administrativo activo con el proyecto'; END IF;
 ELSIF v_objetivo IN('nucleo_agrario','nucleo_agrario_gpkg') THEN
  IF NEW.id_parcela IS NOT NULL THEN RAISE EXCEPTION 'Destino no corresponde a nucleo'; END IF;
 ELSE RAISE EXCEPTION 'Objetivo no conciliable'; END IF;
 IF NEW.estado IN('seleccionado','confirmado') AND NOT EXISTS(SELECT 1 FROM usuario
 WHERE id_usuario=NULLIF(current_setting('app.current_user_id',true),'')::integer AND activo AND rol IN('admin','geografo'))
 THEN RAISE EXCEPTION 'Decision GIS requiere admin o geografo'; END IF;
 IF TG_OP='UPDATE' AND OLD.estado='confirmado' AND to_jsonb(NEW) IS DISTINCT FROM to_jsonb(OLD)
 THEN RAISE EXCEPTION 'Candidato confirmado inmutable'; END IF;
 RETURN NEW;
 END $$;
CREATE TRIGGER trg_gis_candidato_ambito BEFORE INSERT OR UPDATE ON importacion_feature_candidato
 FOR EACH ROW EXECUTE FUNCTION fn_gis_validar_candidato();

CREATE FUNCTION fn_gis_validar_geometria_contexto() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE v_feature importacion_feature%ROWTYPE; v_import importacion_archivo%ROWTYPE;
 BEGIN
 SELECT * INTO v_feature FROM importacion_feature WHERE id_importacion_feature=NEW.id_importacion_feature;
 SELECT * INTO v_import FROM importacion_archivo WHERE id_importacion=v_feature.id_importacion;
 IF v_feature.estado_conciliacion<>'confirmado' OR NOT EXISTS(
 SELECT 1 FROM importacion_feature_candidato c JOIN proyecto_nucleo pn USING(id_proyecto_nucleo)
 WHERE c.id_importacion_feature=NEW.id_importacion_feature AND c.estado='confirmado'
 AND c.id_proyecto_nucleo=NEW.id_proyecto_nucleo AND pn.id_proyecto=v_import.id_proyecto
 AND ((TG_TABLE_NAME='proyecto_nucleo_geometria' AND c.id_parcela IS NULL)
 OR (TG_TABLE_NAME='proyecto_parcela_geometria' AND c.id_parcela=(to_jsonb(NEW)->>'id_parcela')::integer)))
 THEN RAISE EXCEPTION 'Geometria sin destino confirmado del mismo proyecto'; END IF;
 IF NEW.srid_trabajo<>v_import.srid_trabajo OR NEW.geometria_poligono IS DISTINCT FROM v_feature.geometria_normalizada
 OR NEW.geometria_trabajo IS DISTINCT FROM v_feature.geometria_trabajo
 THEN RAISE EXCEPTION 'Geometria o CRS distintos del staging confirmado'; END IF;
 RETURN NEW;
 END $$;
CREATE TRIGGER trg_nucleo_geometria_contexto BEFORE INSERT OR UPDATE ON proyecto_nucleo_geometria
 FOR EACH ROW EXECUTE FUNCTION fn_gis_validar_geometria_contexto();
CREATE TRIGGER trg_parcela_geometria_contexto BEFORE INSERT OR UPDATE ON proyecto_parcela_geometria
 FOR EACH ROW EXECUTE FUNCTION fn_gis_validar_geometria_contexto();

-- Guardas de CRS: la configuración no puede cambiar mientras existan geometrías confirmadas.
CREATE FUNCTION fn_gis_configuracion_coherente() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN
 IF ((TG_OP='INSERT' AND NEW.srid_trabajo<>4326) OR (TG_OP='UPDATE' AND (NEW.srid_trabajo<>OLD.srid_trabajo OR NOT NEW.activo))) AND EXISTS(
 SELECT 1 FROM importacion_archivo WHERE id_proyecto=NEW.id_proyecto AND importados>0 AND version_pipeline<>'legacy-v1')
 THEN RAISE EXCEPTION 'CRS en uso; requiere reproyeccion explicita de las geometrías del proyecto'; END IF;
 RETURN NEW;
 END $$;
CREATE TRIGGER trg_gis_configuracion_coherente BEFORE INSERT OR UPDATE ON proyecto_configuracion_gis
 FOR EACH ROW EXECUTE FUNCTION fn_gis_configuracion_coherente();

DO $$ DECLARE v_table text; v_pk text; BEGIN
 FOREACH v_table IN ARRAY ARRAY['proyecto_configuracion_gis','importacion_feature_candidato',
 'proyecto_nucleo_geometria','proyecto_parcela_geometria','importacion_feature_decision'] LOOP
  v_pk:=CASE v_table WHEN 'proyecto_configuracion_gis' THEN 'id_proyecto'
   WHEN 'importacion_feature_candidato' THEN 'id_candidato'
   WHEN 'importacion_feature_decision' THEN 'id_decision' ELSE 'id_geometria' END;
  EXECUTE format('CREATE TRIGGER %I AFTER INSERT OR UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION fn_audit_log(%L)','trg_audit_'||v_table,v_table,v_pk);
  IF v_table<>'importacion_feature_decision' THEN
   EXECUTE format('CREATE TRIGGER %I BEFORE DELETE ON %I FOR EACH ROW EXECUTE FUNCTION fn_prevenir_delete_fisico()','trg_prevent_delete_'||v_table,v_table);
  END IF;
  EXECUTE format('GRANT SELECT,INSERT,UPDATE ON %I TO software_pa_app',v_table);
 END LOOP;
END $$;
REVOKE UPDATE ON importacion_feature_decision FROM software_pa_app;
GRANT SELECT ON vw_gis_parcela_proyecto TO software_pa_app;
GRANT USAGE,SELECT ON SEQUENCE importacion_feature_candidato_id_candidato_seq,
 importacion_feature_decision_id_decision_seq, proyecto_nucleo_geometria_id_geometria_seq,
 proyecto_parcela_geometria_id_geometria_seq TO software_pa_app;

CREATE OR REPLACE FUNCTION fn_validar_importacion_feature_objetivo()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    v_objetivo varchar(30);
    v_id_proyecto integer;
    v_tipo text;
    v_destino_existe boolean;
BEGIN
    SELECT tipo_objetivo, id_proyecto INTO v_objetivo, v_id_proyecto
      FROM importacion_archivo
     WHERE id_importacion = NEW.id_importacion AND activo;
    IF v_objetivo IS NULL THEN
        RAISE EXCEPTION 'La importación padre no existe o está inactiva';
    END IF;

    IF (SELECT version_pipeline FROM importacion_archivo WHERE id_importacion=NEW.id_importacion) <> 'legacy-v1' THEN
        IF NEW.geometria_trabajo IS NOT NULL AND ST_SRID(NEW.geometria_trabajo)<>
           (SELECT srid_trabajo FROM importacion_archivo WHERE id_importacion=NEW.id_importacion) THEN
            RAISE EXCEPTION 'CRS de staging distinto del CRS de importacion';
        END IF;
        IF NEW.registro_destino_id IS NOT NULL AND v_objetivo IN('nucleo_agrario','nucleo_agrario_gpkg','parcela','parcela_gpkg')
           AND NOT EXISTS(SELECT 1 FROM importacion_feature_candidato c
             WHERE c.id_importacion_feature=NEW.id_importacion_feature AND c.estado='confirmado'
             AND CASE WHEN c.id_parcela IS NULL THEN c.id_proyecto_nucleo ELSE c.id_parcela END=NEW.registro_destino_id) THEN
            RAISE EXCEPTION 'Destino sin candidato confirmado';
        END IF;
        IF NEW.geometria_normalizada IS NOT NULL AND GeometryType(NEW.geometria_normalizada)<>'MULTIPOLYGON' THEN
            RAISE EXCEPTION 'Contrato poligonal de conciliacion';
        END IF;
        IF NEW.estado='confirmado' AND (NEW.registro_destino_id IS NULL
           OR NEW.geometria_normalizada IS NULL OR NEW.geometria_trabajo IS NULL
           OR jsonb_array_length(NEW.errores)>0
           OR (jsonb_array_length(NEW.advertencias)>0 AND NOT NEW.advertencias_aceptadas)) THEN
            RAISE EXCEPTION 'Feature confirmada sin geometria o decision valida';
        END IF;
        IF v_objetivo IN('nucleo_agrario','nucleo_agrario_gpkg','parcela','parcela_gpkg') THEN
            RETURN NEW;
        END IF;
    END IF;

    IF NEW.geometria_normalizada IS NOT NULL THEN
        v_tipo := GeometryType(NEW.geometria_normalizada);
        IF (v_objetivo = 'trazo_proyecto' AND v_tipo <> 'MULTILINESTRING')
           OR (v_objetivo IN ('nucleo_agrario', 'parcela',
                             'derecho_via_proyecto', 'nucleo_agrario_gpkg',
                             'parcela_gpkg') AND v_tipo <> 'MULTIPOLYGON') THEN
            RAISE EXCEPTION 'Tipo geométrico % inválido para objetivo %',
                v_tipo, v_objetivo;
        END IF;
    END IF;

    IF NEW.registro_destino_id IS NOT NULL THEN
        IF v_objetivo = 'trazo_proyecto' THEN
            SELECT EXISTS (
                SELECT 1 FROM trazo_proyecto
                 WHERE id_trazo = NEW.registro_destino_id
            ) INTO v_destino_existe;
        ELSIF v_objetivo = 'nucleo_agrario' THEN
            SELECT EXISTS (
                SELECT 1 FROM nucleo_agrario
                 WHERE id_nucleo = NEW.registro_destino_id
            ) INTO v_destino_existe;
        ELSIF v_objetivo = 'nucleo_agrario_gpkg' THEN
            SELECT EXISTS (
                SELECT 1 FROM nucleo_agrario n
                JOIN proyecto_nucleo pn ON pn.id_nucleo = n.id_nucleo
                 WHERE n.id_nucleo = NEW.registro_destino_id
                   AND n.activo AND pn.activo AND pn.id_proyecto = v_id_proyecto
                   AND lower(btrim(n.fuente_datos)) = 'ran_phina_catalogo_nucleos'
                   AND btrim(n.id_nucleo_fuente) = NEW.atributos_normalizados->>'cve_unica'
            ) INTO v_destino_existe;
        ELSIF v_objetivo = 'parcela_gpkg' THEN
            SELECT EXISTS (
                SELECT 1 FROM parcela p
                JOIN nucleo_agrario n ON n.id_nucleo = p.id_nucleo
                JOIN proyecto_nucleo pn ON pn.id_nucleo = n.id_nucleo
                 WHERE p.id_parcela = NEW.registro_destino_id
                   AND p.activo AND n.activo AND pn.activo
                   AND pn.id_proyecto = v_id_proyecto
                   AND lower(btrim(n.fuente_datos)) = 'ran_phina_catalogo_nucleos'
                   AND btrim(n.id_nucleo_fuente) =
                       NEW.atributos_normalizados->>'cve_unica_nucleo'
                   AND p.id_nucleo =
                       (NEW.atributos_normalizados->>'id_nucleo')::integer
            ) INTO v_destino_existe;
        ELSIF v_objetivo = 'parcela' THEN
            SELECT EXISTS (
                SELECT 1 FROM parcela
                 WHERE id_parcela = NEW.registro_destino_id
            ) INTO v_destino_existe;
        ELSE
            SELECT EXISTS (
                SELECT 1 FROM derecho_via_proyecto
                 WHERE id_derecho_via = NEW.registro_destino_id
                   AND id_proyecto = v_id_proyecto
            ) INTO v_destino_existe;
        END IF;
        IF NOT v_destino_existe THEN
            RAISE EXCEPTION
                'El registro destino confirmado no existe para el objetivo %',
                v_objetivo;
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER trg_importacion_feature_objetivo ON importacion_feature;
CREATE TRIGGER trg_importacion_feature_objetivo BEFORE INSERT OR UPDATE ON importacion_feature FOR EACH ROW EXECUTE FUNCTION fn_validar_importacion_feature_objetivo();

CREATE FUNCTION fn_gis_feature_confirmada_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN
 IF OLD.estado='confirmado' AND to_jsonb(NEW) IS DISTINCT FROM to_jsonb(OLD) THEN
  RAISE EXCEPTION 'Feature GIS confirmada inmutable; utilizar nueva importacion';
 END IF;
 RETURN NEW;
 END $$;
CREATE TRIGGER trg_gis_feature_confirmada_inmutable BEFORE UPDATE ON importacion_feature
 FOR EACH ROW EXECUTE FUNCTION fn_gis_feature_confirmada_inmutable();
