-- Historia técnica GIS. No produce eventos ni cambios administrativos.
SET search_path = public, pg_catalog;
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM schema_migrations WHERE version='025' AND nombre='conciliacion_gis_proyecto'
 AND checksum_sha256='8338aace95845761acf0f9b675064ca25a6b0da2117013178ed060f260ec372a') THEN
  RAISE EXCEPTION '026 requiere 025 canónica exacta';
 END IF;
 IF EXISTS(SELECT 1 FROM schema_migrations WHERE version='026') THEN RAISE EXCEPTION '026 ya registrada'; END IF;
END $$;
SELECT pg_advisory_xact_lock(hashtextextended('software-pa:026:historia-cambios-gis',0));

ALTER TABLE importacion_archivo
 ADD COLUMN alcance_entrega varchar(10) NOT NULL DEFAULT 'parcial' CHECK(alcance_entrega IN('completa','parcial')),
 ADD COLUMN id_importacion_anterior bigint REFERENCES importacion_archivo;
COMMENT ON COLUMN importacion_archivo.alcance_entrega IS
 'Histórico desconocido se conserva como parcial. Completa significa todo el proyecto/objetivo, nunca se infiere del conteo.';
CREATE FUNCTION fn_gis_entrega_contexto() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE anterior importacion_archivo%ROWTYPE;
 BEGIN
 IF TG_OP='UPDATE' AND (NEW.alcance_entrega<>OLD.alcance_entrega OR
  NEW.id_importacion_anterior IS DISTINCT FROM OLD.id_importacion_anterior)
 THEN RAISE EXCEPTION 'Alcance y procedencia de entrega inmutables'; END IF;
 IF NEW.id_importacion_anterior IS NOT NULL THEN
  SELECT * INTO anterior FROM importacion_archivo WHERE id_importacion=NEW.id_importacion_anterior;
  IF anterior.id_proyecto<>NEW.id_proyecto OR anterior.id_importacion>=NEW.id_importacion OR NOT (
   anterior.tipo_objetivo=NEW.tipo_objetivo OR
   (anterior.tipo_objetivo IN('nucleo_agrario','nucleo_agrario_gpkg') AND NEW.tipo_objetivo IN('nucleo_agrario','nucleo_agrario_gpkg')) OR
   (anterior.tipo_objetivo IN('parcela','parcela_gpkg') AND NEW.tipo_objetivo IN('parcela','parcela_gpkg')))
  THEN RAISE EXCEPTION 'Entrega anterior no comparable del mismo proyecto/objetivo'; END IF;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_gis_entrega_contexto BEFORE INSERT OR UPDATE ON importacion_archivo
 FOR EACH ROW EXECUTE FUNCTION fn_gis_entrega_contexto();

CREATE TABLE importacion_conciliacion_ciclo (
 id_ciclo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_importacion bigint NOT NULL REFERENCES importacion_archivo,
 numero_ciclo integer NOT NULL CHECK(numero_ciclo>0),
 tipo_ciclo varchar(20) NOT NULL CHECK(tipo_ciclo IN('historico','inicial','reconciliacion')),
 motivo varchar(250) NOT NULL CHECK(NULLIF(btrim(motivo),'') IS NOT NULL),
 estado varchar(20) NOT NULL DEFAULT 'abierto' CHECK(estado IN('abierto','finalizado')),
 fecha_inicio timestamptz NOT NULL DEFAULT now(), fecha_fin timestamptz,
 id_usuario integer NOT NULL REFERENCES usuario,
 version_algoritmo varchar(40) NOT NULL,
 universo_destinos jsonb NOT NULL CHECK(jsonb_typeof(universo_destinos)='array'),
 resumen jsonb NOT NULL DEFAULT '{}',
 clave_solicitud uuid,
 creado_en timestamptz NOT NULL DEFAULT now(),
 UNIQUE(id_importacion,numero_ciclo), UNIQUE(id_ciclo,id_importacion),
 UNIQUE(id_importacion,clave_solicitud),
 CHECK((estado='abierto' AND fecha_fin IS NULL) OR (estado='finalizado' AND fecha_fin IS NOT NULL))
);
CREATE TABLE importacion_conciliacion_resultado (
 id_ciclo bigint NOT NULL REFERENCES importacion_conciliacion_ciclo,
 id_importacion_feature bigint NOT NULL REFERENCES importacion_feature,
 estado_matching varchar(30) NOT NULL CHECK(estado_matching IN
 ('pendiente','coincidencia_exacta','candidato','ambiguo','sin_coincidencia','confirmado','rechazado','ignorado')),
 creado_en timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(id_ciclo,id_importacion_feature)
);
ALTER TABLE importacion_feature_candidato ADD COLUMN id_ciclo bigint;
ALTER TABLE importacion_feature_decision ADD COLUMN id_ciclo bigint;

-- Backfill sólo agrega contexto: no cambia IDs, decisiones, fechas ni geometrías.
INSERT INTO importacion_conciliacion_ciclo
 (id_importacion,numero_ciclo,tipo_ciclo,motivo,estado,fecha_inicio,fecha_fin,id_usuario,
 version_algoritmo,universo_destinos,resumen,creado_en)
 SELECT i.id_importacion,1,'historico','Historia conservada de 025',
 CASE WHEN i.estado='completo' THEN 'finalizado' ELSE 'abierto' END,
 COALESCE(i.fecha_procesamiento_inicio,i.fecha_carga),
 CASE WHEN i.estado='completo' THEN COALESCE(i.fecha_confirmacion,i.fecha_procesamiento_fin,i.fecha_carga) END,
 i.id_usuario_carga,i.version_pipeline,'[]',
 jsonb_build_object('universo_historico_no_reconstruible',true,'reporte_025',i.reporte),i.fecha_carga
 FROM importacion_archivo i WHERE i.version_pipeline<>'legacy-v1'
 AND i.tipo_objetivo IN('nucleo_agrario','nucleo_agrario_gpkg','parcela','parcela_gpkg');
INSERT INTO importacion_conciliacion_resultado(id_ciclo,id_importacion_feature,estado_matching,creado_en)
 SELECT c.id_ciclo,f.id_importacion_feature,f.estado_conciliacion,f.fecha_procesamiento
 FROM importacion_feature f JOIN importacion_conciliacion_ciclo c USING(id_importacion);
-- Guardas suspendidas únicamente dentro de la transacción DDL del backfill;
-- se restablecen antes de que el runner pueda hacer COMMIT.
ALTER TABLE importacion_feature_candidato DISABLE TRIGGER trg_gis_candidato_ambito;
ALTER TABLE importacion_feature_candidato DISABLE TRIGGER trg_audit_importacion_feature_candidato;
ALTER TABLE importacion_feature_decision DISABLE TRIGGER trg_gis_decision_inmutable;
ALTER TABLE importacion_feature_decision DISABLE TRIGGER trg_audit_importacion_feature_decision;
UPDATE importacion_feature_candidato x SET id_ciclo=c.id_ciclo
 FROM importacion_conciliacion_ciclo c WHERE c.id_importacion=x.id_importacion;
UPDATE importacion_feature_decision d SET id_ciclo=c.id_ciclo
 FROM importacion_feature f JOIN importacion_conciliacion_ciclo c USING(id_importacion)
 WHERE f.id_importacion_feature=d.id_importacion_feature;
ALTER TABLE importacion_feature_candidato ENABLE TRIGGER trg_gis_candidato_ambito;
ALTER TABLE importacion_feature_candidato ENABLE TRIGGER trg_audit_importacion_feature_candidato;
ALTER TABLE importacion_feature_decision ENABLE TRIGGER trg_gis_decision_inmutable;
ALTER TABLE importacion_feature_decision ENABLE TRIGGER trg_audit_importacion_feature_decision;
ALTER TABLE importacion_feature_candidato
 ALTER COLUMN id_ciclo SET NOT NULL,
 ADD CONSTRAINT fk_candidato_ciclo_importacion FOREIGN KEY(id_ciclo,id_importacion)
 REFERENCES importacion_conciliacion_ciclo(id_ciclo,id_importacion),
 ADD CONSTRAINT fk_candidato_resultado FOREIGN KEY(id_ciclo,id_importacion_feature)
 REFERENCES importacion_conciliacion_resultado,
 ADD CONSTRAINT uq_candidato_ciclo_feature UNIQUE(id_candidato,id_ciclo,id_importacion_feature);
ALTER TABLE importacion_feature_decision
 ALTER COLUMN id_ciclo SET NOT NULL,
 ADD CONSTRAINT fk_decision_resultado FOREIGN KEY(id_ciclo,id_importacion_feature)
 REFERENCES importacion_conciliacion_resultado,
 ADD CONSTRAINT fk_decision_candidato_ciclo FOREIGN KEY(id_candidato,id_ciclo,id_importacion_feature)
 REFERENCES importacion_feature_candidato(id_candidato,id_ciclo,id_importacion_feature);
DROP INDEX uq_candidato_destino;
CREATE UNIQUE INDEX uq_candidato_destino ON importacion_feature_candidato
 (id_ciclo,id_importacion_feature,id_proyecto_nucleo,COALESCE(id_parcela,0));
DROP INDEX uq_candidato_seleccion_feature;
CREATE UNIQUE INDEX uq_candidato_seleccion_feature ON importacion_feature_candidato
 (id_ciclo,id_importacion_feature) WHERE estado IN('seleccionado','confirmado');
CREATE UNIQUE INDEX uq_candidato_confirmacion_feature ON importacion_feature_candidato
 (id_importacion_feature) WHERE estado='confirmado';
DROP INDEX uq_candidato_seleccion_nucleo;
CREATE UNIQUE INDEX uq_candidato_seleccion_nucleo ON importacion_feature_candidato
 (id_importacion,id_ciclo,id_proyecto_nucleo) WHERE id_parcela IS NULL AND estado IN('seleccionado','confirmado');
DROP INDEX uq_candidato_seleccion_parcela;
CREATE UNIQUE INDEX uq_candidato_seleccion_parcela ON importacion_feature_candidato
 (id_importacion,id_ciclo,id_proyecto_nucleo,id_parcela) WHERE id_parcela IS NOT NULL AND estado IN('seleccionado','confirmado');
CREATE UNIQUE INDEX uq_candidato_confirmacion_nucleo ON importacion_feature_candidato
 (id_importacion,id_proyecto_nucleo) WHERE id_parcela IS NULL AND estado='confirmado';
CREATE UNIQUE INDEX uq_candidato_confirmacion_parcela ON importacion_feature_candidato
 (id_importacion,id_proyecto_nucleo,id_parcela) WHERE id_parcela IS NOT NULL AND estado='confirmado';
CREATE INDEX idx_decision_ciclo ON importacion_feature_decision(id_ciclo,id_importacion_feature,id_decision);

CREATE FUNCTION fn_gis_ciclo_historia() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Ciclo GIS histórico no eliminable'; END IF;
 IF TG_OP='UPDATE' AND (OLD.estado='finalizado' OR
  (to_jsonb(NEW)-ARRAY['estado','fecha_fin','resumen']) IS DISTINCT FROM
  (to_jsonb(OLD)-ARRAY['estado','fecha_fin','resumen']))
 THEN RAISE EXCEPTION 'Identidad e historia del ciclo GIS inmutables'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_gis_ciclo_historia BEFORE UPDATE OR DELETE ON importacion_conciliacion_ciclo
 FOR EACH ROW EXECUTE FUNCTION fn_gis_ciclo_historia();
CREATE TRIGGER trg_audit_importacion_conciliacion_ciclo AFTER INSERT OR UPDATE ON importacion_conciliacion_ciclo
 FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_ciclo');

-- Sólo pueden cerrarse vigencias o registrarse bajas explícitas; el payload de
-- una versión confirmada nunca se reescribe.
CREATE FUNCTION fn_gis_version_payload_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN
 IF (to_jsonb(NEW)-ARRAY['es_vigente','activo','actualizado_en','actualizado_por','fecha_baja','id_usuario_baja','motivo_baja','observaciones'])
 IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['es_vigente','activo','actualizado_en','actualizado_por','fecha_baja','id_usuario_baja','motivo_baja','observaciones'])
 THEN RAISE EXCEPTION 'Payload de versión GIS inmutable'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_nucleo_version_payload BEFORE UPDATE ON proyecto_nucleo_geometria
 FOR EACH ROW EXECUTE FUNCTION fn_gis_version_payload_inmutable();
CREATE TRIGGER trg_parcela_version_payload BEFORE UPDATE ON proyecto_parcela_geometria
 FOR EACH ROW EXECUTE FUNCTION fn_gis_version_payload_inmutable();
CREATE TRIGGER trg_ddv_version_payload BEFORE UPDATE ON derecho_via_proyecto
 FOR EACH ROW EXECUTE FUNCTION fn_gis_version_payload_inmutable();

CREATE FUNCTION fn_gis_ciclo_contexto() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE v_import bigint;
 BEGIN
 SELECT id_importacion INTO v_import FROM importacion_conciliacion_ciclo WHERE id_ciclo=NEW.id_ciclo;
 IF NOT EXISTS(SELECT 1 FROM importacion_feature WHERE id_importacion_feature=NEW.id_importacion_feature AND id_importacion=v_import)
 THEN RAISE EXCEPTION 'Resultado fuera de la importación del ciclo'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_gis_resultado_contexto BEFORE INSERT ON importacion_conciliacion_resultado
 FOR EACH ROW EXECUTE FUNCTION fn_gis_ciclo_contexto();
CREATE TRIGGER trg_gis_resultado_inmutable BEFORE UPDATE OR DELETE ON importacion_conciliacion_resultado
 FOR EACH ROW EXECUTE FUNCTION fn_gis_decision_inmutable();

CREATE FUNCTION fn_gis_candidato_ciclo() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN
 IF TG_OP='INSERT' AND NEW.id_ciclo IS NULL THEN
  SELECT r.id_ciclo INTO NEW.id_ciclo FROM importacion_conciliacion_resultado r
  JOIN importacion_conciliacion_ciclo c USING(id_ciclo)
  WHERE r.id_importacion_feature=NEW.id_importacion_feature ORDER BY c.numero_ciclo DESC LIMIT 1;
 END IF;
 IF TG_OP='UPDATE' AND (NEW.id_ciclo<>OLD.id_ciclo OR NOT EXISTS(
  SELECT 1 FROM importacion_conciliacion_resultado r JOIN importacion_conciliacion_ciclo c USING(id_ciclo)
  WHERE r.id_importacion_feature=OLD.id_importacion_feature AND c.numero_ciclo=(
   SELECT max(c2.numero_ciclo) FROM importacion_conciliacion_resultado r2
   JOIN importacion_conciliacion_ciclo c2 USING(id_ciclo) WHERE r2.id_importacion_feature=OLD.id_importacion_feature)
  AND r.id_ciclo=OLD.id_ciclo)) THEN RAISE EXCEPTION 'Candidato histórico inmutable'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_gis_candidato_ciclo BEFORE INSERT OR UPDATE ON importacion_feature_candidato
 FOR EACH ROW EXECUTE FUNCTION fn_gis_candidato_ciclo();
CREATE FUNCTION fn_gis_decision_ciclo() RETURNS trigger LANGUAGE plpgsql AS $$
 BEGIN
 IF NEW.id_ciclo IS NULL THEN
  SELECT r.id_ciclo INTO NEW.id_ciclo FROM importacion_conciliacion_resultado r
  JOIN importacion_conciliacion_ciclo c USING(id_ciclo)
  WHERE r.id_importacion_feature=NEW.id_importacion_feature ORDER BY c.numero_ciclo DESC LIMIT 1;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_gis_decision_ciclo BEFORE INSERT ON importacion_feature_decision
 FOR EACH ROW EXECUTE FUNCTION fn_gis_decision_ciclo();

CREATE TABLE revision_cambio_gis (
 id_revision bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 clave_comparacion char(64) NOT NULL UNIQUE,
 id_proyecto integer NOT NULL REFERENCES proyecto,
 objetivo varchar(10) NOT NULL CHECK(objetivo IN('ddv','nucleo','parcela')),
 id_proyecto_nucleo integer REFERENCES proyecto_nucleo,
 id_parcela integer REFERENCES parcela,
 id_feature_nueva bigint REFERENCES importacion_feature,
 id_importacion_anterior bigint REFERENCES importacion_archivo,
 id_importacion_nueva bigint NOT NULL REFERENCES importacion_archivo,
 id_nucleo_geometria_anterior bigint REFERENCES proyecto_nucleo_geometria,
 id_nucleo_geometria_nueva bigint REFERENCES proyecto_nucleo_geometria,
 id_parcela_geometria_anterior bigint REFERENCES proyecto_parcela_geometria,
 id_parcela_geometria_nueva bigint REFERENCES proyecto_parcela_geometria,
 id_ddv_anterior integer REFERENCES derecho_via_proyecto,
 id_ddv_nueva integer REFERENCES derecho_via_proyecto,
 tipo_cambio varchar(40) NOT NULL CHECK(tipo_cambio IN('geometria_modificada','aparece_en_nueva_version',
 'desaparece_en_nueva_version','cambio_relacion_ddv')),
 subtipo_cambio varchar(40) CHECK(subtipo_cambio IN('antes_intersectaba_ahora_no',
 'antes_no_intersectaba_ahora_si','intersecta_en_ambas_con_cambio')),
 srid_medicion integer REFERENCES spatial_ref_sys(srid),
 area_anterior_m2 double precision CHECK(area_anterior_m2>=0),
 area_nueva_m2 double precision CHECK(area_nueva_m2>=0),
 area_diferencia_m2 double precision CHECK(area_diferencia_m2>=0),
 porcentaje_diferencia double precision CHECK(porcentaje_diferencia>=0),
 metricas jsonb NOT NULL DEFAULT '{}',
 creado_en timestamptz NOT NULL DEFAULT now(), creado_por integer NOT NULL REFERENCES usuario,
 CHECK((tipo_cambio='cambio_relacion_ddv')=(subtipo_cambio IS NOT NULL)),
 CHECK(id_parcela IS NULL OR (objetivo='parcela' AND id_proyecto_nucleo IS NOT NULL)),
 CHECK(objetivo='nucleo' OR (id_nucleo_geometria_anterior IS NULL AND id_nucleo_geometria_nueva IS NULL)),
 CHECK(objetivo='parcela' OR (id_parcela_geometria_anterior IS NULL AND id_parcela_geometria_nueva IS NULL)),
 CHECK(tipo_cambio<>'cambio_relacion_ddv' OR (id_ddv_anterior IS NOT NULL AND id_ddv_nueva IS NOT NULL
 AND id_proyecto_nucleo IS NOT NULL AND objetivo IN('nucleo','parcela'))),
 CHECK(tipo_cambio<>'aparece_en_nueva_version' OR id_feature_nueva IS NOT NULL),
 CHECK(tipo_cambio<>'geometria_modificada' OR
  (objetivo='ddv' AND id_ddv_anterior IS NOT NULL AND id_ddv_nueva IS NOT NULL AND id_ddv_anterior<>id_ddv_nueva) OR
  (objetivo='nucleo' AND id_nucleo_geometria_anterior IS NOT NULL AND id_nucleo_geometria_nueva IS NOT NULL
   AND id_nucleo_geometria_anterior<>id_nucleo_geometria_nueva) OR
  (objetivo='parcela' AND id_parcela_geometria_anterior IS NOT NULL AND id_parcela_geometria_nueva IS NOT NULL
   AND id_parcela_geometria_anterior<>id_parcela_geometria_nueva)),
 CHECK(tipo_cambio<>'desaparece_en_nueva_version' OR
  (objetivo='nucleo' AND id_nucleo_geometria_anterior IS NOT NULL AND id_nucleo_geometria_nueva IS NULL) OR
  (objetivo='parcela' AND id_parcela_geometria_anterior IS NOT NULL AND id_parcela_geometria_nueva IS NULL)),
 CHECK((srid_medicion IS NULL AND area_anterior_m2 IS NULL AND area_nueva_m2 IS NULL
  AND area_diferencia_m2 IS NULL AND porcentaje_diferencia IS NULL) OR
  (srid_medicion IS NOT NULL AND area_anterior_m2 IS NOT NULL AND area_nueva_m2 IS NOT NULL AND area_diferencia_m2 IS NOT NULL)),
 CHECK(jsonb_typeof(metricas)='object')
);
CREATE INDEX idx_revision_proyecto ON revision_cambio_gis(id_proyecto,creado_en,id_revision);
CREATE INDEX idx_revision_entidad ON revision_cambio_gis(id_proyecto_nucleo,id_parcela,tipo_cambio);
CREATE TABLE revision_cambio_gis_decision (
 id_decision bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 id_revision bigint NOT NULL REFERENCES revision_cambio_gis,
 accion varchar(20) NOT NULL CHECK(accion IN('revisado','no_aplica','aplicado')),
 motivo varchar(250) NOT NULL CHECK(NULLIF(btrim(motivo),'') IS NOT NULL),
 clave_solicitud uuid NOT NULL,
 id_seguimiento_evento bigint REFERENCES seguimiento_evento,
 creado_por integer NOT NULL REFERENCES usuario, creado_en timestamptz NOT NULL DEFAULT now(),
 UNIQUE(id_revision,clave_solicitud),
 CHECK(id_seguimiento_evento IS NULL OR accion='aplicado')
);
COMMENT ON TABLE revision_cambio_gis IS 'Observación técnica inmutable. Nunca modifica superficies ni estados administrativos.';
COMMENT ON TABLE revision_cambio_gis_decision IS 'APLICADO documenta decisión humana; sólo referencia eventos ya existentes.';
CREATE INDEX idx_revision_decision ON revision_cambio_gis_decision(id_revision,id_decision DESC);
CREATE VIEW vw_revision_cambio_gis_estado AS
 SELECT r.*,COALESCE(d.accion,'pendiente') AS estado_revision FROM revision_cambio_gis r
 LEFT JOIN LATERAL(SELECT accion FROM revision_cambio_gis_decision WHERE id_revision=r.id_revision
 ORDER BY id_decision DESC LIMIT 1) d ON true;

CREATE FUNCTION fn_gis_revision_contexto() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE v_pn integer; v_parcela integer; v_proyecto integer; v_id bigint; v_tabla text;
 BEGIN
 IF NOT EXISTS(SELECT 1 FROM importacion_archivo WHERE id_importacion=NEW.id_importacion_nueva AND id_proyecto=NEW.id_proyecto)
 OR (NEW.id_importacion_anterior IS NOT NULL AND NOT EXISTS(SELECT 1 FROM importacion_archivo
 WHERE id_importacion=NEW.id_importacion_anterior AND id_proyecto=NEW.id_proyecto))
 THEN RAISE EXCEPTION 'Revisión con importaciones de otro proyecto'; END IF;
 IF NEW.id_proyecto_nucleo IS NOT NULL AND NOT EXISTS(SELECT 1 FROM proyecto_nucleo
 WHERE id_proyecto_nucleo=NEW.id_proyecto_nucleo AND id_proyecto=NEW.id_proyecto)
 THEN RAISE EXCEPTION 'Revisión con destino de otro proyecto'; END IF;
 IF NEW.id_feature_nueva IS NOT NULL AND NOT EXISTS(SELECT 1 FROM importacion_feature
 WHERE id_importacion_feature=NEW.id_feature_nueva AND id_importacion=NEW.id_importacion_nueva)
 THEN RAISE EXCEPTION 'Feature de otra entrega'; END IF;
 FOR v_tabla,v_id IN SELECT * FROM (VALUES
 ('proyecto_nucleo_geometria',NEW.id_nucleo_geometria_anterior),('proyecto_nucleo_geometria',NEW.id_nucleo_geometria_nueva),
 ('proyecto_parcela_geometria',NEW.id_parcela_geometria_anterior),('proyecto_parcela_geometria',NEW.id_parcela_geometria_nueva)) x LOOP
  IF v_id IS NOT NULL THEN
   EXECUTE format('SELECT id_proyecto_nucleo,(to_jsonb(g)->>''id_parcela'')::integer FROM %I g WHERE id_geometria=$1',v_tabla)
    INTO v_pn,v_parcela USING v_id;
   IF v_pn IS DISTINCT FROM NEW.id_proyecto_nucleo OR v_parcela IS DISTINCT FROM NEW.id_parcela
   THEN RAISE EXCEPTION 'Versión geométrica de otra entidad'; END IF;
  END IF;
 END LOOP;
 IF EXISTS(SELECT 1 FROM derecho_via_proyecto WHERE id_derecho_via IN(NEW.id_ddv_anterior,NEW.id_ddv_nueva)
 AND id_proyecto<>NEW.id_proyecto) THEN RAISE EXCEPTION 'DDV de otro proyecto'; END IF;
 IF NEW.id_parcela IS NOT NULL AND NOT EXISTS(SELECT 1 FROM parcela p JOIN proyecto_nucleo pn USING(id_nucleo)
  WHERE p.id_parcela=NEW.id_parcela AND pn.id_proyecto_nucleo=NEW.id_proyecto_nucleo)
 THEN RAISE EXCEPTION 'Parcela de otro núcleo'; END IF;
 IF NEW.tipo_cambio='geometria_modificada' AND NEW.objetivo IN('nucleo','parcela') THEN
  v_tabla:=CASE WHEN NEW.objetivo='nucleo' THEN 'proyecto_nucleo_geometria' ELSE 'proyecto_parcela_geometria' END;
  EXECUTE format('SELECT f.id_importacion FROM %I g JOIN importacion_feature f USING(id_importacion_feature) WHERE g.id_geometria=$1',v_tabla)
   INTO v_id USING COALESCE(NEW.id_nucleo_geometria_anterior,NEW.id_parcela_geometria_anterior);
  IF v_id IS DISTINCT FROM NEW.id_importacion_anterior THEN RAISE EXCEPTION 'Importación anterior distinta de la versión'; END IF;
  EXECUTE format('SELECT f.id_importacion FROM %I g JOIN importacion_feature f USING(id_importacion_feature) WHERE g.id_geometria=$1',v_tabla)
   INTO v_id USING COALESCE(NEW.id_nucleo_geometria_nueva,NEW.id_parcela_geometria_nueva);
  IF v_id<>NEW.id_importacion_nueva THEN RAISE EXCEPTION 'Importación nueva distinta de la versión'; END IF;
 END IF;
 IF NEW.tipo_cambio='desaparece_en_nueva_version' AND NOT EXISTS(
  SELECT 1 FROM importacion_archivo a JOIN importacion_archivo b ON b.id_importacion=NEW.id_importacion_nueva
  WHERE a.id_importacion=NEW.id_importacion_anterior AND a.alcance_entrega='completa' AND b.alcance_entrega='completa'
  AND a.estado='completo' AND b.estado='completo' AND a.id_proyecto=b.id_proyecto AND a.srid_trabajo=b.srid_trabajo)
 THEN RAISE EXCEPTION 'Desaparición requiere entregas completas finalizadas'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_gis_revision_contexto BEFORE INSERT ON revision_cambio_gis
 FOR EACH ROW EXECUTE FUNCTION fn_gis_revision_contexto();
CREATE FUNCTION fn_gis_revision_decision_contexto() RETURNS trigger LANGUAGE plpgsql AS $$
 DECLARE r revision_cambio_gis%ROWTYPE; e seguimiento_evento%ROWTYPE; v_actor integer;
 BEGIN
 v_actor:=NULLIF(current_setting('app.current_user_id',true),'')::integer;
 IF NEW.creado_por IS DISTINCT FROM v_actor OR NOT EXISTS(SELECT 1 FROM usuario WHERE id_usuario=v_actor AND activo AND rol IN('admin','geografo'))
 THEN RAISE EXCEPTION 'Decisión GIS requiere admin o geografo'; END IF;
 -- SELECT FOR UPDATE requiere privilegio UPDATE incluso si sólo se quiere
 -- bloquear. Usar lock transaccional de revisión conserva permisos append-only.
 PERFORM pg_advisory_xact_lock(hashtextextended('software-pa:revision-gis:'||NEW.id_revision,0));
 SELECT * INTO r FROM revision_cambio_gis WHERE id_revision=NEW.id_revision;
 IF NOT EXISTS(SELECT 1 FROM proyecto p JOIN usuario u ON u.id_usuario=v_actor
  WHERE p.id_proyecto=r.id_proyecto AND p.activo AND u.activo
  AND (u.rol='admin' OR EXISTS(SELECT 1 FROM usuario_proyecto up
   WHERE up.id_usuario=v_actor AND up.id_proyecto=p.id_proyecto AND up.activo)))
 THEN RAISE EXCEPTION 'Proyecto fuera del alcance autorizado de la decisión GIS'; END IF;
 IF NEW.id_seguimiento_evento IS NOT NULL THEN
  SELECT * INTO e FROM seguimiento_evento WHERE id_seguimiento_evento=NEW.id_seguimiento_evento AND activo FOR SHARE;
  IF e.id_seguimiento_evento IS NULL OR NOT EXISTS(SELECT 1 FROM proyecto_nucleo WHERE id_proyecto_nucleo=e.id_proyecto_nucleo AND id_proyecto=r.id_proyecto)
  OR (r.id_proyecto_nucleo IS NOT NULL AND e.id_proyecto_nucleo<>r.id_proyecto_nucleo)
  OR (e.entidad_tipo IS NOT NULL AND NOT (
    (e.entidad_tipo='proyecto_nucleo' AND e.entidad_id=r.id_proyecto_nucleo)
    OR (e.entidad_tipo='parcela' AND e.entidad_id=r.id_parcela)))
  THEN RAISE EXCEPTION 'Evento incompatible con la revisión'; END IF;
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER trg_gis_revision_decision_contexto BEFORE INSERT ON revision_cambio_gis_decision
 FOR EACH ROW EXECUTE FUNCTION fn_gis_revision_decision_contexto();
DO $$ DECLARE t text; pk text; BEGIN
 FOREACH t IN ARRAY ARRAY['revision_cambio_gis','revision_cambio_gis_decision'] LOOP
  pk:=CASE WHEN t='revision_cambio_gis' THEN 'id_revision' ELSE 'id_decision' END;
  EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION fn_gis_decision_inmutable()','trg_inmutable_'||t,t);
  EXECUTE format('CREATE TRIGGER %I AFTER INSERT ON %I FOR EACH ROW EXECUTE FUNCTION fn_audit_log(%L)','trg_audit_'||t,t,pk);
  EXECUTE format('GRANT SELECT,INSERT ON %I TO software_pa_app',t);
 END LOOP;
END $$;
GRANT SELECT,INSERT ON importacion_conciliacion_resultado TO software_pa_app;
GRANT SELECT,INSERT,UPDATE ON importacion_conciliacion_ciclo TO software_pa_app;
GRANT SELECT ON vw_revision_cambio_gis_estado TO software_pa_app;
-- ALTER DEFAULT PRIVILEGES del bootstrap concede UPDATE a tablas nuevas;
-- las entidades append-only lo revocan expresamente además de sus triggers.
REVOKE UPDATE,DELETE,TRUNCATE ON revision_cambio_gis,revision_cambio_gis_decision,
 importacion_conciliacion_resultado FROM software_pa_app;
REVOKE DELETE,TRUNCATE ON importacion_conciliacion_ciclo FROM software_pa_app;
GRANT USAGE,SELECT ON SEQUENCE importacion_conciliacion_ciclo_id_ciclo_seq,
 revision_cambio_gis_id_revision_seq,revision_cambio_gis_decision_id_decision_seq TO software_pa_app;
