-- B-03: expansión compatible; no clasifica ni actualiza documentos existentes.
SET search_path = public, pg_catalog;
SELECT pg_advisory_xact_lock(hashtextextended('software-pa:028:catalogo-tipo-documento', 0));

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM schema_migrations WHERE version = '027'
          AND nombre = 'actividad_campo_objetivo_documental'
          AND checksum_sha256 = 'd5371660b3d0f6a257bcdffe453feb72984b225d24804991e6b4cf7c1ce68665'
    ) THEN RAISE EXCEPTION '028 requiere 027 canónica exacta'; END IF;
    IF EXISTS (SELECT 1 FROM schema_migrations WHERE version = '028') THEN
        RAISE EXCEPTION '028 ya se encuentra registrada';
    END IF;
    IF to_regclass('public.catalogo_tipo_documento') IS NOT NULL OR EXISTS (
        SELECT 1 FROM information_schema.columns WHERE table_schema = 'public'
        AND table_name = 'documento' AND column_name = 'id_tipo_documento'
    ) THEN RAISE EXCEPTION '028 encontró una expansión previa no registrada'; END IF;
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns WHERE table_schema = 'public'
        AND table_name = 'documento' AND column_name = 'tipo_documento'
        AND data_type = 'character varying' AND character_maximum_length = 80
        AND is_nullable = 'NO'
    ) THEN RAISE EXCEPTION 'Documento no corresponde al contrato legado 027'; END IF;
END $$;

LOCK TABLE documento IN SHARE ROW EXCLUSIVE MODE;
SELECT set_config('app.migration_028_document_count', count(*)::text, true),
       set_config('app.migration_028_document_hash',
           md5(COALESCE(string_agg(to_jsonb(d)::text, '|' ORDER BY id_documento), '')), true)
FROM documento d;

CREATE TABLE catalogo_tipo_documento (
    id_tipo_documento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo varchar(80) NOT NULL,
    nombre varchar(250) NOT NULL,
    descripcion text,
    orden integer NOT NULL DEFAULT 0,
    activo boolean NOT NULL DEFAULT true,
    creado_en timestamptz NOT NULL DEFAULT now(),
    creado_por integer REFERENCES usuario(id_usuario),
    actualizado_en timestamptz,
    actualizado_por integer REFERENCES usuario(id_usuario),
    fecha_baja timestamptz,
    id_usuario_baja integer REFERENCES usuario(id_usuario),
    motivo_baja text,
    observaciones text,
    CONSTRAINT uq_catalogo_tipo_documento_codigo UNIQUE (codigo),
    CONSTRAINT chk_catalogo_tipo_documento_codigo CHECK (codigo ~ '^[A-Z][A-Z0-9_]*$'),
    CONSTRAINT chk_catalogo_tipo_documento_nombre CHECK (NULLIF(btrim(nombre), '') IS NOT NULL),
    CONSTRAINT chk_catalogo_tipo_documento_orden CHECK (orden >= 0),
    CONSTRAINT chk_catalogo_tipo_documento_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);

-- Semilla de esquema antes de instalar la auditoría de la tabla nueva.
INSERT INTO catalogo_tipo_documento (codigo, nombre, descripcion, orden) VALUES
    ('MINUTA', 'Minuta', 'Registro escrito de reunión o actividad.', 10),
    ('FOTOGRAFIA', 'Fotografía', 'Evidencia fotográfica; la actividad respaldada se identifica en el contexto.', 20),
    ('ACTA_ASAMBLEA', 'Acta de asamblea', 'Acta de acuerdos de asamblea, salvo los tipos específicos del catálogo.', 30),
    ('PADRON', 'Padrón de ejidatarios/comuneros', 'Documento que identifica integrantes del núcleo; no equivale a cualquier lista de personas.', 40),
    ('ACTA_ELECCION_ORV', 'Acta de elección de ORV', 'Acta que documenta la elección de órganos de representación y vigilancia.', 50),
    ('ACTA_REMOCION_ORV', 'Acta de remoción de ORV', 'Acta de remoción, distinta del acto de elección.', 60),
    ('ACTA_NO_VERIFICATIVO', 'Acta de no verificativo', 'Acta que acredita que una asamblea no se verificó.', 70),
    ('ACTA_COMPLEMENTARIA', 'Acta complementaria', 'Documento complementario de un acto previo, identificado en la descripción.', 80),
    ('ACTA_DELIMITACION_DESTINO_ASIGNACION', 'Acta de delimitación, destino y asignación de tierras', 'Acta específica sobre delimitación, destino y asignación de tierras.', 90),
    ('CONVOCATORIA_PRIMERA', 'Primera convocatoria', 'Documento de primera convocatoria de asamblea.', 100),
    ('CONVOCATORIA_SEGUNDA', 'Segunda convocatoria', 'Documento de segunda convocatoria de asamblea.', 110),
    ('CONVENIO', 'Convenio', 'Instrumento de convenio/COP; el subtipo jurídico pertenece a la entidad Convenio.', 120),
    ('ACUSE_RAN', 'Acuse de ingreso al RAN', 'Evidencia de recepción de un ingreso al RAN, distinta de la solicitud.', 130),
    ('SOLICITUD_RAN', 'Solicitud de ingreso al RAN', 'Documento de solicitud de ingreso o reingreso al Registro Agrario Nacional.', 140),
    ('AVISO_INSCRIPCION_RAN', 'Aviso de inscripción RAN', 'Aviso que comunica la inscripción de un instrumento.', 150),
    ('CONSTANCIA_INSCRIPCION_RAN', 'Constancia de inscripción RAN', 'Constancia acreditativa de inscripción, distinta del aviso cuando sea identificable.', 160),
    ('FOLIO_EJIDOS_COMUNIDADES', 'Documento de folio de ejidos/comunidades', 'Impresión o extracto del folio; un número aislado es metadato.', 170),
    ('CREDENCIAL_INE', 'Credencial INE', 'Identificación oficial INE.', 180),
    ('CREDENCIAL_RAN', 'Credencial RAN', 'Credencial expedida en contexto RAN, distinta de la identificación INE.', 190),
    ('CERTIFICADO_PARCELARIO', 'Certificado parcelario', 'Documento de acreditación parcelaria.', 200),
    ('CERTIFICADO_DERECHOS_AGRARIOS', 'Certificado de derechos agrarios', 'Medio de acreditación agraria distinto del certificado parcelario.', 210),
    ('CONSTANCIA_VIGENCIA_DERECHOS', 'Constancia de vigencia de derechos', 'Constancia que acredita la vigencia del derecho.', 220),
    ('OFICIO', 'Oficio', 'Comunicación formal identificada como oficio; emisor, destinatario y asunto son contexto.', 230),
    ('RESPUESTA', 'Respuesta documental', 'Respuesta cuyo soporte no se identifica como oficio u otro tipo más concreto.', 240),
    ('VALIDACION', 'Documento de validación', 'Documento que acredita una validación; no representa un estado de cumplimiento.', 250),
    ('AVALUO', 'Avalúo', 'Documento de valoración; monto y contexto permanecen separados.', 260),
    ('OTRO', 'Otro documento', 'Documento identificado no cubierto por los tipos anteriores; requiere descripción.', 999);

CREATE FUNCTION fn_catalogo_tipo_documento_codigo_inmutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.codigo IS DISTINCT FROM OLD.codigo THEN
        RAISE EXCEPTION 'El código documental es inmutable'
            USING ERRCODE = '23514', CONSTRAINT = 'catalogo_tipo_documento_codigo_inmutable';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER trg_catalogo_tipo_documento_codigo_inmutable
BEFORE UPDATE OF codigo ON catalogo_tipo_documento
FOR EACH ROW EXECUTE FUNCTION fn_catalogo_tipo_documento_codigo_inmutable();
CREATE TRIGGER trg_prevent_delete_catalogo_tipo_documento
BEFORE DELETE ON catalogo_tipo_documento
FOR EACH ROW EXECUTE FUNCTION fn_prevenir_delete_fisico();
CREATE TRIGGER trg_audit_catalogo_tipo_documento
AFTER INSERT OR UPDATE ON catalogo_tipo_documento
FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_tipo_documento');

ALTER TABLE documento ADD COLUMN id_tipo_documento bigint;
ALTER TABLE documento ADD CONSTRAINT fk_documento_tipo_documento
    FOREIGN KEY (id_tipo_documento) REFERENCES catalogo_tipo_documento(id_tipo_documento)
    ON DELETE RESTRICT;
CREATE INDEX idx_documento_tipo_catalogo ON documento (id_tipo_documento)
    WHERE id_tipo_documento IS NOT NULL;

CREATE FUNCTION fn_validar_clasificacion_documental() RETURNS trigger
LANGUAGE plpgsql SET search_path = public, pg_catalog AS $$
DECLARE
    v_codigo text;
    v_activo boolean;
    v_seleccion boolean;
BEGIN
    v_seleccion := TG_OP = 'INSERT';
    IF TG_OP = 'UPDATE' THEN
        v_seleccion := NEW.id_tipo_documento IS DISTINCT FROM OLD.id_tipo_documento;
        IF OLD.id_tipo_documento IS NOT NULL AND NEW.id_tipo_documento IS NULL THEN
            RAISE EXCEPTION 'No se permite eliminar una clasificación documental'
                USING ERRCODE = '23514', CONSTRAINT = 'documento_clasificacion_irrevocable';
        END IF;
        IF (OLD.id_tipo_documento IS NOT NULL OR NEW.id_tipo_documento IS NOT NULL)
           AND NEW.tipo_documento IS DISTINCT FROM OLD.tipo_documento THEN
            RAISE EXCEPTION 'El texto legado de un documento clasificado se conserva'
                USING ERRCODE = '23514', CONSTRAINT = 'documento_tipo_legado_protegido';
        END IF;
    END IF;
    IF NEW.id_tipo_documento IS NULL THEN RETURN NEW; END IF;

    -- FOR SHARE bloquea también UPDATE de activo, no sólo cambios de clave.
    SELECT codigo, activo INTO v_codigo, v_activo
    FROM catalogo_tipo_documento WHERE id_tipo_documento = NEW.id_tipo_documento
    FOR SHARE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Tipo documental inexistente'
            USING ERRCODE = '23503', CONSTRAINT = 'fk_documento_tipo_documento';
    END IF;
    IF v_seleccion AND NOT v_activo THEN
        RAISE EXCEPTION 'No se permite seleccionar un tipo documental inactivo'
            USING ERRCODE = '23514', CONSTRAINT = 'documento_tipo_catalogo_activo';
    END IF;
    IF v_codigo = 'OTRO' AND NULLIF(btrim(NEW.descripcion), '') IS NULL THEN
        RAISE EXCEPTION 'OTRO requiere descripción no vacía'
            USING ERRCODE = '23514', CONSTRAINT = 'documento_otro_descripcion';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER trg_validar_clasificacion_documental
BEFORE INSERT OR UPDATE OF id_tipo_documento, tipo_documento, descripcion ON documento
FOR EACH ROW EXECUTE FUNCTION fn_validar_clasificacion_documental();

COMMENT ON TABLE catalogo_tipo_documento IS
    'Taxonomía documental V1 derivada de Excel y requisitos; no contiene actividades ni estados.';
COMMENT ON COLUMN documento.id_tipo_documento IS
    'Clasificación autoritativa cuando no es NULL. NULL conserva documentos legados sin backfill.';
COMMENT ON COLUMN documento.tipo_documento IS
    'Texto de compatibilidad: nuevas capturas por catálogo guardan su nombre; históricos conservan el original.';
GRANT SELECT ON catalogo_tipo_documento TO software_pa_app;

DO $$
BEGIN
    IF (SELECT count(*) FROM catalogo_tipo_documento) <> 27
       OR EXISTS (SELECT 1 FROM catalogo_tipo_documento WHERE NOT activo)
       OR NOT EXISTS (SELECT 1 FROM catalogo_tipo_documento WHERE codigo = 'OTRO' AND orden = 999)
    THEN RAISE EXCEPTION '028 postcondición: semilla documental incompleta'; END IF;
    IF (SELECT count(*) FROM documento) <>
         current_setting('app.migration_028_document_count')::bigint
       OR EXISTS (SELECT 1 FROM documento WHERE id_tipo_documento IS NOT NULL)
       OR (SELECT md5(COALESCE(string_agg((to_jsonb(d) - 'id_tipo_documento')::text,
             '|' ORDER BY id_documento), '')) FROM documento d)
          IS DISTINCT FROM current_setting('app.migration_028_document_hash')
    THEN RAISE EXCEPTION '028 postcondición: se modificaron documentos históricos'; END IF;
END $$;

