-- Contracción GIS legacy y consolidación del importador geoespacial.
BEGIN;

SELECT pg_advisory_xact_lock(20260825, 32);

DO $preflight$
DECLARE
    v_environment TEXT := lower(current_setting('app.environment', TRUE));
    v_confirm TEXT := current_setting('app.allow_destructive_test_reset', TRUE);
    v_backup TEXT := current_setting('app.backup_verified', TRUE);
BEGIN
    IF v_environment IS NULL
       OR v_environment NOT IN ('development', 'test')
       OR current_database() !~* '(test|prueba|dev|local)'
       OR v_confirm IS DISTINCT FROM '1'
       OR v_backup IS DISTINCT FROM '1' THEN
        RAISE EXCEPTION '032 bloqueada: entorno, confirmación o respaldo no válidos';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '031') THEN
        RAISE EXCEPTION '032 requiere la migración 031';
    END IF;
    IF EXISTS (SELECT 1 FROM schema_migrations WHERE version = '032') THEN
        RAISE EXCEPTION 'La migración 032 ya fue aplicada';
    END IF;
END;
$preflight$;

-- Datos de staging y cartografía existentes son de prueba y no se backfillean.
DROP TABLE IF EXISTS importacion_feature CASCADE;
DROP TABLE IF EXISTS importacion_archivo CASCADE;
DROP TABLE IF EXISTS perfil_mapeo_importacion CASCADE;
DROP TABLE IF EXISTS catalogo_alias_territorial CASCADE;
DROP TABLE IF EXISTS carga_geoespacial_feature CASCADE;
DROP TABLE IF EXISTS carga_geoespacial CASCADE;
DROP TABLE IF EXISTS candidato_tramo_nucleo CASCADE;
DROP TABLE IF EXISTS seccion_derecho_via CASCADE;
DROP TABLE IF EXISTS usuario_tramo CASCADE;
DROP TABLE IF EXISTS franja_derecho_via CASCADE;
DROP TABLE IF EXISTS tramo CASCADE;

DO $drop_legacy_functions$
DECLARE
    v_signature TEXT;
BEGIN
    FOR v_signature IN
        SELECT p.oid::regprocedure::TEXT
        FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = 'public'
          AND (
              p.proname LIKE 'fn_c5_%'
              OR p.proname IN (
                  'fn_015_validar_baja_padre', 'fn_015_validar_geometria_padre',
                  'fn_015_validar_hijo_activo', 'fn_018_normalizar_nombre_nucleo',
                  'fn_020_validar_alias_territorial'
              )
          )
    LOOP
        EXECUTE format('DROP FUNCTION IF EXISTS %s CASCADE', v_signature);
    END LOOP;
END;
$drop_legacy_functions$;

CREATE TABLE trazo_proyecto (
    id_trazo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto INTEGER NOT NULL REFERENCES proyecto(id_proyecto),
    version INTEGER NOT NULL,
    geometria_linea geometry(MULTILINESTRING, 4326) NOT NULL,
    fuente VARCHAR(250) NOT NULL,
    fecha_fuente DATE,
    fecha_vigencia_inicio DATE NOT NULL,
    fecha_vigencia_fin DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT uq_trazo_proyecto_version UNIQUE (id_proyecto, version),
    CONSTRAINT chk_trazo_version CHECK (version > 0),
    CONSTRAINT chk_trazo_fuente CHECK (NULLIF(btrim(fuente), '') IS NOT NULL),
    CONSTRAINT chk_trazo_vigencia CHECK (fecha_vigencia_fin IS NULL OR fecha_vigencia_fin >= fecha_vigencia_inicio),
    CONSTRAINT chk_trazo_geometria CHECK (
        NOT ST_IsEmpty(geometria_linea)
        AND ST_IsValid(geometria_linea)
        AND ST_SRID(geometria_linea) = 4326
        AND GeometryType(geometria_linea) = 'MULTILINESTRING'
    ),
    CONSTRAINT chk_trazo_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_trazo_proyecto_activo ON trazo_proyecto (id_proyecto) WHERE activo;
CREATE INDEX idx_trazo_proyecto_geom ON trazo_proyecto USING gist (geometria_linea);

CREATE TABLE perfil_mapeo_importacion (
    id_perfil BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto INTEGER REFERENCES proyecto(id_proyecto),
    nombre VARCHAR(120) NOT NULL,
    fuente VARCHAR(250) NOT NULL,
    tipo_objetivo VARCHAR(30) NOT NULL,
    mapeo JSONB NOT NULL,
    opciones JSONB NOT NULL DEFAULT '{}'::JSONB,
    id_usuario_creacion INTEGER NOT NULL REFERENCES usuario(id_usuario),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_perfil_objetivo CHECK (tipo_objetivo IN ('trazo_proyecto', 'nucleo_agrario', 'parcela')),
    CONSTRAINT chk_perfil_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_perfil_nombre_activo
    ON perfil_mapeo_importacion (COALESCE(id_proyecto, 0), lower(nombre)) WHERE activo;

CREATE TABLE catalogo_alias_territorial (
    id_alias BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_entidad INTEGER NOT NULL REFERENCES entidad_federativa(id_entidad),
    alias_nombre VARCHAR(200),
    alias_normalizado VARCHAR(200) NOT NULL,
    alias_clave VARCHAR(120),
    id_municipio_destino INTEGER NOT NULL REFERENCES municipio(id_municipio),
    fuente VARCHAR(250) NOT NULL,
    fecha_vigencia_inicio DATE,
    fecha_vigencia_fin DATE,
    id_usuario_aprobador INTEGER NOT NULL REFERENCES usuario(id_usuario),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_alias_identidad CHECK (alias_nombre IS NOT NULL OR alias_clave IS NOT NULL),
    CONSTRAINT chk_alias_vigencia CHECK (fecha_vigencia_fin IS NULL OR fecha_vigencia_inicio IS NULL OR fecha_vigencia_fin >= fecha_vigencia_inicio),
    CONSTRAINT chk_alias_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_alias_territorial_activo
    ON catalogo_alias_territorial (id_entidad, alias_normalizado, COALESCE(alias_clave, '')) WHERE activo;

CREATE TABLE importacion_archivo (
    id_importacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto INTEGER NOT NULL REFERENCES proyecto(id_proyecto),
    tipo_objetivo VARCHAR(30) NOT NULL,
    nombre_original VARCHAR(255) NOT NULL,
    nombre_almacenado VARCHAR(255) NOT NULL,
    formato_detectado VARCHAR(20) NOT NULL,
    tamano_bytes BIGINT NOT NULL,
    sha256 CHAR(64) NOT NULL,
    fuente VARCHAR(250) NOT NULL,
    fecha_fuente DATE,
    crs_original TEXT,
    crs_destino VARCHAR(30) NOT NULL DEFAULT 'EPSG:4326',
    columnas_detectadas JSONB NOT NULL DEFAULT '[]'::JSONB,
    mapeo JSONB NOT NULL DEFAULT '{}'::JSONB,
    opciones_mapeo JSONB NOT NULL DEFAULT '{}'::JSONB,
    id_perfil BIGINT REFERENCES perfil_mapeo_importacion(id_perfil),
    estado VARCHAR(40) NOT NULL DEFAULT 'subido',
    total_features INTEGER NOT NULL DEFAULT 0,
    features_procesados INTEGER NOT NULL DEFAULT 0,
    validos INTEGER NOT NULL DEFAULT 0,
    advertencias INTEGER NOT NULL DEFAULT 0,
    errores INTEGER NOT NULL DEFAULT 0,
    importados INTEGER NOT NULL DEFAULT 0,
    descartados INTEGER NOT NULL DEFAULT 0,
    id_usuario_carga INTEGER NOT NULL REFERENCES usuario(id_usuario),
    fecha_carga TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_procesamiento_inicio TIMESTAMPTZ,
    fecha_procesamiento_fin TIMESTAMPTZ,
    confirmacion_explicita BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_confirmacion TIMESTAMPTZ,
    id_usuario_confirmacion INTEGER REFERENCES usuario(id_usuario),
    error_codigo VARCHAR(80),
    error_detalle TEXT,
    reporte JSONB NOT NULL DEFAULT '{}'::JSONB,
    version_control INTEGER NOT NULL DEFAULT 1,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_importacion_objetivo CHECK (tipo_objetivo IN ('trazo_proyecto', 'nucleo_agrario', 'parcela')),
    CONSTRAINT chk_importacion_formato CHECK (formato_detectado IN ('geojson', 'gpkg', 'shp', 'kml', 'zip')),
    CONSTRAINT chk_importacion_hash CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_importacion_tamano CHECK (tamano_bytes > 0),
    CONSTRAINT chk_importacion_estado CHECK (estado IN ('subido', 'mapeado', 'procesando', 'previsualizado', 'confirmando', 'completo', 'error', 'cancelado')),
    CONSTRAINT chk_importacion_contadores CHECK (
        total_features >= 0 AND features_procesados >= 0 AND validos >= 0
        AND advertencias >= 0 AND errores >= 0 AND importados >= 0 AND descartados >= 0
    ),
    CONSTRAINT chk_importacion_confirmacion CHECK (
        (NOT confirmacion_explicita AND fecha_confirmacion IS NULL AND id_usuario_confirmacion IS NULL)
        OR (confirmacion_explicita AND fecha_confirmacion IS NOT NULL AND id_usuario_confirmacion IS NOT NULL)
    ),
    CONSTRAINT chk_importacion_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_importacion_idempotente
    ON importacion_archivo (id_proyecto, tipo_objetivo, sha256) WHERE activo;
CREATE INDEX idx_importacion_estado ON importacion_archivo (id_proyecto, estado, fecha_carga DESC) WHERE activo;
CREATE INDEX idx_importacion_usuario ON importacion_archivo (id_usuario_carga, fecha_carga DESC) WHERE activo;

CREATE TABLE importacion_feature (
    id_importacion_feature BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_importacion BIGINT NOT NULL REFERENCES importacion_archivo(id_importacion),
    indice_feature INTEGER NOT NULL,
    capa_origen VARCHAR(200),
    id_externo VARCHAR(200),
    tipo_geometria VARCHAR(40),
    atributos_originales JSONB NOT NULL DEFAULT '{}'::JSONB,
    atributos_normalizados JSONB NOT NULL DEFAULT '{}'::JSONB,
    geometria_normalizada geometry(Geometry, 4326),
    estado VARCHAR(40) NOT NULL DEFAULT 'pendiente_revision',
    errores JSONB NOT NULL DEFAULT '[]'::JSONB,
    advertencias JSONB NOT NULL DEFAULT '[]'::JSONB,
    transformaciones JSONB NOT NULL DEFAULT '[]'::JSONB,
    advertencias_aceptadas BOOLEAN NOT NULL DEFAULT FALSE,
    id_usuario_revision INTEGER REFERENCES usuario(id_usuario),
    fecha_revision TIMESTAMPTZ,
    registro_destino_id INTEGER,
    fecha_procesamiento TIMESTAMPTZ NOT NULL DEFAULT now(),
    fecha_importacion TIMESTAMPTZ,
    CONSTRAINT uq_importacion_feature UNIQUE (id_importacion, indice_feature),
    CONSTRAINT chk_importacion_feature_indice CHECK (indice_feature >= 0),
    CONSTRAINT chk_importacion_feature_estado CHECK (estado IN ('pendiente_revision', 'valido', 'advertencia', 'error', 'confirmado', 'descartado')),
    CONSTRAINT chk_importacion_feature_geometria CHECK (
        geometria_normalizada IS NULL OR (
            NOT ST_IsEmpty(geometria_normalizada)
            AND ST_IsValid(geometria_normalizada)
            AND ST_SRID(geometria_normalizada) = 4326
        )
    )
);
CREATE INDEX idx_importacion_feature_estado ON importacion_feature (id_importacion, estado);
CREATE INDEX idx_importacion_feature_destino ON importacion_feature (registro_destino_id) WHERE registro_destino_id IS NOT NULL;
CREATE INDEX idx_importacion_feature_geom ON importacion_feature USING gist (geometria_normalizada);

CREATE OR REPLACE FUNCTION fn_validar_importacion_feature_objetivo()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_objetivo VARCHAR(30);
    v_tipo TEXT;
    v_destino_existe BOOLEAN;
BEGIN
    SELECT tipo_objetivo INTO v_objetivo
    FROM importacion_archivo WHERE id_importacion = NEW.id_importacion AND activo;
    IF v_objetivo IS NULL THEN
        RAISE EXCEPTION 'La importación padre no existe o está inactiva';
    END IF;

    IF NEW.geometria_normalizada IS NOT NULL THEN
        v_tipo := GeometryType(NEW.geometria_normalizada);
        IF (v_objetivo = 'trazo_proyecto' AND v_tipo <> 'MULTILINESTRING')
           OR (v_objetivo IN ('nucleo_agrario', 'parcela') AND v_tipo <> 'MULTIPOLYGON') THEN
            RAISE EXCEPTION 'Tipo geométrico % inválido para objetivo %', v_tipo, v_objetivo;
        END IF;
    END IF;

    IF NEW.registro_destino_id IS NOT NULL THEN
        IF v_objetivo = 'trazo_proyecto' THEN
            SELECT EXISTS (SELECT 1 FROM trazo_proyecto WHERE id_trazo = NEW.registro_destino_id) INTO v_destino_existe;
        ELSIF v_objetivo = 'nucleo_agrario' THEN
            SELECT EXISTS (SELECT 1 FROM nucleo_agrario WHERE id_nucleo = NEW.registro_destino_id) INTO v_destino_existe;
        ELSE
            SELECT EXISTS (SELECT 1 FROM parcela WHERE id_parcela = NEW.registro_destino_id) INTO v_destino_existe;
        END IF;
        IF NOT v_destino_existe THEN
            RAISE EXCEPTION 'El registro destino confirmado no existe para el objetivo %', v_objetivo;
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_importacion_feature_objetivo
    BEFORE INSERT OR UPDATE OF id_importacion, geometria_normalizada, registro_destino_id
    ON importacion_feature FOR EACH ROW EXECUTE FUNCTION fn_validar_importacion_feature_objetivo();

CREATE OR REPLACE FUNCTION fn_validar_alias_territorial_objetivo()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_entidad INTEGER;
BEGIN
    SELECT id_entidad INTO v_entidad FROM municipio WHERE id_municipio = NEW.id_municipio_destino AND activo;
    IF v_entidad IS NULL OR v_entidad <> NEW.id_entidad THEN
        RAISE EXCEPTION 'El municipio destino del alias no pertenece a la entidad indicada';
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_alias_territorial_objetivo
    BEFORE INSERT OR UPDATE OF id_entidad, id_municipio_destino ON catalogo_alias_territorial
    FOR EACH ROW EXECUTE FUNCTION fn_validar_alias_territorial_objetivo();

CREATE TRIGGER trg_audit_trazo_proyecto
    AFTER INSERT OR UPDATE ON trazo_proyecto
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_trazo');
CREATE TRIGGER trg_audit_perfil_mapeo_importacion
    AFTER INSERT OR UPDATE ON perfil_mapeo_importacion
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_perfil');
CREATE TRIGGER trg_audit_catalogo_alias_territorial
    AFTER INSERT OR UPDATE ON catalogo_alias_territorial
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_alias');
CREATE TRIGGER trg_audit_importacion_archivo
    AFTER INSERT OR UPDATE ON importacion_archivo
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_importacion');

GRANT SELECT, INSERT, UPDATE ON trazo_proyecto, perfil_mapeo_importacion,
    catalogo_alias_territorial, importacion_archivo, importacion_feature TO software_pa_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO software_pa_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON trazo_proyecto, perfil_mapeo_importacion,
    catalogo_alias_territorial, importacion_archivo, importacion_feature FROM software_pa_app;

INSERT INTO schema_migrations (version, descripcion)
VALUES ('032', 'Contracción GIS legacy, trazo por proyecto e importador consolidado');

COMMIT;
