-- 036_modelo_operativo_excel_colectivo.sql
-- Normalización integral del seguimiento colectivo vigente.
-- El modelo canónico queda en catálogos tipados, bienes, convocatorias,
-- eventos RAN/FIFONAFE, checklist documental e importación tabular.

BEGIN;

SELECT pg_advisory_xact_lock(20260831, 36);

DO $preflight$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '035') THEN
        RAISE EXCEPTION '036 requiere la migración 035';
    END IF;
    IF EXISTS (SELECT 1 FROM schema_migrations WHERE version = '036') THEN
        RAISE EXCEPTION 'La migración 036 ya fue aplicada';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM usuario WHERE activo) THEN
        RAISE EXCEPTION '036 requiere al menos un usuario activo para auditar el backfill';
    END IF;
END;
$preflight$;

-- Las tablas 031 ya tienen triggers de auditoría; el backfill se atribuye a
-- un usuario activo existente y no altera identidades ni credenciales.
SELECT set_config(
    'app.current_user_id',
    (SELECT min(id_usuario)::TEXT FROM usuario WHERE activo),
    TRUE
);

-- ---------------------------------------------------------------------------
-- Catálogos operativos. Es un registro de opciones tipadas, no una tabla EAV:
-- no almacena atributos arbitrarios de entidades y cada FK se valida por tipo.
-- ---------------------------------------------------------------------------

CREATE TABLE catalogo_operativo (
    id_catalogo_opcion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_catalogo VARCHAR(50) NOT NULL,
    codigo VARCHAR(80) NOT NULL,
    nombre VARCHAR(250) NOT NULL,
    descripcion TEXT,
    orden INTEGER NOT NULL DEFAULT 0,
    fuente VARCHAR(250),
    vigencia_inicio DATE,
    vigencia_fin DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT uq_catalogo_operativo_codigo UNIQUE (tipo_catalogo, codigo),
    CONSTRAINT chk_catalogo_operativo_tipo CHECK (NULLIF(btrim(tipo_catalogo), '') IS NOT NULL),
    CONSTRAINT chk_catalogo_operativo_codigo CHECK (codigo ~ '^[A-Za-z0-9][A-Za-z0-9_-]*$'),
    CONSTRAINT chk_catalogo_operativo_nombre CHECK (NULLIF(btrim(nombre), '') IS NOT NULL),
    CONSTRAINT chk_catalogo_operativo_vigencia CHECK (
        vigencia_fin IS NULL OR vigencia_inicio IS NULL OR vigencia_fin >= vigencia_inicio
    ),
    CONSTRAINT chk_catalogo_operativo_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE INDEX idx_catalogo_operativo_lista
    ON catalogo_operativo (tipo_catalogo, activo DESC, orden, nombre);

CREATE TABLE catalogo_operativo_alias (
    id_catalogo_alias BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_catalogo_opcion BIGINT NOT NULL REFERENCES catalogo_operativo(id_catalogo_opcion),
    alias VARCHAR(300) NOT NULL,
    alias_normalizado VARCHAR(300) NOT NULL,
    fuente VARCHAR(250),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT uq_catalogo_alias UNIQUE (id_catalogo_opcion, alias_normalizado),
    CONSTRAINT chk_catalogo_alias_valor CHECK (
        NULLIF(btrim(alias), '') IS NOT NULL AND NULLIF(btrim(alias_normalizado), '') IS NOT NULL
    ),
    CONSTRAINT chk_catalogo_alias_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE INDEX idx_catalogo_alias_busqueda
    ON catalogo_operativo_alias (alias_normalizado) WHERE activo;

CREATE OR REPLACE FUNCTION fn_036_catalogo_inmutable()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'Los catálogos no admiten DELETE físico; desactive la opción';
    END IF;
    IF NEW.tipo_catalogo IS DISTINCT FROM OLD.tipo_catalogo
       OR NEW.codigo IS DISTINCT FROM OLD.codigo THEN
        RAISE EXCEPTION 'El tipo y código estable de catálogo son inmutables';
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_catalogo_inmutable
    BEFORE UPDATE OR DELETE ON catalogo_operativo
    FOR EACH ROW EXECUTE FUNCTION fn_036_catalogo_inmutable();

CREATE OR REPLACE FUNCTION fn_036_catalogo_alias_no_delete()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
    RAISE EXCEPTION 'Los aliases de catálogo no admiten DELETE físico; desactive el alias';
END;
$fn$;
CREATE TRIGGER trg_036_catalogo_alias_no_delete
    BEFORE DELETE ON catalogo_operativo_alias
    FOR EACH ROW EXECUTE FUNCTION fn_036_catalogo_alias_no_delete();

CREATE OR REPLACE FUNCTION fn_036_opcion_catalogo_valida(
    p_id BIGINT, p_tipo TEXT, p_permitir_inactiva BOOLEAN DEFAULT TRUE
) RETURNS BOOLEAN LANGUAGE sql STABLE AS $fn$
    SELECT p_id IS NULL OR EXISTS (
        SELECT 1 FROM catalogo_operativo c
        WHERE c.id_catalogo_opcion = p_id
          AND c.tipo_catalogo = p_tipo
          AND (p_permitir_inactiva OR c.activo)
    );
$fn$;

INSERT INTO catalogo_operativo
    (tipo_catalogo, codigo, nombre, descripcion, orden, fuente)
VALUES
    ('tipo_tenencia','ejido','Ejido','Núcleo agrario constituido como ejido.',10,'Ley Agraria/RAN'),
    ('tipo_tenencia','comunidad','Comunidad','Núcleo agrario constituido como comunidad.',20,'Ley Agraria/RAN'),

    ('residencia','naucalpan','Naucalpan',NULL,10,'Excel colectivo 2026'),
    ('residencia','atlacomulco','Atlacomulco',NULL,20,'Excel colectivo 2026'),
    ('residencia','tula','Tula',NULL,30,'Excel colectivo 2026'),
    ('residencia','queretaro','Querétaro',NULL,40,'Excel colectivo 2026'),

    ('tipo_gestion','PARCELA','Parcela',NULL,10,'Excel colectivo 2026'),
    ('tipo_gestion','TUC','Tierras de Uso Común (TUC)',NULL,20,'Excel colectivo 2026'),

    ('tipo_cop_operativo','ORIGEN','ORIGEN','cop_original; secuencia 1.',10,'Excel colectivo 2026'),
    ('tipo_cop_operativo','ADICIONAL','ADICIONAL','superficie_adicional; secuencia 1.',20,'Excel colectivo 2026'),
    ('tipo_cop_operativo','2A_ADICIONAL','2A ADICIONAL','superficie_adicional; secuencia 2.',30,'Excel colectivo 2026'),
    ('tipo_cop_operativo','COMPLEMENTARIAS','COMPLEMENTARIAS','obras_complementarias; secuencia 1.',40,'Excel colectivo 2026'),

    ('destino_superficie','tuc','Tierras de Uso Común',NULL,10,'Excel colectivo/RAN'),
    ('destino_superficie','sin_asignar','Sin asignar',NULL,20,'Excel colectivo 2026'),
    ('destino_superficie','favor_nucleo','A favor del núcleo agrario',NULL,30,'Excel colectivo 2026'),
    ('destino_superficie','parcela_escolar','Parcela escolar',NULL,40,'Excel colectivo 2026'),
    ('destino_superficie','uaim','Unidad Agrícola Industrial de la Mujer (UAIM)',NULL,50,'Excel colectivo 2026'),
    ('destino_superficie','camino','Camino',NULL,60,'Excel colectivo 2026'),
    ('destino_superficie','canal','Canal de riego o dren',NULL,70,'Excel colectivo 2026'),
    ('destino_superficie','derecho_paso','Derecho de paso',NULL,80,'Excel colectivo 2026'),
    ('destino_superficie','servidumbre_paso','Servidumbre de paso',NULL,90,'Excel colectivo 2026'),
    ('destino_superficie','infraestructura','Infraestructura',NULL,100,'Excel colectivo 2026'),
    ('destino_superficie','asentamiento_humano','Asentamiento humano',NULL,110,'Excel colectivo/RAN'),
    ('destino_superficie','parcela_ejidal','Parcela ejidal',NULL,120,'Excel colectivo 2026'),
    ('destino_superficie','solar','Solar',NULL,130,'Excel colectivo 2026'),
    ('destino_superficie','otro','Otro',NULL,999,'Excel colectivo 2026'),

    ('estado_registral_orv','no_ingresada','No ingresada',NULL,10,'Modelo operativo'),
    ('estado_registral_orv','en_proceso','En proceso',NULL,20,'Excel colectivo 2026'),
    ('estado_registral_orv','prevenida','Prevenida',NULL,30,'Modelo registral RAN'),
    ('estado_registral_orv','inscrita','Inscrita',NULL,40,'Excel colectivo/RAN'),
    ('estado_registral_orv','otro','Otro',NULL,999,'Modelo operativo'),

    ('organo_orv','comisariado','Comisariado',NULL,10,'Ley Agraria'),
    ('organo_orv','consejo_vigilancia','Consejo de Vigilancia',NULL,20,'Ley Agraria'),
    ('cargo_orv','presidente','Presidente',NULL,10,'Ley Agraria'),
    ('cargo_orv','secretario','Secretario',NULL,20,'Ley Agraria'),
    ('cargo_orv','tesorero','Tesorero',NULL,30,'Ley Agraria'),
    ('cargo_orv','secretario_1','Secretario 1',NULL,40,'Fuente funcional'),
    ('cargo_orv','secretario_2','Secretario 2',NULL,50,'Fuente funcional'),
    ('calidad_integrante_orv','propietario','Propietario',NULL,10,'Ley Agraria'),
    ('calidad_integrante_orv','suplente','Suplente',NULL,20,'Ley Agraria'),

    ('tipo_asamblea','anuencia','Anuencia',NULL,10,'Excel colectivo/Reglamento MOPR'),
    ('tipo_asamblea','retiro_fondos','Retiro de fondos',NULL,20,'Excel colectivo/FIFONAFE'),
    ('tipo_asamblea','otra','Otra',NULL,999,'Modelo operativo'),
    ('contexto_asamblea','cop_original','COP original',NULL,10,'Excel colectivo 2026'),
    ('contexto_asamblea','modificatorio','Modificatorio',NULL,20,'Dominio vigente'),
    ('contexto_asamblea','superficie_adicional','Superficie adicional',NULL,30,'Dominio vigente'),
    ('contexto_asamblea','obras_complementarias','Obras complementarias',NULL,40,'Dominio vigente'),
    ('contexto_asamblea','retiro_fondos','Retiro de fondos',NULL,50,'Excel colectivo/FIFONAFE'),
    ('contexto_asamblea','otro','Otro',NULL,999,'Modelo operativo'),
    ('resultado_convocatoria','celebrada','Celebrada',NULL,10,'Excel colectivo 2026'),
    ('resultado_convocatoria','no_verificativo','No verificativo',NULL,20,'Excel colectivo/FIFONAFE'),
    ('resultado_convocatoria','cancelada','Cancelada',NULL,30,'Modelo operativo'),
    ('resultado_convocatoria','reprogramada','Reprogramada',NULL,40,'Excel colectivo 2026'),
    ('resultado_convocatoria','otro','Otro',NULL,999,'Modelo operativo'),

    ('tipo_evento_ran','ingreso','Ingreso',NULL,10,'RAN/Excel colectivo'),
    ('tipo_evento_ran','reingreso','Reingreso',NULL,20,'Modelo registral'),
    ('tipo_evento_ran','prevencion','Prevención',NULL,30,'Modelo registral'),
    ('tipo_evento_ran','subsanacion','Subsanación/corrección',NULL,40,'Modelo registral'),
    ('tipo_evento_ran','desistimiento','Desistimiento',NULL,50,'Modelo registral'),
    ('tipo_evento_ran','calificacion','Calificación',NULL,60,'RAN/Excel colectivo'),
    ('tipo_evento_ran','inscripcion','Inscripción',NULL,70,'RAN/Excel colectivo'),
    ('tipo_evento_ran','otro','Otro',NULL,999,'Modelo registral'),

    ('tipo_evento_fifonafe','oficio_fifonafe_dgaopr','Oficio FIFONAFE a DGAOPR/Representación',NULL,10,'Excel colectivo 2026'),
    ('tipo_evento_fifonafe','oficio_dgaopr_representacion','Oficio DGAOPR a Representación',NULL,20,'Excel colectivo 2026'),
    ('tipo_evento_fifonafe','respuesta_representacion_dgaopr','Respuesta Representación a DGAOPR',NULL,30,'Excel colectivo 2026'),
    ('tipo_evento_fifonafe','respuesta_dgaopr_fifonafe','Respuesta DGAOPR/Representación a FIFONAFE',NULL,40,'Excel colectivo 2026'),
    ('tipo_evento_fifonafe','otro','Otro',NULL,999,'Modelo operativo'),

    ('estado_requisito_documental','pendiente','Pendiente',NULL,10,'Modelo documental'),
    ('estado_requisito_documental','disponible','Disponible',NULL,20,'Excel colectivo 2026'),
    ('estado_requisito_documental','faltante','Faltante',NULL,30,'Excel colectivo 2026'),
    ('estado_requisito_documental','no_aplica','No aplica',NULL,40,'Modelo documental'),
    ('estado_requisito_documental','otro','Otro',NULL,999,'Modelo documental');

INSERT INTO catalogo_operativo_alias
    (id_catalogo_opcion, alias, alias_normalizado, fuente)
SELECT c.id_catalogo_opcion, v.alias, v.normalizado, 'Excel colectivo 2026'
FROM (VALUES
    ('destino_superficie','tuc','TIERRAS DE USO COMÚN','TIERRAS DE USO COMUN'),
    ('destino_superficie','parcela_escolar','PARCELA ESCOLAR','PARCELA ESCOLAR'),
    ('destino_superficie','uaim','UNIDAD AGRICOLA INDUSTRIAL DE LA MUJER','UNIDAD AGRICOLA INDUSTRIAL DE LA MUJER'),
    ('destino_superficie','camino','CAMINOS','CAMINOS'),
    ('destino_superficie','canal','CANAL','CANAL'),
    ('destino_superficie','canal','CANAL DE RIEGO Y DRENES','CANAL DE RIEGO Y DRENES'),
    ('destino_superficie','derecho_paso','DERECHO DE PASO','DERECHO DE PASO'),
    ('destino_superficie','servidumbre_paso','SERVIDUMBRE DE PASO','SERVIDUMBRE DE PASO'),
    ('destino_superficie','asentamiento_humano','ASENTAMIENTO HUMANO','ASENTAMIENTO HUMANO'),
    ('destino_superficie','parcela_ejidal','PARCELA EJIDAL','PARCELA EJIDAL'),
    ('destino_superficie','sin_asignar','SIN ASIGNAR','SIN ASIGNAR'),
    ('destino_superficie','favor_nucleo','A FAVOR DEL NÚCLEO AGRARIO','A FAVOR DEL NUCLEO AGRARIO'),
    ('tipo_cop_operativo','2A_ADICIONAL','2A ADICIONAL','2A ADICIONAL'),
    ('residencia','queretaro','QUERETARO','QUERETARO')
) AS v(tipo, codigo, alias, normalizado)
JOIN catalogo_operativo c ON c.tipo_catalogo = v.tipo AND c.codigo = v.codigo;

-- ---------------------------------------------------------------------------
-- Datos generales, tenencia, residencia, responsables, padrón y ORV.
-- ---------------------------------------------------------------------------

ALTER TABLE nucleo_agrario
    ADD COLUMN id_tipo_tenencia BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion);
UPDATE nucleo_agrario n
SET id_tipo_tenencia = c.id_catalogo_opcion
FROM catalogo_operativo c
WHERE c.tipo_catalogo = 'tipo_tenencia' AND c.codigo = n.tipo_nucleo;
ALTER TABLE nucleo_agrario ALTER COLUMN id_tipo_tenencia SET NOT NULL;
ALTER TABLE nucleo_agrario ALTER COLUMN comunidad_indigena DROP DEFAULT;
ALTER TABLE nucleo_agrario ALTER COLUMN comunidad_indigena DROP NOT NULL;
COMMENT ON COLUMN nucleo_agrario.tipo_nucleo IS
    'Compatibilidad derivada de id_tipo_tenencia; retiro previsto después de migrar consumidores (migración objetivo 038).';
COMMENT ON COLUMN nucleo_agrario.comunidad_indigena IS
    'Trivaluado: NULL=no capturado, TRUE=sí, FALSE=no. No se infiere de la tenencia.';

-- Las residencias preexistentes que no son una opción inicial se preservan.
INSERT INTO catalogo_operativo
    (tipo_catalogo, codigo, nombre, descripcion, orden, fuente)
SELECT 'residencia', 'legacy_' || substr(md5(btrim(pn.residencia)),1,16), btrim(pn.residencia),
       'Valor preservado durante el backfill 035→036.', 900, 'backfill_035'
FROM proyecto_nucleo pn
WHERE NULLIF(btrim(pn.residencia), '') IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM catalogo_operativo c
      WHERE c.tipo_catalogo = 'residencia'
        AND upper(translate(c.nombre,'ÁÉÍÓÚÜÑ','AEIOUUN')) =
            upper(translate(btrim(pn.residencia),'ÁÉÍÓÚÜÑ','AEIOUUN'))
  )
GROUP BY btrim(pn.residencia);

ALTER TABLE proyecto_nucleo
    ADD COLUMN id_residencia BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    ADD COLUMN total_cops_planeados INTEGER,
    ADD CONSTRAINT chk_proyecto_nucleo_total_cops CHECK (
        total_cops_planeados IS NULL OR total_cops_planeados >= 0
    );
UPDATE proyecto_nucleo pn
SET id_residencia = c.id_catalogo_opcion
FROM catalogo_operativo c
WHERE c.tipo_catalogo = 'residencia'
  AND NULLIF(btrim(pn.residencia), '') IS NOT NULL
  AND upper(translate(c.nombre,'ÁÉÍÓÚÜÑ','AEIOUUN')) =
      upper(translate(btrim(pn.residencia),'ÁÉÍÓÚÜÑ','AEIOUUN'));
COMMENT ON COLUMN proyecto_nucleo.residencia IS
    'Compatibilidad derivada de id_residencia; retiro previsto al concluir migración de frontend (objetivo 038).';
COMMENT ON COLUMN proyecto_nucleo.total_cops_planeados IS
    'Planeación explícita del Excel; no es COUNT de filas ni de convenios existentes.';

-- Clave funcional de actividad: las marcas X y trimestres no participan. Dos
-- filas Excel con el mismo expediente/tipo/contexto/fechas/responsable/resultado
-- representan un solo hecho.
CREATE UNIQUE INDEX uq_036_actividad_hecho
    ON actividad_campo (
        id_proyecto_nucleo,
        tipo_actividad,
        contexto_actividad,
        COALESCE(fecha_programada, DATE 'infinity'),
        COALESCE(fecha_realizada, DATE 'infinity'),
        COALESCE(lower(btrim(responsable)), ''),
        COALESCE(md5(resultado), '')
    ) WHERE activo;

CREATE TABLE proyecto_nucleo_responsable (
    id_responsable BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto_nucleo INTEGER NOT NULL REFERENCES proyecto_nucleo(id_proyecto_nucleo),
    nombre VARCHAR(300) NOT NULL,
    cargo VARCHAR(200),
    contacto VARCHAR(200),
    vigencia_inicio DATE,
    vigencia_fin DATE,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_responsable_nombre CHECK (NULLIF(btrim(nombre), '') IS NOT NULL),
    CONSTRAINT chk_responsable_vigencia CHECK (
        vigencia_fin IS NULL OR vigencia_inicio IS NULL OR vigencia_fin >= vigencia_inicio
    ),
    CONSTRAINT chk_responsable_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_responsable_principal
    ON proyecto_nucleo_responsable (id_proyecto_nucleo)
    WHERE activo AND es_principal;
CREATE INDEX idx_responsable_historial
    ON proyecto_nucleo_responsable (id_proyecto_nucleo, vigencia_inicio DESC);
INSERT INTO proyecto_nucleo_responsable
    (id_proyecto_nucleo, nombre, contacto, es_principal, creado_por, observaciones)
SELECT id_proyecto_nucleo, btrim(responsable_nombre), contacto, TRUE, creado_por,
       'Backfill de columnas de compatibilidad de proyecto_nucleo.'
FROM proyecto_nucleo
WHERE NULLIF(btrim(responsable_nombre), '') IS NOT NULL;
COMMENT ON COLUMN proyecto_nucleo.responsable_nombre IS
    'Compatibilidad: el historial canónico está en proyecto_nucleo_responsable.';
COMMENT ON COLUMN proyecto_nucleo.contacto IS
    'Compatibilidad: el historial canónico está en proyecto_nucleo_responsable.';

ALTER TABLE orv
    ADD COLUMN id_estado_registral BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion);
UPDATE orv o
SET id_estado_registral = c.id_catalogo_opcion
FROM catalogo_operativo c
WHERE c.tipo_catalogo = 'estado_registral_orv'
  AND c.codigo = CASE
      WHEN o.acta_eleccion_inscrita_ran IS TRUE THEN 'inscrita'
      WHEN upper(COALESCE(o.estatus_fuente,'')) LIKE '%PROCESO%' THEN 'en_proceso'
      WHEN o.acta_eleccion_inscrita_ran IS FALSE THEN 'no_ingresada'
      ELSE 'otro'
  END;
COMMENT ON COLUMN orv.acta_eleccion_inscrita_ran IS
    'Compatibilidad SI/NO; el estado canónico es id_estado_registral y puede expresar proceso o prevención.';

ALTER TABLE orv_integrante
    ALTER COLUMN cargo DROP NOT NULL,
    ADD COLUMN id_organo BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    ADD COLUMN id_cargo BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    ADD COLUMN id_calidad BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    ADD CONSTRAINT chk_orv_integrante_estructura CHECK (
        (id_organo IS NULL AND id_cargo IS NULL AND id_calidad IS NULL AND NULLIF(btrim(cargo), '') IS NOT NULL)
        OR (id_organo IS NOT NULL AND id_cargo IS NOT NULL AND id_calidad IS NOT NULL)
    );
COMMENT ON COLUMN orv_integrante.cargo IS
    'Texto legacy; las capturas normalizadas usan id_organo, id_cargo e id_calidad.';

ALTER TABLE padron_historial
    ADD COLUMN fuente VARCHAR(250),
    ADD COLUMN id_documento INTEGER REFERENCES documento(id_documento);
COMMENT ON COLUMN padron_historial.fecha_padron IS
    'Fecha de emisión del corte de padrón; una fila representa un solo corte.';

-- ---------------------------------------------------------------------------
-- Afectación y bien/unidad afectada. Se elimina la falsa equivalencia
-- colectivo = sin referencia de parcela.
-- ---------------------------------------------------------------------------

ALTER TABLE afectacion DROP CONSTRAINT chk_afectacion_ambito_parcela;
ALTER TABLE afectacion
    ADD CONSTRAINT chk_afectacion_ambito_parcela CHECK (
        tipo_afectacion = 'colectivo'
        OR (tipo_afectacion = 'individual' AND id_parcela IS NOT NULL)
    );

CREATE OR REPLACE FUNCTION fn_validar_afectacion_parcela_nucleo()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_nucleo_pn INTEGER;
    v_nucleo_parcela INTEGER;
BEGIN
    IF NEW.id_parcela IS NOT NULL AND NEW.activo THEN
        SELECT id_nucleo INTO v_nucleo_pn
        FROM proyecto_nucleo WHERE id_proyecto_nucleo = NEW.id_proyecto_nucleo AND activo;
        SELECT id_nucleo INTO v_nucleo_parcela
        FROM parcela WHERE id_parcela = NEW.id_parcela AND activo;
        IF v_nucleo_pn IS NULL OR v_nucleo_parcela IS NULL OR v_nucleo_pn <> v_nucleo_parcela THEN
            RAISE EXCEPTION 'La parcela de la afectación debe pertenecer al mismo núcleo';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;

CREATE TABLE bien_afectado (
    id_bien_afectado BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_afectacion INTEGER NOT NULL REFERENCES afectacion(id_afectacion),
    id_tipo_gestion BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_destino_superficie BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_tipo_cop_operativo BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_parcela INTEGER REFERENCES parcela(id_parcela),
    tipo_tierra VARCHAR(120),
    referencia_alfanumerica VARCHAR(150),
    titularidad VARCHAR(250),
    detalle TEXT,
    superficie_preliminar_ha NUMERIC(14,6),
    superficie_afectada_ha NUMERIC(14,6),
    superficie_valor_original VARCHAR(120),
    superficie_formato_origen VARCHAR(50),
    fuente VARCHAR(250),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_bien_referencia CHECK (
        id_destino_superficie IS NOT NULL OR id_tipo_gestion IS NOT NULL OR id_parcela IS NOT NULL
        OR NULLIF(btrim(tipo_tierra), '') IS NOT NULL
        OR NULLIF(btrim(referencia_alfanumerica), '') IS NOT NULL
    ),
    CONSTRAINT chk_bien_superficie CHECK (
        (superficie_preliminar_ha IS NULL OR superficie_preliminar_ha >= 0)
        AND (superficie_afectada_ha IS NULL OR superficie_afectada_ha >= 0)
    ),
    CONSTRAINT chk_bien_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE INDEX idx_bien_afectacion ON bien_afectado (id_afectacion) WHERE activo;
CREATE INDEX idx_bien_catalogos
    ON bien_afectado (id_tipo_gestion, id_destino_superficie, id_tipo_cop_operativo) WHERE activo;
CREATE INDEX idx_bien_parcela ON bien_afectado (id_parcela) WHERE activo;

INSERT INTO bien_afectado (
    id_afectacion, id_destino_superficie, id_parcela, referencia_alfanumerica,
    superficie_preliminar_ha, superficie_afectada_ha, fuente, creado_por, observaciones
)
SELECT a.id_afectacion, c.id_catalogo_opcion, a.id_parcela, a.no_parcela_solar,
       a.superficie_preliminar_ha, a.superficie_afectada_ha, 'backfill_035', a.creado_por,
       'Backfill de columnas legacy de afectacion; tipo_gestion no fue inferido desde el ámbito.'
FROM afectacion a
LEFT JOIN catalogo_operativo c
  ON c.tipo_catalogo = 'destino_superficie'
 AND c.codigo = CASE lower(COALESCE(a.destino_superficie,''))
     WHEN 'tierras_uso_comun' THEN 'tuc'
     WHEN 'tierras de uso común' THEN 'tuc'
     WHEN 'parcela_escolar' THEN 'parcela_escolar'
     WHEN 'parcela escolar' THEN 'parcela_escolar'
     WHEN 'sin_asignar' THEN 'sin_asignar'
     ELSE NULL END
WHERE a.id_parcela IS NOT NULL OR a.destino_superficie IS NOT NULL
   OR a.no_parcela_solar IS NOT NULL OR a.superficie_preliminar_ha IS NOT NULL
   OR a.superficie_afectada_ha IS NOT NULL;

COMMENT ON COLUMN afectacion.destino_superficie IS
    'Compatibilidad; el destino canónico está en bien_afectado.id_destino_superficie.';
COMMENT ON COLUMN afectacion.no_parcela_solar IS
    'Compatibilidad; la referencia canónica alfanumérica está en bien_afectado.';

-- ---------------------------------------------------------------------------
-- Asamblea repetible, convocatorias y separación tipo/contexto.
-- ---------------------------------------------------------------------------

ALTER TABLE asamblea
    ADD COLUMN id_tipo_asamblea BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    ADD COLUMN id_contexto_asamblea BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion);
UPDATE asamblea a
SET id_tipo_asamblea = c.id_catalogo_opcion
FROM catalogo_operativo c
WHERE c.tipo_catalogo = 'tipo_asamblea'
  AND c.codigo = CASE WHEN a.tipo_asamblea = 'retiro_fondos' THEN 'retiro_fondos'
                      WHEN a.tipo_asamblea = 'otra' THEN 'otra' ELSE 'anuencia' END;
UPDATE asamblea a
SET id_contexto_asamblea = c.id_catalogo_opcion
FROM catalogo_operativo c
WHERE c.tipo_catalogo = 'contexto_asamblea' AND c.codigo = a.contexto_proceso;
ALTER TABLE asamblea ALTER COLUMN id_tipo_asamblea SET NOT NULL;
ALTER TABLE asamblea DROP CONSTRAINT chk_asamblea_tipo;
ALTER TABLE asamblea DROP CONSTRAINT chk_asamblea_contexto_proceso;
COMMENT ON COLUMN asamblea.tipo_asamblea IS
    'Compatibilidad derivada de id_tipo_asamblea; sólo anuencia/retiro_fondos/otra.';
COMMENT ON COLUMN asamblea.contexto_proceso IS
    'Compatibilidad derivada de id_contexto_asamblea; no es el tipo de asamblea.';

CREATE TABLE asamblea_convocatoria (
    id_convocatoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_asamblea INTEGER NOT NULL REFERENCES asamblea(id_asamblea),
    ordinal INTEGER NOT NULL,
    fecha_expedicion DATE,
    fecha_programada DATE,
    fecha_realizacion DATE,
    id_resultado BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    observaciones_resultado TEXT,
    id_documento INTEGER REFERENCES documento(id_documento),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_convocatoria_ordinal CHECK (ordinal > 0),
    CONSTRAINT chk_convocatoria_fechas CHECK (
        fecha_programada IS NULL OR fecha_expedicion IS NULL OR fecha_programada >= fecha_expedicion
    ),
    CONSTRAINT chk_convocatoria_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_convocatoria_ordinal
    ON asamblea_convocatoria (id_asamblea, ordinal) WHERE activo;
CREATE INDEX idx_convocatoria_fechas
    ON asamblea_convocatoria (fecha_programada, fecha_realizacion) WHERE activo;

INSERT INTO asamblea_convocatoria
    (id_asamblea, ordinal, fecha_expedicion, fecha_programada, fecha_realizacion,
     id_resultado, creado_por, observaciones)
SELECT a.id_asamblea, 1, a.fecha_expedicion_primera, a.fecha_programada_primera,
       CASE WHEN a.fecha_programada_segunda IS NULL THEN a.fecha_realizada END,
       CASE WHEN a.fecha_realizada IS NOT NULL AND a.fecha_programada_segunda IS NULL
            THEN (SELECT id_catalogo_opcion FROM catalogo_operativo
                  WHERE tipo_catalogo='resultado_convocatoria' AND codigo='celebrada') END,
       a.creado_por, 'Backfill de convocatoria legacy 1.'
FROM asamblea a
WHERE a.fecha_expedicion_primera IS NOT NULL OR a.fecha_programada_primera IS NOT NULL
   OR (a.fecha_realizada IS NOT NULL AND a.fecha_programada_segunda IS NULL);
INSERT INTO asamblea_convocatoria
    (id_asamblea, ordinal, fecha_expedicion, fecha_programada, fecha_realizacion,
     id_resultado, creado_por, observaciones)
SELECT a.id_asamblea, 2, a.fecha_expedicion_segunda, a.fecha_programada_segunda,
       a.fecha_realizada,
       CASE WHEN a.fecha_realizada IS NOT NULL
            THEN (SELECT id_catalogo_opcion FROM catalogo_operativo
                  WHERE tipo_catalogo='resultado_convocatoria' AND codigo='celebrada') END,
       a.creado_por, 'Backfill de convocatoria legacy 2.'
FROM asamblea a
WHERE a.fecha_expedicion_segunda IS NOT NULL OR a.fecha_programada_segunda IS NOT NULL;

COMMENT ON COLUMN asamblea.fecha_expedicion_primera IS 'Compatibilidad derivada de asamblea_convocatoria ordinal 1; objetivo de retiro 038.';
COMMENT ON COLUMN asamblea.fecha_programada_primera IS 'Compatibilidad derivada de asamblea_convocatoria ordinal 1; objetivo de retiro 038.';
COMMENT ON COLUMN asamblea.fecha_expedicion_segunda IS 'Compatibilidad derivada de asamblea_convocatoria ordinal 2; objetivo de retiro 038.';
COMMENT ON COLUMN asamblea.fecha_programada_segunda IS 'Compatibilidad derivada de asamblea_convocatoria ordinal 2; objetivo de retiro 038.';

CREATE OR REPLACE FUNCTION fn_036_resumir_convocatorias_legacy()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE v_asamblea INTEGER := NEW.id_asamblea;
BEGIN
    UPDATE asamblea a SET
        fecha_expedicion_primera=(SELECT c.fecha_expedicion FROM asamblea_convocatoria c WHERE c.id_asamblea=v_asamblea AND c.ordinal=1 AND c.activo),
        fecha_programada_primera=(SELECT c.fecha_programada FROM asamblea_convocatoria c WHERE c.id_asamblea=v_asamblea AND c.ordinal=1 AND c.activo),
        fecha_expedicion_segunda=(SELECT c.fecha_expedicion FROM asamblea_convocatoria c WHERE c.id_asamblea=v_asamblea AND c.ordinal=2 AND c.activo),
        fecha_programada_segunda=(SELECT c.fecha_programada FROM asamblea_convocatoria c WHERE c.id_asamblea=v_asamblea AND c.ordinal=2 AND c.activo),
        fecha_realizada=(SELECT max(c.fecha_realizacion) FROM asamblea_convocatoria c WHERE c.id_asamblea=v_asamblea AND c.activo),
        actualizado_en=now(),
        actualizado_por=NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER
    WHERE a.id_asamblea=v_asamblea;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_convocatoria_resumen_legacy
    AFTER INSERT OR UPDATE OF fecha_expedicion,fecha_programada,fecha_realizacion,activo
    ON asamblea_convocatoria FOR EACH ROW EXECUTE FUNCTION fn_036_resumir_convocatorias_legacy();

-- ---------------------------------------------------------------------------
-- RAN: trámite con objetivo tipado y eventos 1:N. Las columnas legacy quedan
-- sólo como resumen de compatibilidad, no como fuente canónica.
-- ---------------------------------------------------------------------------

CREATE TABLE tramite_ran (
    id_tramite_ran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto_nucleo INTEGER NOT NULL REFERENCES proyecto_nucleo(id_proyecto_nucleo),
    id_asamblea INTEGER REFERENCES asamblea(id_asamblea),
    id_convenio INTEGER REFERENCES convenio(id_convenio),
    id_orv INTEGER REFERENCES orv(id_orv),
    fecha_programada_ingreso DATE,
    referencia_expediente VARCHAR(150),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_tramite_ran_objetivo CHECK (num_nonnulls(id_asamblea,id_convenio,id_orv) = 1),
    CONSTRAINT chk_tramite_ran_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_tramite_ran_asamblea ON tramite_ran (id_asamblea) WHERE activo AND id_asamblea IS NOT NULL;
CREATE UNIQUE INDEX uq_tramite_ran_convenio ON tramite_ran (id_convenio) WHERE activo AND id_convenio IS NOT NULL;
CREATE UNIQUE INDEX uq_tramite_ran_orv ON tramite_ran (id_orv) WHERE activo AND id_orv IS NOT NULL;
CREATE INDEX idx_tramite_ran_pn ON tramite_ran (id_proyecto_nucleo) WHERE activo;

CREATE TABLE tramite_ran_evento (
    id_evento_ran BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite_ran BIGINT NOT NULL REFERENCES tramite_ran(id_tramite_ran),
    ordinal INTEGER NOT NULL,
    id_tipo_evento BIGINT NOT NULL REFERENCES catalogo_operativo(id_catalogo_opcion),
    fecha_evento DATE,
    numero_solicitud VARCHAR(150),
    resultado VARCHAR(250),
    calificacion TEXT,
    folio_referencia VARCHAR(200),
    id_documento INTEGER REFERENCES documento(id_documento),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_evento_ran_ordinal CHECK (ordinal > 0),
    CONSTRAINT chk_evento_ran_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_evento_ran_ordinal
    ON tramite_ran_evento (id_tramite_ran, ordinal) WHERE activo;
CREATE INDEX idx_evento_ran_historial
    ON tramite_ran_evento (id_tramite_ran, fecha_evento, ordinal) WHERE activo;
CREATE INDEX idx_evento_ran_solicitud
    ON tramite_ran_evento (numero_solicitud) WHERE activo AND numero_solicitud IS NOT NULL;

-- Backfill de Asamblea.
INSERT INTO tramite_ran
    (id_proyecto_nucleo,id_asamblea,fecha_programada_ingreso,creado_por,observaciones)
SELECT id_proyecto_nucleo,id_asamblea,fecha_programada_ingreso_ran,creado_por,
       'Backfill de seguimiento RAN legacy de asamblea.'
FROM asamblea
WHERE fecha_programada_ingreso_ran IS NOT NULL OR fecha_ingreso_ran IS NOT NULL
   OR numero_solicitud_ran IS NOT NULL OR calificacion_registral_ran IS NOT NULL
   OR fecha_inscripcion_ran IS NOT NULL;
INSERT INTO tramite_ran_evento
    (id_tramite_ran,ordinal,id_tipo_evento,fecha_evento,numero_solicitud,creado_por,observaciones)
SELECT t.id_tramite_ran,1,c.id_catalogo_opcion,a.fecha_ingreso_ran,a.numero_solicitud_ran,a.creado_por,'Backfill ingreso legacy.'
FROM tramite_ran t JOIN asamblea a ON a.id_asamblea=t.id_asamblea
JOIN catalogo_operativo c ON c.tipo_catalogo='tipo_evento_ran' AND c.codigo='ingreso'
WHERE a.fecha_ingreso_ran IS NOT NULL OR a.numero_solicitud_ran IS NOT NULL;
INSERT INTO tramite_ran_evento
    (id_tramite_ran,ordinal,id_tipo_evento,fecha_evento,calificacion,creado_por,observaciones)
SELECT t.id_tramite_ran,1+COALESCE((SELECT max(e.ordinal) FROM tramite_ran_evento e WHERE e.id_tramite_ran=t.id_tramite_ran),0),
       c.id_catalogo_opcion,NULL,a.calificacion_registral_ran,a.creado_por,'Backfill calificación legacy.'
FROM tramite_ran t JOIN asamblea a ON a.id_asamblea=t.id_asamblea
JOIN catalogo_operativo c ON c.tipo_catalogo='tipo_evento_ran' AND c.codigo='calificacion'
WHERE a.calificacion_registral_ran IS NOT NULL;
INSERT INTO tramite_ran_evento
    (id_tramite_ran,ordinal,id_tipo_evento,fecha_evento,creado_por,observaciones)
SELECT t.id_tramite_ran,1+COALESCE((SELECT max(e.ordinal) FROM tramite_ran_evento e WHERE e.id_tramite_ran=t.id_tramite_ran),0),
       c.id_catalogo_opcion,a.fecha_inscripcion_ran,a.creado_por,'Backfill inscripción legacy.'
FROM tramite_ran t JOIN asamblea a ON a.id_asamblea=t.id_asamblea
JOIN catalogo_operativo c ON c.tipo_catalogo='tipo_evento_ran' AND c.codigo='inscripcion'
WHERE a.fecha_inscripcion_ran IS NOT NULL;

-- Backfill de Convenio.
INSERT INTO tramite_ran
    (id_proyecto_nucleo,id_convenio,fecha_programada_ingreso,creado_por,observaciones)
SELECT id_proyecto_nucleo,id_convenio,fecha_programada_ingreso_ran,creado_por,
       'Backfill de seguimiento RAN legacy de convenio.'
FROM convenio
WHERE fecha_programada_ingreso_ran IS NOT NULL OR ingreso_ran_fecha IS NOT NULL
   OR numero_solicitud_ingreso IS NOT NULL OR calificacion_registral IS NOT NULL
   OR fecha_inscripcion_ran IS NOT NULL;
INSERT INTO tramite_ran_evento
    (id_tramite_ran,ordinal,id_tipo_evento,fecha_evento,numero_solicitud,creado_por,observaciones)
SELECT t.id_tramite_ran,1,c.id_catalogo_opcion,v.ingreso_ran_fecha,v.numero_solicitud_ingreso,v.creado_por,'Backfill ingreso legacy.'
FROM tramite_ran t JOIN convenio v ON v.id_convenio=t.id_convenio
JOIN catalogo_operativo c ON c.tipo_catalogo='tipo_evento_ran' AND c.codigo='ingreso'
WHERE v.ingreso_ran_fecha IS NOT NULL OR v.numero_solicitud_ingreso IS NOT NULL;
INSERT INTO tramite_ran_evento
    (id_tramite_ran,ordinal,id_tipo_evento,calificacion,creado_por,observaciones)
SELECT t.id_tramite_ran,1+COALESCE((SELECT max(e.ordinal) FROM tramite_ran_evento e WHERE e.id_tramite_ran=t.id_tramite_ran),0),
       c.id_catalogo_opcion,v.calificacion_registral,v.creado_por,'Backfill calificación legacy.'
FROM tramite_ran t JOIN convenio v ON v.id_convenio=t.id_convenio
JOIN catalogo_operativo c ON c.tipo_catalogo='tipo_evento_ran' AND c.codigo='calificacion'
WHERE v.calificacion_registral IS NOT NULL;
INSERT INTO tramite_ran_evento
    (id_tramite_ran,ordinal,id_tipo_evento,fecha_evento,creado_por,observaciones)
SELECT t.id_tramite_ran,1+COALESCE((SELECT max(e.ordinal) FROM tramite_ran_evento e WHERE e.id_tramite_ran=t.id_tramite_ran),0),
       c.id_catalogo_opcion,v.fecha_inscripcion_ran,v.creado_por,'Backfill inscripción legacy.'
FROM tramite_ran t JOIN convenio v ON v.id_convenio=t.id_convenio
JOIN catalogo_operativo c ON c.tipo_catalogo='tipo_evento_ran' AND c.codigo='inscripcion'
WHERE v.fecha_inscripcion_ran IS NOT NULL;

-- ORV inscrito también es un objeto registral tipado. Se contextualiza con un
-- ProyectoNucleo activo del núcleo; no duplica el ORV.
INSERT INTO tramite_ran (id_proyecto_nucleo,id_orv,creado_por,observaciones)
SELECT pn.id_proyecto_nucleo,o.id_orv,o.creado_por,'Backfill registral ORV.'
FROM orv o
JOIN LATERAL (
    SELECT p.id_proyecto_nucleo FROM proyecto_nucleo p
    WHERE p.id_nucleo=o.id_nucleo AND p.activo
    ORDER BY p.id_proyecto_nucleo LIMIT 1
) pn ON TRUE
WHERE o.acta_eleccion_inscrita_ran IS NOT NULL OR o.fecha_inscripcion_acta_ran IS NOT NULL
   OR NULLIF(btrim(o.estatus_fuente),'') IS NOT NULL;
INSERT INTO tramite_ran_evento
    (id_tramite_ran,ordinal,id_tipo_evento,fecha_evento,resultado,creado_por,observaciones)
SELECT t.id_tramite_ran,1,c.id_catalogo_opcion,o.fecha_inscripcion_acta_ran,o.estatus_fuente,o.creado_por,'Backfill estado registral ORV.'
FROM tramite_ran t JOIN orv o ON o.id_orv=t.id_orv
JOIN catalogo_operativo c ON c.tipo_catalogo='tipo_evento_ran'
 AND c.codigo=CASE WHEN o.acta_eleccion_inscrita_ran IS TRUE THEN 'inscripcion' ELSE 'ingreso' END;

COMMENT ON COLUMN asamblea.fecha_ingreso_ran IS 'Resumen legacy derivado de tramite_ran_evento; canónico desde 036.';
COMMENT ON COLUMN asamblea.numero_solicitud_ran IS 'Resumen legacy derivado de tramite_ran_evento; canónico desde 036.';
COMMENT ON COLUMN asamblea.calificacion_registral_ran IS 'Resumen legacy derivado de tramite_ran_evento; canónico desde 036.';
COMMENT ON COLUMN asamblea.fecha_inscripcion_ran IS 'Resumen legacy derivado de tramite_ran_evento; canónico desde 036.';
COMMENT ON COLUMN convenio.ingreso_ran_fecha IS 'Resumen legacy derivado de tramite_ran_evento; canónico desde 036.';
COMMENT ON COLUMN convenio.numero_solicitud_ingreso IS 'Resumen legacy derivado de tramite_ran_evento; canónico desde 036.';
COMMENT ON COLUMN convenio.calificacion_registral IS 'Resumen legacy derivado de tramite_ran_evento; canónico desde 036.';
COMMENT ON COLUMN convenio.fecha_inscripcion_ran IS 'Resumen legacy derivado de tramite_ran_evento; canónico desde 036.';

CREATE OR REPLACE FUNCTION fn_036_resumir_ran_legacy()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE v_tramite tramite_ran%ROWTYPE;
BEGIN
    SELECT * INTO v_tramite FROM tramite_ran WHERE id_tramite_ran=NEW.id_tramite_ran;
    IF v_tramite.id_asamblea IS NOT NULL THEN
        UPDATE asamblea a SET
            fecha_ingreso_ran=(SELECT min(e.fecha_evento) FROM tramite_ran_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_ran=v_tramite.id_tramite_ran AND e.activo AND c.codigo IN ('ingreso','reingreso')),
            numero_solicitud_ran=(SELECT e.numero_solicitud FROM tramite_ran_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_ran=v_tramite.id_tramite_ran AND e.activo AND c.codigo IN ('ingreso','reingreso') AND e.numero_solicitud IS NOT NULL ORDER BY e.ordinal DESC LIMIT 1),
            calificacion_registral_ran=(SELECT e.calificacion FROM tramite_ran_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_ran=v_tramite.id_tramite_ran AND e.activo AND c.codigo='calificacion' ORDER BY e.ordinal DESC LIMIT 1),
            fecha_inscripcion_ran=(SELECT max(e.fecha_evento) FROM tramite_ran_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_ran=v_tramite.id_tramite_ran AND e.activo AND c.codigo='inscripcion'),
            actualizado_en=now(), actualizado_por=NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER
        WHERE a.id_asamblea=v_tramite.id_asamblea;
    ELSIF v_tramite.id_convenio IS NOT NULL THEN
        UPDATE convenio v SET
            ingreso_ran_fecha=(SELECT min(e.fecha_evento) FROM tramite_ran_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_ran=v_tramite.id_tramite_ran AND e.activo AND c.codigo IN ('ingreso','reingreso')),
            numero_solicitud_ingreso=(SELECT e.numero_solicitud FROM tramite_ran_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_ran=v_tramite.id_tramite_ran AND e.activo AND c.codigo IN ('ingreso','reingreso') AND e.numero_solicitud IS NOT NULL ORDER BY e.ordinal DESC LIMIT 1),
            calificacion_registral=(SELECT e.calificacion FROM tramite_ran_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_ran=v_tramite.id_tramite_ran AND e.activo AND c.codigo='calificacion' ORDER BY e.ordinal DESC LIMIT 1),
            fecha_inscripcion_ran=(SELECT max(e.fecha_evento) FROM tramite_ran_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_ran=v_tramite.id_tramite_ran AND e.activo AND c.codigo='inscripcion'),
            actualizado_en=now(), actualizado_por=NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER
        WHERE v.id_convenio=v_tramite.id_convenio;
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_evento_ran_resumen_legacy
    AFTER INSERT OR UPDATE OF id_tipo_evento,fecha_evento,numero_solicitud,calificacion,activo
    ON tramite_ran_evento FOR EACH ROW EXECUTE FUNCTION fn_036_resumir_ran_legacy();

-- ---------------------------------------------------------------------------
-- Convenios: mapeo operativo derivado sin crear "segunda_adicional".
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW vw_convenio_tipo_cop_operativo AS
SELECT v.id_convenio, v.id_proyecto_nucleo, v.ambito, v.tipo_convenio, v.consecutivo,
       CASE
           WHEN v.tipo_convenio='cop_original' AND v.consecutivo=1 THEN 'ORIGEN'
           WHEN v.tipo_convenio='superficie_adicional' AND v.consecutivo=1 THEN 'ADICIONAL'
           WHEN v.tipo_convenio='superficie_adicional' AND v.consecutivo=2 THEN '2A ADICIONAL'
           WHEN v.tipo_convenio='superficie_adicional' AND v.consecutivo>2 THEN v.consecutivo::TEXT || 'A ADICIONAL'
           WHEN v.tipo_convenio='obras_complementarias' THEN 'COMPLEMENTARIAS'
           ELSE NULL
       END AS tipo_cop_operativo
FROM convenio v;

-- ---------------------------------------------------------------------------
-- FIFONAFE: correspondencia 1:N; la N:M con afectación se conserva intacta.
-- ---------------------------------------------------------------------------

CREATE TABLE tramite_fifonafe_evento (
    id_evento_fifonafe BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tramite_fifonafe INTEGER NOT NULL REFERENCES tramite_fifonafe(id_tramite_fifonafe),
    ordinal INTEGER NOT NULL,
    id_tipo_evento BIGINT NOT NULL REFERENCES catalogo_operativo(id_catalogo_opcion),
    origen VARCHAR(200),
    destino VARCHAR(200),
    numero_oficio VARCHAR(150),
    fecha_oficio DATE,
    id_documento INTEGER REFERENCES documento(id_documento),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_evento_fifonafe_ordinal CHECK (ordinal > 0),
    CONSTRAINT chk_evento_fifonafe_dato CHECK (
        NULLIF(btrim(numero_oficio), '') IS NOT NULL OR fecha_oficio IS NOT NULL
        OR NULLIF(btrim(observaciones), '') IS NOT NULL
    ),
    CONSTRAINT chk_evento_fifonafe_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_evento_fifonafe_ordinal
    ON tramite_fifonafe_evento (id_tramite_fifonafe, ordinal) WHERE activo;
CREATE INDEX idx_evento_fifonafe_historial
    ON tramite_fifonafe_evento (id_tramite_fifonafe, fecha_oficio, ordinal) WHERE activo;

INSERT INTO tramite_fifonafe_evento
    (id_tramite_fifonafe,ordinal,id_tipo_evento,origen,destino,numero_oficio,fecha_oficio,creado_por,observaciones)
SELECT t.id_tramite_fifonafe,x.ordinal,c.id_catalogo_opcion,x.origen,x.destino,x.numero,x.fecha,t.creado_por,
       'Backfill de correspondencia FIFONAFE legacy.'
FROM tramite_fifonafe t
CROSS JOIN LATERAL (VALUES
    (1,'oficio_fifonafe_dgaopr','FIFONAFE','DGAOPR/Representación',t.no_oficio_fifonafe_a_dgaopr,t.fecha_oficio_fifonafe_a_dgaopr),
    (2,'oficio_dgaopr_representacion','DGAOPR','Representación',t.no_oficio_dgaopr_a_representacion,t.fecha_oficio_dgaopr_a_representacion),
    (3,'respuesta_representacion_dgaopr','Representación','DGAOPR',t.no_oficio_respuesta_representacion_a_dgaopr,t.fecha_oficio_respuesta_representacion_a_dgaopr),
    (4,'respuesta_dgaopr_fifonafe','DGAOPR/Representación','FIFONAFE',t.no_oficio_respuesta_dgaopr_a_fifonafe,t.fecha_oficio_respuesta_dgaopr_a_fifonafe)
) x(ordinal,codigo,origen,destino,numero,fecha)
JOIN catalogo_operativo c ON c.tipo_catalogo='tipo_evento_fifonafe' AND c.codigo=x.codigo
WHERE x.numero IS NOT NULL OR x.fecha IS NOT NULL;

COMMENT ON COLUMN tramite_fifonafe.no_oficio_fifonafe_a_dgaopr IS 'Compatibilidad; eventos canónicos en tramite_fifonafe_evento desde 036.';
COMMENT ON COLUMN tramite_fifonafe.no_oficio_dgaopr_a_representacion IS 'Compatibilidad; eventos canónicos en tramite_fifonafe_evento desde 036.';
COMMENT ON COLUMN tramite_fifonafe.no_oficio_respuesta_representacion_a_dgaopr IS 'Compatibilidad; eventos canónicos en tramite_fifonafe_evento desde 036.';
COMMENT ON COLUMN tramite_fifonafe.no_oficio_respuesta_dgaopr_a_fifonafe IS 'Compatibilidad; eventos canónicos en tramite_fifonafe_evento desde 036.';

CREATE OR REPLACE FUNCTION fn_036_resumir_fifonafe_legacy()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
    UPDATE tramite_fifonafe t SET
        no_oficio_fifonafe_a_dgaopr=(SELECT e.numero_oficio FROM tramite_fifonafe_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_fifonafe=NEW.id_tramite_fifonafe AND e.activo AND c.codigo='oficio_fifonafe_dgaopr' ORDER BY e.ordinal DESC LIMIT 1),
        fecha_oficio_fifonafe_a_dgaopr=(SELECT e.fecha_oficio FROM tramite_fifonafe_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_fifonafe=NEW.id_tramite_fifonafe AND e.activo AND c.codigo='oficio_fifonafe_dgaopr' ORDER BY e.ordinal DESC LIMIT 1),
        no_oficio_dgaopr_a_representacion=(SELECT e.numero_oficio FROM tramite_fifonafe_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_fifonafe=NEW.id_tramite_fifonafe AND e.activo AND c.codigo='oficio_dgaopr_representacion' ORDER BY e.ordinal DESC LIMIT 1),
        fecha_oficio_dgaopr_a_representacion=(SELECT e.fecha_oficio FROM tramite_fifonafe_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_fifonafe=NEW.id_tramite_fifonafe AND e.activo AND c.codigo='oficio_dgaopr_representacion' ORDER BY e.ordinal DESC LIMIT 1),
        no_oficio_respuesta_representacion_a_dgaopr=(SELECT e.numero_oficio FROM tramite_fifonafe_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_fifonafe=NEW.id_tramite_fifonafe AND e.activo AND c.codigo='respuesta_representacion_dgaopr' ORDER BY e.ordinal DESC LIMIT 1),
        fecha_oficio_respuesta_representacion_a_dgaopr=(SELECT e.fecha_oficio FROM tramite_fifonafe_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_fifonafe=NEW.id_tramite_fifonafe AND e.activo AND c.codigo='respuesta_representacion_dgaopr' ORDER BY e.ordinal DESC LIMIT 1),
        no_oficio_respuesta_dgaopr_a_fifonafe=(SELECT e.numero_oficio FROM tramite_fifonafe_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_fifonafe=NEW.id_tramite_fifonafe AND e.activo AND c.codigo='respuesta_dgaopr_fifonafe' ORDER BY e.ordinal DESC LIMIT 1),
        fecha_oficio_respuesta_dgaopr_a_fifonafe=(SELECT e.fecha_oficio FROM tramite_fifonafe_evento e JOIN catalogo_operativo c ON c.id_catalogo_opcion=e.id_tipo_evento WHERE e.id_tramite_fifonafe=NEW.id_tramite_fifonafe AND e.activo AND c.codigo='respuesta_dgaopr_fifonafe' ORDER BY e.ordinal DESC LIMIT 1),
        actualizado_en=now(), actualizado_por=NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER
    WHERE t.id_tramite_fifonafe=NEW.id_tramite_fifonafe;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_evento_fifonafe_resumen_legacy
    AFTER INSERT OR UPDATE OF id_tipo_evento,numero_oficio,fecha_oficio,activo
    ON tramite_fifonafe_evento FOR EACH ROW EXECUTE FUNCTION fn_036_resumir_fifonafe_legacy();

-- ---------------------------------------------------------------------------
-- Checklist documental estructurado.
-- ---------------------------------------------------------------------------

CREATE TABLE requisito_documental (
    id_requisito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    nombre VARCHAR(250) NOT NULL,
    descripcion TEXT,
    contexto VARCHAR(80) NOT NULL DEFAULT 'general',
    obligatorio BOOLEAN NOT NULL DEFAULT FALSE,
    orden INTEGER NOT NULL DEFAULT 0,
    fuente VARCHAR(250),
    vigencia_inicio DATE,
    vigencia_fin DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_requisito_codigo CHECK (codigo ~ '^[a-z0-9][a-z0-9_-]*$'),
    CONSTRAINT chk_requisito_nombre CHECK (NULLIF(btrim(nombre), '') IS NOT NULL),
    CONSTRAINT chk_requisito_vigencia CHECK (vigencia_fin IS NULL OR vigencia_inicio IS NULL OR vigencia_fin >= vigencia_inicio),
    CONSTRAINT chk_requisito_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE INDEX idx_requisito_lista ON requisito_documental (contexto,activo DESC,orden,nombre);
CREATE TRIGGER trg_036_requisito_no_delete
    BEFORE DELETE ON requisito_documental
    FOR EACH ROW EXECUTE FUNCTION fn_036_catalogo_alias_no_delete();

INSERT INTO requisito_documental (codigo,nombre,contexto,orden,fuente) VALUES
    ('padron','Padrón de ejidatarios/comuneros','datos_generales',10,'Excel colectivo/FIFONAFE'),
    ('acta_eleccion_orv','Acta de elección de ORV','orv',20,'Excel colectivo/FIFONAFE'),
    ('constancia_orv_ran','Constancia/inscripción ORV en RAN','orv',30,'Excel colectivo/RAN'),
    ('convocatoria_asamblea','Convocatoria de asamblea','asamblea',40,'Excel colectivo/FIFONAFE'),
    ('acta_no_verificativo','Acta de no verificativo','asamblea',50,'Excel colectivo/FIFONAFE'),
    ('acta_asamblea','Acta de asamblea','asamblea',60,'Excel colectivo/FIFONAFE'),
    ('convenio_ocupacion_previa','Convenio de ocupación previa','convenio',70,'Excel colectivo/Reglamento MOPR'),
    ('acuse_ran','Acuse de ingreso al RAN','ran',80,'Excel colectivo/RAN'),
    ('soporte_sensibilizacion','Soporte de sensibilización','actividad',90,'Excel colectivo 2026'),
    ('soporte_caminamiento','Soporte de caminamiento','actividad',100,'Excel colectivo 2026');

CREATE TABLE expediente_requisito (
    id_expediente_requisito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto_nucleo INTEGER NOT NULL REFERENCES proyecto_nucleo(id_proyecto_nucleo),
    id_afectacion INTEGER REFERENCES afectacion(id_afectacion),
    id_requisito BIGINT NOT NULL REFERENCES requisito_documental(id_requisito),
    id_estado BIGINT NOT NULL REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_documento INTEGER REFERENCES documento(id_documento),
    detalle TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_expediente_requisito_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE UNIQUE INDEX uq_expediente_requisito
    ON expediente_requisito (id_proyecto_nucleo,id_requisito,COALESCE(id_afectacion,0)) WHERE activo;
CREATE INDEX idx_expediente_requisito_estado
    ON expediente_requisito (id_proyecto_nucleo,id_estado) WHERE activo;

-- ---------------------------------------------------------------------------
-- Trazabilidad específica de archivo tabular/celda. importacion_feature sigue
-- reservado al importador GIS y no se fuerza para datos Excel.
-- ---------------------------------------------------------------------------

CREATE TABLE importacion_tabular (
    id_importacion_tabular BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proyecto INTEGER NOT NULL REFERENCES proyecto(id_proyecto),
    archivo VARCHAR(255) NOT NULL,
    sha256 CHAR(64) NOT NULL,
    hoja VARCHAR(255) NOT NULL,
    filas_detectadas INTEGER NOT NULL DEFAULT 0,
    filas_procesadas INTEGER NOT NULL DEFAULT 0,
    advertencias INTEGER NOT NULL DEFAULT 0,
    errores INTEGER NOT NULL DEFAULT 0,
    estado VARCHAR(30) NOT NULL DEFAULT 'auditado',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT uq_importacion_tabular UNIQUE (id_proyecto,sha256,hoja),
    CONSTRAINT chk_importacion_tabular_hash CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_importacion_tabular_conteos CHECK (
        filas_detectadas >= 0 AND filas_procesadas >= 0 AND advertencias >= 0 AND errores >= 0
    ),
    CONSTRAINT chk_importacion_tabular_estado CHECK (estado IN ('auditado','previsualizado','importando','completo','con_advertencias','error','cancelado')),
    CONSTRAINT chk_importacion_tabular_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);
CREATE INDEX idx_importacion_tabular_proyecto
    ON importacion_tabular (id_proyecto,creado_en DESC) WHERE activo;

CREATE TABLE importacion_tabular_celda (
    id_importacion_celda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_importacion_tabular BIGINT NOT NULL REFERENCES importacion_tabular(id_importacion_tabular),
    fila INTEGER NOT NULL,
    columna VARCHAR(20) NOT NULL,
    encabezado VARCHAR(300),
    valor_original TEXT,
    valor_normalizado TEXT,
    tratamiento VARCHAR(30) NOT NULL,
    mensajes JSONB NOT NULL DEFAULT '[]'::JSONB,
    entidad_tipo VARCHAR(50),
    entidad_id BIGINT,
    registrado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    id_usuario_registro INTEGER REFERENCES usuario(id_usuario),
    CONSTRAINT uq_importacion_tabular_celda UNIQUE (id_importacion_tabular,fila,columna),
    CONSTRAINT chk_importacion_celda_fila CHECK (fila > 0),
    CONSTRAINT chk_importacion_celda_columna CHECK (columna ~ '^[A-Z]+$'),
    CONSTRAINT chk_importacion_celda_tratamiento CHECK (tratamiento IN (
        'PERSISTIR','DERIVAR','REFERENCIA','DOCUMENTAR','REVISAR','NO_IMPLEMENTAR','ERROR'
    )),
    CONSTRAINT chk_importacion_celda_objetivo CHECK (
        (entidad_tipo IS NULL AND entidad_id IS NULL) OR (entidad_tipo IS NOT NULL AND entidad_id IS NOT NULL)
    )
);
CREATE INDEX idx_importacion_celda_origen
    ON importacion_tabular_celda (id_importacion_tabular,fila);
CREATE INDEX idx_importacion_celda_objetivo
    ON importacion_tabular_celda (entidad_tipo,entidad_id) WHERE entidad_id IS NOT NULL;

ALTER TABLE trazabilidad_fuente
    ADD COLUMN id_importacion_tabular BIGINT REFERENCES importacion_tabular(id_importacion_tabular),
    ADD COLUMN valor_normalizado TEXT,
    ADD COLUMN mensajes JSONB NOT NULL DEFAULT '[]'::JSONB;

-- ---------------------------------------------------------------------------
-- Validaciones cruzadas de categorías, núcleos, contextos y objetivos.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_036_validar_catalogos_dominio()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_codigo TEXT;
    v_organo TEXT;
    v_cargo TEXT;
BEGIN
    IF TG_TABLE_NAME='nucleo_agrario' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_tenencia,'tipo_tenencia') THEN
            RAISE EXCEPTION 'Tipo de tenencia inválido';
        END IF;
        SELECT codigo INTO v_codigo FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_tipo_tenencia;
        NEW.tipo_nucleo := v_codigo;
    ELSIF TG_TABLE_NAME='proyecto_nucleo' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_residencia,'residencia') THEN
            RAISE EXCEPTION 'Residencia inválida';
        END IF;
        IF NEW.id_residencia IS NOT NULL THEN
            SELECT nombre INTO NEW.residencia FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_residencia;
        END IF;
    ELSIF TG_TABLE_NAME='orv' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_estado_registral,'estado_registral_orv') THEN
            RAISE EXCEPTION 'Estado registral ORV inválido';
        END IF;
        IF NEW.id_estado_registral IS NOT NULL THEN
            SELECT codigo INTO v_codigo FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_estado_registral;
            NEW.acta_eleccion_inscrita_ran := CASE WHEN v_codigo='inscrita' THEN TRUE WHEN v_codigo='no_ingresada' THEN FALSE ELSE NULL END;
        END IF;
    ELSIF TG_TABLE_NAME='orv_integrante' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_organo,'organo_orv')
           OR NOT fn_036_opcion_catalogo_valida(NEW.id_cargo,'cargo_orv')
           OR NOT fn_036_opcion_catalogo_valida(NEW.id_calidad,'calidad_integrante_orv') THEN
            RAISE EXCEPTION 'Estructura ORV inválida';
        END IF;
        IF NEW.id_organo IS NOT NULL THEN
            SELECT codigo INTO v_organo FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_organo;
            SELECT codigo INTO v_cargo FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_cargo;
            IF (v_organo='comisariado' AND v_cargo NOT IN ('presidente','secretario','tesorero'))
               OR (v_organo='consejo_vigilancia' AND v_cargo NOT IN ('presidente','secretario_1','secretario_2')) THEN
                RAISE EXCEPTION 'Cargo % no pertenece al órgano %',v_cargo,v_organo;
            END IF;
        END IF;
    ELSIF TG_TABLE_NAME='bien_afectado' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_gestion,'tipo_gestion')
           OR NOT fn_036_opcion_catalogo_valida(NEW.id_destino_superficie,'destino_superficie')
           OR NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_cop_operativo,'tipo_cop_operativo') THEN
            RAISE EXCEPTION 'Catálogo de bien afectado inválido';
        END IF;
    ELSIF TG_TABLE_NAME='asamblea_convocatoria' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_resultado,'resultado_convocatoria') THEN
            RAISE EXCEPTION 'Resultado de convocatoria inválido';
        END IF;
    ELSIF TG_TABLE_NAME='tramite_ran_evento' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_evento,'tipo_evento_ran') THEN
            RAISE EXCEPTION 'Tipo de evento RAN inválido';
        END IF;
    ELSIF TG_TABLE_NAME='tramite_fifonafe_evento' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_evento,'tipo_evento_fifonafe') THEN
            RAISE EXCEPTION 'Tipo de evento FIFONAFE inválido';
        END IF;
    ELSIF TG_TABLE_NAME='expediente_requisito' THEN
        IF NOT fn_036_opcion_catalogo_valida(NEW.id_estado,'estado_requisito_documental') THEN
            RAISE EXCEPTION 'Estado de requisito documental inválido';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_036_nucleo_catalogo BEFORE INSERT OR UPDATE OF id_tipo_tenencia,tipo_nucleo ON nucleo_agrario FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();
CREATE TRIGGER trg_036_pn_catalogo BEFORE INSERT OR UPDATE OF id_residencia,residencia ON proyecto_nucleo FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();
CREATE TRIGGER trg_036_orv_catalogo BEFORE INSERT OR UPDATE OF id_estado_registral,acta_eleccion_inscrita_ran ON orv FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();
CREATE TRIGGER trg_036_integrante_catalogo BEFORE INSERT OR UPDATE OF id_organo,id_cargo,id_calidad ON orv_integrante FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();
CREATE TRIGGER trg_036_bien_catalogo BEFORE INSERT OR UPDATE OF id_tipo_gestion,id_destino_superficie,id_tipo_cop_operativo ON bien_afectado FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();
CREATE TRIGGER trg_036_convocatoria_catalogo BEFORE INSERT OR UPDATE OF id_resultado ON asamblea_convocatoria FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();
CREATE TRIGGER trg_036_evento_ran_catalogo BEFORE INSERT OR UPDATE OF id_tipo_evento ON tramite_ran_evento FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();
CREATE TRIGGER trg_036_evento_fifonafe_catalogo BEFORE INSERT OR UPDATE OF id_tipo_evento ON tramite_fifonafe_evento FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();
CREATE TRIGGER trg_036_requisito_estado BEFORE INSERT OR UPDATE OF id_estado ON expediente_requisito FOR EACH ROW EXECUTE FUNCTION fn_036_validar_catalogos_dominio();

CREATE OR REPLACE FUNCTION fn_036_validar_bien_parcela()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE v_nucleo_bien INTEGER; v_nucleo_parcela INTEGER;
BEGIN
    IF NEW.id_parcela IS NOT NULL AND NEW.activo THEN
        SELECT pn.id_nucleo INTO v_nucleo_bien
        FROM afectacion a JOIN proyecto_nucleo pn ON pn.id_proyecto_nucleo=a.id_proyecto_nucleo
        WHERE a.id_afectacion=NEW.id_afectacion AND a.activo AND pn.activo;
        SELECT id_nucleo INTO v_nucleo_parcela FROM parcela WHERE id_parcela=NEW.id_parcela AND activo;
        IF v_nucleo_bien IS NULL OR v_nucleo_parcela IS NULL OR v_nucleo_bien<>v_nucleo_parcela THEN
            RAISE EXCEPTION 'La parcela del bien debe pertenecer al mismo núcleo';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_bien_parcela
    BEFORE INSERT OR UPDATE OF id_afectacion,id_parcela,activo ON bien_afectado
    FOR EACH ROW EXECUTE FUNCTION fn_036_validar_bien_parcela();

CREATE OR REPLACE FUNCTION fn_036_sync_asamblea_catalogos()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE v_tipo TEXT; v_contexto TEXT;
BEGIN
    IF NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_asamblea,'tipo_asamblea')
       OR NOT fn_036_opcion_catalogo_valida(NEW.id_contexto_asamblea,'contexto_asamblea') THEN
        RAISE EXCEPTION 'Tipo o contexto de asamblea inválido';
    END IF;
    SELECT codigo INTO v_tipo FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_tipo_asamblea;
    SELECT codigo INTO v_contexto FROM catalogo_operativo WHERE id_catalogo_opcion=NEW.id_contexto_asamblea;
    IF (v_tipo='retiro_fondos' AND v_contexto IS DISTINCT FROM 'retiro_fondos')
       OR (v_tipo='anuencia' AND v_contexto='retiro_fondos') THEN
        RAISE EXCEPTION 'Tipo de asamblea y contexto contradictorios';
    END IF;
    NEW.tipo_asamblea := v_tipo;
    NEW.contexto_proceso := v_contexto;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_asamblea_catalogos
    BEFORE INSERT OR UPDATE OF id_tipo_asamblea,id_contexto_asamblea,tipo_asamblea,contexto_proceso ON asamblea
    FOR EACH ROW EXECUTE FUNCTION fn_036_sync_asamblea_catalogos();

CREATE OR REPLACE FUNCTION fn_036_validar_tramite_ran()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE v_pn INTEGER; v_nucleo_obj INTEGER; v_nucleo_pn INTEGER;
BEGIN
    IF NEW.id_asamblea IS NOT NULL THEN
        SELECT id_proyecto_nucleo INTO v_pn FROM asamblea WHERE id_asamblea=NEW.id_asamblea AND activo;
    ELSIF NEW.id_convenio IS NOT NULL THEN
        SELECT id_proyecto_nucleo INTO v_pn FROM convenio WHERE id_convenio=NEW.id_convenio AND activo;
    ELSE
        SELECT id_nucleo INTO v_nucleo_obj FROM orv WHERE id_orv=NEW.id_orv AND activo;
        SELECT id_nucleo INTO v_nucleo_pn FROM proyecto_nucleo WHERE id_proyecto_nucleo=NEW.id_proyecto_nucleo AND activo;
        IF v_nucleo_obj IS NULL OR v_nucleo_pn IS NULL OR v_nucleo_obj<>v_nucleo_pn THEN
            RAISE EXCEPTION 'El ORV del trámite RAN debe pertenecer al núcleo del expediente';
        END IF;
        RETURN NEW;
    END IF;
    IF v_pn IS NULL OR v_pn<>NEW.id_proyecto_nucleo THEN
        RAISE EXCEPTION 'El objetivo RAN debe pertenecer al mismo ProyectoNucleo';
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_tramite_ran_objetivo
    BEFORE INSERT OR UPDATE OF id_proyecto_nucleo,id_asamblea,id_convenio,id_orv,activo ON tramite_ran
    FOR EACH ROW EXECUTE FUNCTION fn_036_validar_tramite_ran();

CREATE OR REPLACE FUNCTION fn_036_validar_expediente_requisito()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE v_pn INTEGER;
BEGIN
    IF NEW.id_afectacion IS NOT NULL THEN
        SELECT id_proyecto_nucleo INTO v_pn FROM afectacion WHERE id_afectacion=NEW.id_afectacion AND activo;
        IF v_pn IS NULL OR v_pn<>NEW.id_proyecto_nucleo THEN
            RAISE EXCEPTION 'La afectación del requisito debe pertenecer al mismo ProyectoNucleo';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_expediente_requisito
    BEFORE INSERT OR UPDATE OF id_proyecto_nucleo,id_afectacion,activo ON expediente_requisito
    FOR EACH ROW EXECUTE FUNCTION fn_036_validar_expediente_requisito();

-- Padre/hijo real: mismo expediente/ámbito, sin ciclos y con relación semántica.
CREATE OR REPLACE FUNCTION fn_validar_convenio_relaciones()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE v_padre convenio%ROWTYPE; v_asamblea asamblea%ROWTYPE; v_contexto TEXT;
BEGIN
    IF NEW.id_convenio_padre IS NOT NULL THEN
        SELECT * INTO v_padre FROM convenio WHERE id_convenio=NEW.id_convenio_padre AND activo;
        IF v_padre.id_convenio IS NULL OR v_padre.id_proyecto_nucleo<>NEW.id_proyecto_nucleo OR v_padre.ambito<>NEW.ambito THEN
            RAISE EXCEPTION 'El convenio padre debe estar activo y pertenecer al mismo ProyectoNucleo/ámbito';
        END IF;
        IF NEW.tipo_convenio='cop_original'
           OR (NEW.tipo_convenio='superficie_adicional' AND v_padre.tipo_convenio NOT IN ('cop_original','superficie_adicional'))
           OR (NEW.tipo_convenio='obras_complementarias' AND v_padre.tipo_convenio NOT IN ('cop_original','obras_complementarias'))
           OR (NEW.tipo_convenio IN ('ampliacion','ampliacion_remanente') AND v_padre.tipo_convenio NOT IN ('cop_original','ampliacion')) THEN
            RAISE EXCEPTION 'Relación padre/hijo no permitida para los tipos de convenio';
        END IF;
        IF NEW.id_convenio IS NOT NULL AND EXISTS (
            WITH RECURSIVE ancestro AS (
                SELECT id_convenio_padre FROM convenio WHERE id_convenio=NEW.id_convenio_padre
                UNION ALL SELECT c.id_convenio_padre FROM convenio c JOIN ancestro a ON c.id_convenio=a.id_convenio_padre
                WHERE c.id_convenio_padre IS NOT NULL
            ) SELECT 1 FROM ancestro WHERE id_convenio_padre=NEW.id_convenio
        ) THEN RAISE EXCEPTION 'La relación de convenios produciría un ciclo'; END IF;
    END IF;
    IF NEW.id_asamblea_autorizacion IS NOT NULL THEN
        SELECT * INTO v_asamblea FROM asamblea WHERE id_asamblea=NEW.id_asamblea_autorizacion AND activo;
        IF NEW.ambito<>'colectivo' OR v_asamblea.id_asamblea IS NULL OR v_asamblea.id_proyecto_nucleo<>NEW.id_proyecto_nucleo THEN
            RAISE EXCEPTION 'La asamblea sólo autoriza convenios colectivos del mismo ProyectoNucleo';
        END IF;
        SELECT c.codigo INTO v_contexto FROM catalogo_operativo c WHERE c.id_catalogo_opcion=v_asamblea.id_contexto_asamblea;
        IF v_contexto IS NOT NULL AND v_contexto<>'otro' AND v_contexto<>NEW.tipo_convenio THEN
            RAISE EXCEPTION 'El contexto de la asamblea no corresponde al tipo de convenio';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;

-- Extensión de objetivos documentales y de trazabilidad controlados.
ALTER TABLE documento_vinculo DROP CONSTRAINT chk_documento_vinculo_tipo;
ALTER TABLE documento_vinculo ADD CONSTRAINT chk_documento_vinculo_tipo CHECK (entidad_tipo IN (
    'proyecto_nucleo','nucleo_agrario','orv','padron_historial','parcela','afectacion','bien_afectado',
    'asamblea','asamblea_convocatoria','convenio','tramite_ran','tramite_ran_evento',
    'tramite_fifonafe','tramite_fifonafe_evento','indemnizacion','pago','expediente_requisito'
));

CREATE OR REPLACE FUNCTION fn_objetivo_controlado_existe(p_tipo TEXT, p_id BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql STABLE AS $fn$
DECLARE v_pk TEXT; v_exists BOOLEAN;
BEGIN
    v_pk := CASE p_tipo
        WHEN 'proyecto' THEN 'id_proyecto' WHEN 'proyecto_nucleo' THEN 'id_proyecto_nucleo'
        WHEN 'proyecto_nucleo_referencia' THEN 'id_referencia' WHEN 'proyecto_nucleo_responsable' THEN 'id_responsable'
        WHEN 'nucleo_agrario' THEN 'id_nucleo' WHEN 'persona' THEN 'id_persona'
        WHEN 'orv' THEN 'id_orv' WHEN 'orv_integrante' THEN 'id_orv_integrante'
        WHEN 'padron_historial' THEN 'id_padron' WHEN 'parcela' THEN 'id_parcela'
        WHEN 'parcela_titular' THEN 'id_parcela_titular' WHEN 'actividad_campo' THEN 'id_actividad'
        WHEN 'afectacion' THEN 'id_afectacion' WHEN 'bien_afectado' THEN 'id_bien_afectado'
        WHEN 'asamblea' THEN 'id_asamblea' WHEN 'asamblea_convocatoria' THEN 'id_convocatoria'
        WHEN 'convenio' THEN 'id_convenio' WHEN 'tramite_ran' THEN 'id_tramite_ran'
        WHEN 'tramite_ran_evento' THEN 'id_evento_ran' WHEN 'tramite_fifonafe' THEN 'id_tramite_fifonafe'
        WHEN 'tramite_fifonafe_evento' THEN 'id_evento_fifonafe'
        WHEN 'indemnizacion' THEN 'id_indemnizacion' WHEN 'pago' THEN 'id_pago'
        WHEN 'documento' THEN 'id_documento' WHEN 'expediente_requisito' THEN 'id_expediente_requisito'
        WHEN 'importacion_tabular' THEN 'id_importacion_tabular' ELSE NULL END;
    IF v_pk IS NULL OR to_regclass('public.'||p_tipo) IS NULL THEN RETURN FALSE; END IF;
    EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I WHERE %I=$1)',p_tipo,v_pk) INTO v_exists USING p_id;
    RETURN v_exists;
END;
$fn$;

CREATE OR REPLACE FUNCTION fn_036_validar_importacion_celda()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
    IF NEW.entidad_id IS NOT NULL AND NOT fn_objetivo_controlado_existe(NEW.entidad_tipo,NEW.entidad_id) THEN
        RAISE EXCEPTION 'Objetivo de celda importada %:% no existe',NEW.entidad_tipo,NEW.entidad_id;
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_036_importacion_celda_objetivo
    BEFORE INSERT OR UPDATE OF entidad_tipo,entidad_id ON importacion_tabular_celda
    FOR EACH ROW EXECUTE FUNCTION fn_036_validar_importacion_celda();

-- ---------------------------------------------------------------------------
-- Auditoría, privilegios runtime y registro de versión.
-- ---------------------------------------------------------------------------

DO $audit_triggers$
DECLARE v_item TEXT[];
BEGIN
    FOREACH v_item SLICE 1 IN ARRAY ARRAY[
        ARRAY['catalogo_operativo','id_catalogo_opcion'],
        ARRAY['catalogo_operativo_alias','id_catalogo_alias'],
        ARRAY['proyecto_nucleo_responsable','id_responsable'],
        ARRAY['bien_afectado','id_bien_afectado'],
        ARRAY['asamblea_convocatoria','id_convocatoria'],
        ARRAY['tramite_ran','id_tramite_ran'],
        ARRAY['tramite_ran_evento','id_evento_ran'],
        ARRAY['tramite_fifonafe_evento','id_evento_fifonafe'],
        ARRAY['requisito_documental','id_requisito'],
        ARRAY['expediente_requisito','id_expediente_requisito'],
        ARRAY['importacion_tabular','id_importacion_tabular']
    ] LOOP
        EXECUTE format(
            'CREATE TRIGGER %I AFTER INSERT OR UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION fn_audit_log(%L)',
            'trg_audit_'||v_item[1],v_item[1],v_item[2]
        );
    END LOOP;
END;
$audit_triggers$;

GRANT SELECT, INSERT, UPDATE ON catalogo_operativo,catalogo_operativo_alias,
    proyecto_nucleo_responsable,bien_afectado,asamblea_convocatoria,
    tramite_ran,tramite_ran_evento,tramite_fifonafe_evento,
    requisito_documental,expediente_requisito,importacion_tabular,
    importacion_tabular_celda TO software_pa_app;
GRANT SELECT ON vw_convenio_tipo_cop_operativo TO software_pa_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO software_pa_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON catalogo_operativo,catalogo_operativo_alias,
    proyecto_nucleo_responsable,bien_afectado,asamblea_convocatoria,
    tramite_ran,tramite_ran_evento,tramite_fifonafe_evento,
    requisito_documental,expediente_requisito,importacion_tabular,
    importacion_tabular_celda FROM software_pa_app;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE ON schema_migrations FROM software_pa_app;

INSERT INTO schema_migrations (version,descripcion)
VALUES ('036','Modelo operativo normalizado del Excel colectivo vigente');

COMMIT;
