-- 037_normalizacion_unidad_agraria_afectacion.sql
--
-- Corrige la granularidad introducida por 036 sin reescribir migraciones previas.
-- Objetivos:
--   1) separar la identidad del bien/unidad agraria del hecho ProyectoNucleo/Afectacion;
--   2) normalizar tipo de tierra y titularidad;
--   3) mantener colectivo/individual independiente de TIPO_GESTION;
--   4) mover TIPO COP operativo al nivel de Afectacion (planeacion/proceso),
--      dejando bien_afectado.id_tipo_cop_operativo solo como compatibilidad;
--   5) modelar NO AFECTA TUC en ProyectoNucleo sin crear afectaciones ficticias;
--   6) preservar datos 036 mediante backfill conservador y trazable.
--
-- Esta migracion NO cierra todavia los contratos legacy de Asamblea/RAN/FIFONAFE.

BEGIN;

SELECT pg_advisory_xact_lock(20260831, 37);

DO $preflight$
DECLARE
    v_required TEXT;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = '036') THEN
        RAISE EXCEPTION '037 requiere la migracion 036';
    END IF;
    IF EXISTS (SELECT 1 FROM schema_migrations WHERE version = '037') THEN
        RAISE EXCEPTION 'La migracion 037 ya fue aplicada';
    END IF;

    FOREACH v_required IN ARRAY ARRAY[
        'usuario','catalogo_operativo','nucleo_agrario','proyecto_nucleo','parcela',
        'parcela_titular','persona','afectacion','bien_afectado','documento_vinculo',
        'schema_migrations'
    ] LOOP
        IF to_regclass('public.' || v_required) IS NULL THEN
            RAISE EXCEPTION '037 requiere la tabla %', v_required;
        END IF;
    END LOOP;

    IF to_regclass('public.unidad_agraria') IS NOT NULL
       OR to_regclass('public.afectacion_unidad_agraria') IS NOT NULL
       OR to_regclass('public.unidad_agraria_titular') IS NOT NULL THEN
        RAISE EXCEPTION '037 encontro estructuras objetivo preexistentes; revisar estado antes de continuar';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM usuario WHERE activo) THEN
        RAISE EXCEPTION '037 requiere al menos un usuario activo para auditar el backfill';
    END IF;
END;
$preflight$;

SELECT set_config(
    'app.current_user_id',
    (SELECT min(id_usuario)::TEXT FROM usuario WHERE activo),
    TRUE
);

-- ---------------------------------------------------------------------------
-- 1. Catalogos nuevos: tipo de tierra, titularidad y motivo de no afectacion TUC.
-- ---------------------------------------------------------------------------

INSERT INTO catalogo_operativo
    (tipo_catalogo, codigo, nombre, descripcion, orden, fuente)
VALUES
    ('tipo_tierra','uso_comun','Tierras de uso comun',
     'Destino juridico/catastral de tierras de uso comun; no equivale por si solo a ambito colectivo.',
     10,'Ley Agraria/RAN'),
    ('tipo_tierra','parcelada','Tierra parcelada',
     'Tierra identificada como parcelada; no determina por si sola el ambito de la afectacion.',
     20,'Ley Agraria/RAN'),
    ('tipo_tierra','asentamiento_humano','Asentamiento humano',
     'Tierra destinada al asentamiento humano.',30,'Ley Agraria/RAN'),
    ('tipo_tierra','otra','Otra',NULL,900,'Modelo operativo'),
    ('tipo_tierra','no_determinada','No determinada',
     'La fuente disponible no permite clasificar sin inferencia.',999,'Modelo operativo'),

    ('tipo_titularidad_unidad','nucleo_agrario','Nucleo agrario',
     'El derecho/bien se administra como titularidad del nucleo agrario.',10,'Modelo agrario'),
    ('tipo_titularidad_unidad','persona','Persona titular',
     'Existe una persona titular identificada mediante relaciones normalizadas.',20,'Modelo individual'),
    ('tipo_titularidad_unidad','copropiedad','Copropiedad / cotitularidad',
     'Existen dos o mas titulares identificados.',30,'Modelo individual'),
    ('tipo_titularidad_unidad','no_determinada','No determinada',
     'La fuente no permite establecer titularidad sin revision.',900,'Modelo operativo'),
    ('tipo_titularidad_unidad','otra','Otra',NULL,999,'Modelo operativo'),

    ('motivo_no_afecta_tuc','expropiacion_directa','Expropiacion directa',
     'Salida operativa cuando no se da seguimiento PA a TUC por expropiacion directa.',10,'Fuente funcional'),
    ('motivo_no_afecta_tuc','comunidad_indigena','Comunidad indigena',
     'Motivo operativo diferenciado; no sustituye nucleo_agrario.comunidad_indigena.',20,'Fuente funcional'),
    ('motivo_no_afecta_tuc','no_afectacion_colectiva','No existe afectacion colectiva a TUC',
     'El proyecto no afecta tierras de uso comun en el contexto del expediente.',30,'Fuente funcional'),
    ('motivo_no_afecta_tuc','otro','Otro',NULL,999,'Modelo operativo')
ON CONFLICT (tipo_catalogo, codigo) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 2. Unidad agraria: identidad estable a nivel NucleoAgrario.
-- ---------------------------------------------------------------------------

CREATE TABLE unidad_agraria (
    id_unidad_agraria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_nucleo INTEGER NOT NULL REFERENCES nucleo_agrario(id_nucleo),
    id_tipo_tierra BIGINT NOT NULL REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_tipo_gestion BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_destino_superficie BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_tipo_titularidad BIGINT NOT NULL REFERENCES catalogo_operativo(id_catalogo_opcion),
    id_parcela INTEGER REFERENCES parcela(id_parcela),
    referencia_alfanumerica VARCHAR(150),
    referencia_normalizada VARCHAR(150),
    detalle TEXT,
    fuente VARCHAR(250),
    requiere_revision BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_revision TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_unidad_agraria_dato CHECK (
        id_parcela IS NOT NULL
        OR id_tipo_gestion IS NOT NULL
        OR id_destino_superficie IS NOT NULL
        OR NULLIF(btrim(referencia_alfanumerica), '') IS NOT NULL
        OR NULLIF(btrim(detalle), '') IS NOT NULL
    ),
    CONSTRAINT chk_unidad_agraria_revision CHECK (
        NOT requiere_revision OR NULLIF(btrim(motivo_revision), '') IS NOT NULL
    ),
    CONSTRAINT chk_unidad_agraria_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);

CREATE INDEX idx_unidad_agraria_nucleo
    ON unidad_agraria (id_nucleo) WHERE activo;
CREATE INDEX idx_unidad_agraria_parcela
    ON unidad_agraria (id_parcela) WHERE activo AND id_parcela IS NOT NULL;
CREATE INDEX idx_unidad_agraria_clasificacion
    ON unidad_agraria (id_tipo_tierra, id_tipo_gestion, id_destino_superficie) WHERE activo;
CREATE INDEX idx_unidad_agraria_referencia
    ON unidad_agraria (id_nucleo, referencia_normalizada)
    WHERE activo AND referencia_normalizada IS NOT NULL;

COMMENT ON TABLE unidad_agraria IS
    'Identidad de bien/unidad agraria del NucleoAgrario. No depende de un ProyectoNucleo ni de una Afectacion concreta.';
COMMENT ON COLUMN unidad_agraria.id_tipo_tierra IS
    'Clasificacion normalizada; no se infiere automaticamente desde TIPO_GESTION ni destino.';
COMMENT ON COLUMN unidad_agraria.id_tipo_titularidad IS
    'Clasificacion normalizada de titularidad. Los titulares persona se detallan en unidad_agraria_titular.';
COMMENT ON COLUMN unidad_agraria.id_parcela IS
    'Referencia opcional a parcela. Puede existir en unidades colectivas sin convertir la afectacion en individual.';

CREATE TABLE unidad_agraria_titular (
    id_unidad_titular BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_unidad_agraria BIGINT NOT NULL REFERENCES unidad_agraria(id_unidad_agraria),
    id_persona INTEGER REFERENCES persona(id_persona),
    id_parcela_titular INTEGER REFERENCES parcela_titular(id_parcela_titular),
    porcentaje_participacion NUMERIC(7,4),
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_unidad_titular_objetivo CHECK (num_nonnulls(id_persona,id_parcela_titular) = 1),
    CONSTRAINT chk_unidad_titular_porcentaje CHECK (
        porcentaje_participacion IS NULL OR (porcentaje_participacion > 0 AND porcentaje_participacion <= 100)
    ),
    CONSTRAINT chk_unidad_titular_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_unidad_titular_persona
    ON unidad_agraria_titular (id_unidad_agraria,id_persona)
    WHERE activo AND id_persona IS NOT NULL;
CREATE UNIQUE INDEX uq_unidad_titular_parcela_titular
    ON unidad_agraria_titular (id_unidad_agraria,id_parcela_titular)
    WHERE activo AND id_parcela_titular IS NOT NULL;

COMMENT ON TABLE unidad_agraria_titular IS
    'Titulares persona de una unidad agraria. Reutiliza Persona/ParcelaTitular y evita nombres libres como fuente canónica.';

-- ---------------------------------------------------------------------------
-- 3. Relacion Afectacion <-> UnidadAgraria. La superficie pertenece al hecho
--    de afectacion, no a la identidad permanente del bien.
-- ---------------------------------------------------------------------------

CREATE TABLE afectacion_unidad_agraria (
    id_afectacion_unidad BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_afectacion INTEGER NOT NULL REFERENCES afectacion(id_afectacion),
    id_unidad_agraria BIGINT NOT NULL REFERENCES unidad_agraria(id_unidad_agraria),
    superficie_preliminar_ha NUMERIC(14,6),
    superficie_afectada_ha NUMERIC(14,6),
    superficie_valor_original VARCHAR(120),
    superficie_formato_origen VARCHAR(50),
    fuente VARCHAR(250),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_por INTEGER REFERENCES usuario(id_usuario),
    actualizado_en TIMESTAMPTZ,
    actualizado_por INTEGER REFERENCES usuario(id_usuario),
    fecha_baja TIMESTAMPTZ,
    id_usuario_baja INTEGER REFERENCES usuario(id_usuario),
    motivo_baja TEXT,
    observaciones TEXT,
    CONSTRAINT chk_afectacion_unidad_superficie CHECK (
        (superficie_preliminar_ha IS NULL OR superficie_preliminar_ha >= 0)
        AND (superficie_afectada_ha IS NULL OR superficie_afectada_ha >= 0)
    ),
    CONSTRAINT chk_afectacion_unidad_baja CHECK (
        (activo AND fecha_baja IS NULL AND id_usuario_baja IS NULL AND motivo_baja IS NULL)
        OR (NOT activo AND fecha_baja IS NOT NULL AND id_usuario_baja IS NOT NULL
            AND NULLIF(btrim(motivo_baja), '') IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_afectacion_unidad_activa
    ON afectacion_unidad_agraria (id_afectacion,id_unidad_agraria) WHERE activo;
CREATE INDEX idx_afectacion_unidad_unidad
    ON afectacion_unidad_agraria (id_unidad_agraria) WHERE activo;

COMMENT ON TABLE afectacion_unidad_agraria IS
    'Relacion ProyectoNucleo/Afectacion con una unidad agraria del mismo nucleo; permite reutilizar el mismo bien en procesos distintos.';

-- ---------------------------------------------------------------------------
-- 4. Afectacion: TIPO COP operativo se mueve al proceso, no al bien.
-- ---------------------------------------------------------------------------

ALTER TABLE afectacion
    ADD COLUMN id_tipo_cop_operativo BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    ADD COLUMN tipo_cop_revision_pendiente BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN tipo_cop_revision_detalle TEXT,
    ADD CONSTRAINT chk_afectacion_tipo_cop_revision CHECK (
        NOT tipo_cop_revision_pendiente OR NULLIF(btrim(tipo_cop_revision_detalle), '') IS NOT NULL
    );

CREATE INDEX idx_afectacion_tipo_cop_operativo
    ON afectacion (id_tipo_cop_operativo) WHERE activo AND id_tipo_cop_operativo IS NOT NULL;

COMMENT ON COLUMN afectacion.id_tipo_cop_operativo IS
    'Clasificacion operativa de planeacion/proceso (ORIGEN/ADICIONAL/2A ADICIONAL/COMPLEMENTARIAS). El convenio juridico sigue siendo convenio.tipo_convenio + consecutivo.';
COMMENT ON COLUMN bien_afectado.id_tipo_cop_operativo IS
    'LEGACY 036: TIPO COP dejo de ser atributo canónico del bien. Fuente canónica desde 037: afectacion.id_tipo_cop_operativo; retiro previsto al cerrar consumidores legacy.';

-- Mapeo explícito del bien legacy a su unidad canónica.
ALTER TABLE bien_afectado
    ADD COLUMN id_unidad_agraria BIGINT REFERENCES unidad_agraria(id_unidad_agraria);
CREATE INDEX idx_bien_afectado_unidad_agraria
    ON bien_afectado (id_unidad_agraria) WHERE activo AND id_unidad_agraria IS NOT NULL;
COMMENT ON COLUMN bien_afectado.id_unidad_agraria IS
    'Puente de compatibilidad 036->037 hacia la unidad agraria canónica.';

-- ---------------------------------------------------------------------------
-- 5. ProyectoNucleo: resultado NO AFECTA TUC sin afectacion ficticia.
-- ---------------------------------------------------------------------------

ALTER TABLE proyecto_nucleo
    ADD COLUMN afecta_tuc BOOLEAN,
    ADD COLUMN id_motivo_no_afecta_tuc BIGINT REFERENCES catalogo_operativo(id_catalogo_opcion),
    ADD COLUMN motivo_no_afecta_tuc_detalle TEXT,
    ADD COLUMN tuc_revision_pendiente BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN tuc_revision_detalle TEXT,
    ADD CONSTRAINT chk_proyecto_nucleo_alcance_tuc CHECK (
        (afecta_tuc IS NULL AND id_motivo_no_afecta_tuc IS NULL AND motivo_no_afecta_tuc_detalle IS NULL)
        OR (afecta_tuc IS TRUE AND id_motivo_no_afecta_tuc IS NULL AND motivo_no_afecta_tuc_detalle IS NULL)
        OR (afecta_tuc IS FALSE AND id_motivo_no_afecta_tuc IS NOT NULL)
    ),
    ADD CONSTRAINT chk_proyecto_nucleo_tuc_revision CHECK (
        NOT tuc_revision_pendiente OR NULLIF(btrim(tuc_revision_detalle), '') IS NOT NULL
    );

COMMENT ON COLUMN proyecto_nucleo.afecta_tuc IS
    'Trivaluado: NULL=no evaluado/no capturado; TRUE=existe afectacion a TUC; FALSE=se determino que el proyecto no afecta TUC.';
COMMENT ON COLUMN proyecto_nucleo.id_motivo_no_afecta_tuc IS
    'Motivo requerido cuando afecta_tuc=FALSE. No sustituye atributos intrinsecos del nucleo como comunidad_indigena.';

-- ---------------------------------------------------------------------------
-- 6. Funciones de validacion catalogada y coherencia de nucleo.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_037_normalizar_referencia(p_valor TEXT)
RETURNS TEXT LANGUAGE sql IMMUTABLE AS $fn$
    SELECT NULLIF(
        upper(regexp_replace(btrim(COALESCE(p_valor,'')), '[[:space:]]+', ' ', 'g')),
        ''
    );
$fn$;

CREATE OR REPLACE FUNCTION fn_037_validar_unidad_agraria()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_nucleo_parcela INTEGER;
BEGIN
    IF NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_tierra,'tipo_tierra')
       OR NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_gestion,'tipo_gestion')
       OR NOT fn_036_opcion_catalogo_valida(NEW.id_destino_superficie,'destino_superficie')
       OR NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_titularidad,'tipo_titularidad_unidad') THEN
        RAISE EXCEPTION 'La unidad agraria contiene catalogos de tipo incorrecto';
    END IF;

    NEW.referencia_normalizada := fn_037_normalizar_referencia(NEW.referencia_alfanumerica);

    IF NEW.id_parcela IS NOT NULL AND NEW.activo THEN
        SELECT id_nucleo INTO v_nucleo_parcela
        FROM parcela
        WHERE id_parcela=NEW.id_parcela AND activo;
        IF v_nucleo_parcela IS NULL OR v_nucleo_parcela<>NEW.id_nucleo THEN
            RAISE EXCEPTION 'La parcela de la unidad agraria debe pertenecer al mismo nucleo';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_037_unidad_agraria_validar
    BEFORE INSERT OR UPDATE OF id_nucleo,id_tipo_tierra,id_tipo_gestion,id_destino_superficie,
        id_tipo_titularidad,id_parcela,referencia_alfanumerica,activo
    ON unidad_agraria
    FOR EACH ROW EXECUTE FUNCTION fn_037_validar_unidad_agraria();

CREATE OR REPLACE FUNCTION fn_037_validar_unidad_titular()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_nucleo_unidad INTEGER;
    v_nucleo_parcela INTEGER;
    v_persona_parcela INTEGER;
    v_persona_directa INTEGER;
    v_tipo_titularidad TEXT;
BEGIN
    SELECT u.id_nucleo, c.codigo
      INTO v_nucleo_unidad, v_tipo_titularidad
    FROM unidad_agraria u
    JOIN catalogo_operativo c ON c.id_catalogo_opcion=u.id_tipo_titularidad
    WHERE u.id_unidad_agraria=NEW.id_unidad_agraria AND u.activo;

    IF v_nucleo_unidad IS NULL THEN
        RAISE EXCEPTION 'La unidad agraria titular debe estar activa';
    END IF;
    IF v_tipo_titularidad NOT IN ('persona','copropiedad') THEN
        RAISE EXCEPTION 'Solo unidades con titularidad persona/copropiedad admiten titulares persona';
    END IF;

    IF NEW.id_parcela_titular IS NOT NULL THEN
        SELECT p.id_nucleo, pt.id_persona
          INTO v_nucleo_parcela, v_persona_parcela
        FROM parcela_titular pt
        JOIN parcela p ON p.id_parcela=pt.id_parcela
        WHERE pt.id_parcela_titular=NEW.id_parcela_titular
          AND pt.activo AND p.activo;
        IF v_nucleo_parcela IS NULL OR v_nucleo_parcela<>v_nucleo_unidad THEN
            RAISE EXCEPTION 'ParcelaTitular debe pertenecer al mismo nucleo de la unidad agraria';
        END IF;
    ELSE
        SELECT id_persona INTO v_persona_directa
        FROM persona WHERE id_persona=NEW.id_persona AND activo;
        IF v_persona_directa IS NULL THEN
            RAISE EXCEPTION 'La persona titular debe estar activa';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_037_unidad_titular_validar
    BEFORE INSERT OR UPDATE OF id_unidad_agraria,id_persona,id_parcela_titular,activo
    ON unidad_agraria_titular
    FOR EACH ROW EXECUTE FUNCTION fn_037_validar_unidad_titular();

CREATE OR REPLACE FUNCTION fn_037_validar_afectacion_unidad()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_nucleo_afectacion INTEGER;
    v_nucleo_unidad INTEGER;
    v_tipo_afectacion TEXT;
    v_parcela_afectacion INTEGER;
    v_parcela_unidad INTEGER;
BEGIN
    SELECT pn.id_nucleo, a.tipo_afectacion, a.id_parcela
      INTO v_nucleo_afectacion, v_tipo_afectacion, v_parcela_afectacion
    FROM afectacion a
    JOIN proyecto_nucleo pn ON pn.id_proyecto_nucleo=a.id_proyecto_nucleo
    WHERE a.id_afectacion=NEW.id_afectacion AND a.activo AND pn.activo;

    SELECT id_nucleo, id_parcela
      INTO v_nucleo_unidad, v_parcela_unidad
    FROM unidad_agraria
    WHERE id_unidad_agraria=NEW.id_unidad_agraria AND activo;

    IF v_nucleo_afectacion IS NULL OR v_nucleo_unidad IS NULL
       OR v_nucleo_afectacion<>v_nucleo_unidad THEN
        RAISE EXCEPTION 'Afectacion y unidad agraria deben pertenecer al mismo nucleo';
    END IF;

    IF v_tipo_afectacion='individual' THEN
        IF v_parcela_afectacion IS NULL THEN
            RAISE EXCEPTION 'La afectacion individual requiere parcela';
        END IF;
        IF v_parcela_unidad IS NULL OR v_parcela_unidad<>v_parcela_afectacion THEN
            RAISE EXCEPTION 'La unidad de una afectacion individual debe referenciar la misma parcela';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_037_afectacion_unidad_validar
    BEFORE INSERT OR UPDATE OF id_afectacion,id_unidad_agraria,activo
    ON afectacion_unidad_agraria
    FOR EACH ROW EXECUTE FUNCTION fn_037_validar_afectacion_unidad();

CREATE OR REPLACE FUNCTION fn_037_validar_afectacion_tipo_cop()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
    IF NOT fn_036_opcion_catalogo_valida(NEW.id_tipo_cop_operativo,'tipo_cop_operativo') THEN
        RAISE EXCEPTION 'TIPO COP operativo invalido';
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_037_afectacion_tipo_cop
    BEFORE INSERT OR UPDATE OF id_tipo_cop_operativo
    ON afectacion FOR EACH ROW EXECUTE FUNCTION fn_037_validar_afectacion_tipo_cop();

CREATE OR REPLACE FUNCTION fn_037_validar_pn_tuc()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_codigo TEXT;
BEGIN
    IF NOT fn_036_opcion_catalogo_valida(NEW.id_motivo_no_afecta_tuc,'motivo_no_afecta_tuc') THEN
        RAISE EXCEPTION 'Motivo de no afectacion TUC invalido';
    END IF;

    IF NEW.afecta_tuc IS FALSE THEN
        SELECT codigo INTO v_codigo
        FROM catalogo_operativo
        WHERE id_catalogo_opcion=NEW.id_motivo_no_afecta_tuc;
        IF v_codigo='otro' AND NULLIF(btrim(NEW.motivo_no_afecta_tuc_detalle),'') IS NULL THEN
            RAISE EXCEPTION 'El motivo otro requiere detalle';
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;
CREATE TRIGGER trg_037_pn_tuc
    BEFORE INSERT OR UPDATE OF afecta_tuc,id_motivo_no_afecta_tuc,motivo_no_afecta_tuc_detalle
    ON proyecto_nucleo FOR EACH ROW EXECUTE FUNCTION fn_037_validar_pn_tuc();

-- ---------------------------------------------------------------------------
-- 7. Backfill conservador desde bien_afectado 036.
--    No se infiere tipo_tierra desde TIPO_GESTION/destino.
-- ---------------------------------------------------------------------------

DO $backfill_unidades$
DECLARE
    r RECORD;
    v_unidad BIGINT;
    v_tipo_tierra_nd BIGINT;
    v_tit_nucleo BIGINT;
    v_tit_persona BIGINT;
    v_tit_copropiedad BIGINT;
    v_tit_nd BIGINT;
    v_titularidad BIGINT;
    v_titulares INTEGER;
    v_ref_norm TEXT;
    v_existing_gestion BIGINT;
    v_existing_destino BIGINT;
    v_existing_tit BIGINT;
    v_revision BOOLEAN;
    v_revision_detalle TEXT;
BEGIN
    SELECT id_catalogo_opcion INTO v_tipo_tierra_nd
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_tierra' AND codigo='no_determinada';
    SELECT id_catalogo_opcion INTO v_tit_nucleo
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_titularidad_unidad' AND codigo='nucleo_agrario';
    SELECT id_catalogo_opcion INTO v_tit_persona
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_titularidad_unidad' AND codigo='persona';
    SELECT id_catalogo_opcion INTO v_tit_copropiedad
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_titularidad_unidad' AND codigo='copropiedad';
    SELECT id_catalogo_opcion INTO v_tit_nd
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_titularidad_unidad' AND codigo='no_determinada';

    FOR r IN
        SELECT b.*, a.id_proyecto_nucleo, a.tipo_afectacion,
               COALESCE(b.id_parcela,a.id_parcela) AS parcela_efectiva,
               pn.id_nucleo
        FROM bien_afectado b
        JOIN afectacion a ON a.id_afectacion=b.id_afectacion
        JOIN proyecto_nucleo pn ON pn.id_proyecto_nucleo=a.id_proyecto_nucleo
        ORDER BY b.id_bien_afectado
    LOOP
        v_ref_norm := fn_037_normalizar_referencia(r.referencia_alfanumerica);
        v_revision := FALSE;
        v_revision_detalle := NULL;

        IF r.tipo_afectacion='colectivo' THEN
            v_titularidad := v_tit_nucleo;
        ELSIF r.parcela_efectiva IS NOT NULL THEN
            SELECT count(*) INTO v_titulares
            FROM parcela_titular
            WHERE id_parcela=r.parcela_efectiva AND activo;
            IF v_titulares=1 THEN
                v_titularidad := v_tit_persona;
            ELSIF v_titulares>1 THEN
                v_titularidad := v_tit_copropiedad;
            ELSE
                v_titularidad := v_tit_nd;
                v_revision := TRUE;
                v_revision_detalle := 'Afectacion individual sin titular activo identificable durante backfill 037.';
            END IF;
        ELSE
            v_titularidad := v_tit_nd;
            v_revision := TRUE;
            v_revision_detalle := 'No fue posible determinar titularidad durante backfill 037.';
        END IF;

        v_unidad := NULL;

        -- Reutilizacion conservadora: misma parcela + mismo tipo de titularidad.
        IF r.parcela_efectiva IS NOT NULL THEN
            SELECT u.id_unidad_agraria, u.id_tipo_gestion, u.id_destino_superficie, u.id_tipo_titularidad
              INTO v_unidad, v_existing_gestion, v_existing_destino, v_existing_tit
            FROM unidad_agraria u
            WHERE u.id_nucleo=r.id_nucleo
              AND u.id_parcela=r.parcela_efectiva
              AND u.id_tipo_titularidad=v_titularidad
              AND u.activo
            ORDER BY u.id_unidad_agraria
            LIMIT 1;
        ELSIF v_ref_norm IS NOT NULL THEN
            SELECT u.id_unidad_agraria, u.id_tipo_gestion, u.id_destino_superficie, u.id_tipo_titularidad
              INTO v_unidad, v_existing_gestion, v_existing_destino, v_existing_tit
            FROM unidad_agraria u
            WHERE u.id_nucleo=r.id_nucleo
              AND u.id_parcela IS NULL
              AND u.referencia_normalizada=v_ref_norm
              AND u.id_tipo_titularidad=v_titularidad
              AND u.activo
            ORDER BY u.id_unidad_agraria
            LIMIT 1;
        END IF;

        IF v_unidad IS NULL THEN
            IF r.parcela_efectiva IS NULL AND v_ref_norm IS NULL THEN
                v_revision := TRUE;
                v_revision_detalle := concat_ws(' ',v_revision_detalle,
                    'Unidad creada sin parcela/referencia estable; revisar posible deduplicacion del bien 036.');
            END IF;

            INSERT INTO unidad_agraria (
                id_nucleo,id_tipo_tierra,id_tipo_gestion,id_destino_superficie,
                id_tipo_titularidad,id_parcela,referencia_alfanumerica,detalle,fuente,
                requiere_revision,motivo_revision,creado_por,observaciones
            ) VALUES (
                r.id_nucleo,v_tipo_tierra_nd,r.id_tipo_gestion,r.id_destino_superficie,
                v_titularidad,r.parcela_efectiva,r.referencia_alfanumerica,r.detalle,
                COALESCE(r.fuente,'backfill_036'),v_revision,v_revision_detalle,
                COALESCE(r.creado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER),
                'Creada por migracion 037 desde bien_afectado '||r.id_bien_afectado
            ) RETURNING id_unidad_agraria INTO v_unidad;
        ELSE
            -- Si el mismo identificador trae clasificaciones contradictorias, no se sobreescribe:
            -- se conserva la primera y se marca revision.
            IF (v_existing_gestion IS DISTINCT FROM r.id_tipo_gestion AND r.id_tipo_gestion IS NOT NULL)
               OR (v_existing_destino IS DISTINCT FROM r.id_destino_superficie AND r.id_destino_superficie IS NOT NULL) THEN
                UPDATE unidad_agraria
                SET requiere_revision=TRUE,
                    motivo_revision=concat_ws(' ',motivo_revision,
                        'Conflicto de tipo_gestion/destino detectado durante backfill 037.'),
                    actualizado_en=now(),
                    actualizado_por=NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER
                WHERE id_unidad_agraria=v_unidad;
            END IF;
        END IF;

        UPDATE bien_afectado
        SET id_unidad_agraria=v_unidad,
            actualizado_en=COALESCE(actualizado_en,now()),
            actualizado_por=COALESCE(actualizado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER)
        WHERE id_bien_afectado=r.id_bien_afectado;

        IF NOT EXISTS (
            SELECT 1 FROM afectacion_unidad_agraria au
            WHERE au.id_afectacion=r.id_afectacion
              AND au.id_unidad_agraria=v_unidad
              AND au.activo
        ) THEN
            INSERT INTO afectacion_unidad_agraria (
                id_afectacion,id_unidad_agraria,superficie_preliminar_ha,
                superficie_afectada_ha,superficie_valor_original,
                superficie_formato_origen,fuente,creado_por,observaciones
            ) VALUES (
                r.id_afectacion,v_unidad,r.superficie_preliminar_ha,
                r.superficie_afectada_ha,r.superficie_valor_original,
                r.superficie_formato_origen,COALESCE(r.fuente,'backfill_036'),
                COALESCE(r.creado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER),
                'Backfill desde bien_afectado '||r.id_bien_afectado
            );
        ELSE
            -- No sumar superficies: varias filas legacy pueden ser repeticion del mismo hecho.
            UPDATE afectacion_unidad_agraria
            SET observaciones=concat_ws(E'\n',observaciones,
                    'Bien legacy adicional '||r.id_bien_afectado||' resolvio a la misma unidad; superficie no sumada automaticamente.'),
                actualizado_en=now(),
                actualizado_por=NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER
            WHERE id_afectacion=r.id_afectacion
              AND id_unidad_agraria=v_unidad
              AND activo;
        END IF;
    END LOOP;
END;
$backfill_unidades$;

-- Titulares normalizados desde ParcelaTitular para unidades persona/copropiedad.
INSERT INTO unidad_agraria_titular (
    id_unidad_agraria,id_parcela_titular,porcentaje_participacion,es_principal,
    creado_por,observaciones
)
SELECT u.id_unidad_agraria, pt.id_parcela_titular, pt.porcentaje_participacion,
       row_number() OVER (PARTITION BY u.id_unidad_agraria ORDER BY pt.id_parcela_titular)=1,
       COALESCE(pt.creado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER),
       'Backfill 037 desde parcela_titular.'
FROM unidad_agraria u
JOIN catalogo_operativo ct ON ct.id_catalogo_opcion=u.id_tipo_titularidad
JOIN parcela_titular pt ON pt.id_parcela=u.id_parcela AND pt.activo
WHERE u.activo AND ct.tipo_catalogo='tipo_titularidad_unidad'
  AND ct.codigo IN ('persona','copropiedad')
  AND NOT EXISTS (
      SELECT 1 FROM unidad_agraria_titular ut
      WHERE ut.id_unidad_agraria=u.id_unidad_agraria
        AND ut.id_parcela_titular=pt.id_parcela_titular
        AND ut.activo
  );

-- ---------------------------------------------------------------------------
-- 8. Backfill TIPO COP: un valor inequívoco por Afectacion se migra;
--    conflictos quedan expresamente en revision.
-- ---------------------------------------------------------------------------

WITH cop AS (
    SELECT id_afectacion,
           count(DISTINCT id_tipo_cop_operativo) FILTER (WHERE id_tipo_cop_operativo IS NOT NULL) AS n,
           min(id_tipo_cop_operativo) FILTER (WHERE id_tipo_cop_operativo IS NOT NULL) AS unico
    FROM bien_afectado
    GROUP BY id_afectacion
)
UPDATE afectacion a
SET id_tipo_cop_operativo = cop.unico
FROM cop
WHERE cop.id_afectacion=a.id_afectacion AND cop.n=1;

WITH cop AS (
    SELECT id_afectacion,
           count(DISTINCT id_tipo_cop_operativo) FILTER (WHERE id_tipo_cop_operativo IS NOT NULL) AS n
    FROM bien_afectado
    GROUP BY id_afectacion
)
UPDATE afectacion a
SET tipo_cop_revision_pendiente=TRUE,
    tipo_cop_revision_detalle='Mas de un TIPO COP 036 fue asociado a la misma Afectacion; no se eligio uno automaticamente.'
FROM cop
WHERE cop.id_afectacion=a.id_afectacion AND cop.n>1;

-- ---------------------------------------------------------------------------
-- 9. Backfill alcance TUC en ProyectoNucleo.
-- ---------------------------------------------------------------------------

-- Evidencia positiva: existe bien legacy clasificado explicitamente TUC.
UPDATE proyecto_nucleo pn
SET afecta_tuc=TRUE
WHERE pn.afecta_tuc IS NULL
  AND EXISTS (
      SELECT 1
      FROM afectacion a
      JOIN bien_afectado b ON b.id_afectacion=a.id_afectacion AND b.activo
      JOIN catalogo_operativo c ON c.id_catalogo_opcion=b.id_tipo_gestion
      WHERE a.id_proyecto_nucleo=pn.id_proyecto_nucleo
        AND a.activo
        AND c.tipo_catalogo='tipo_gestion'
        AND c.codigo='TUC'
  );

-- Evidencia negativa legacy sin contradiccion TUC.
UPDATE proyecto_nucleo pn
SET afecta_tuc=FALSE,
    id_motivo_no_afecta_tuc=(
        SELECT id_catalogo_opcion FROM catalogo_operativo
        WHERE tipo_catalogo='motivo_no_afecta_tuc' AND codigo='otro'
    ),
    motivo_no_afecta_tuc_detalle='Backfill desde afectacion.condicion_especial=no_afectacion_uso_comun; revisar motivo especifico.'
WHERE EXISTS (
    SELECT 1 FROM afectacion a
    WHERE a.id_proyecto_nucleo=pn.id_proyecto_nucleo
      AND a.activo
      AND a.condicion_especial='no_afectacion_uso_comun'
)
AND NOT EXISTS (
    SELECT 1
    FROM afectacion a
    JOIN bien_afectado b ON b.id_afectacion=a.id_afectacion AND b.activo
    JOIN catalogo_operativo c ON c.id_catalogo_opcion=b.id_tipo_gestion
    WHERE a.id_proyecto_nucleo=pn.id_proyecto_nucleo
      AND a.activo
      AND c.tipo_catalogo='tipo_gestion'
      AND c.codigo='TUC'
);

-- Contradiccion: existe marca NO TUC y a la vez bienes TUC.
UPDATE proyecto_nucleo pn
SET afecta_tuc=NULL,
    id_motivo_no_afecta_tuc=NULL,
    motivo_no_afecta_tuc_detalle=NULL,
    tuc_revision_pendiente=TRUE,
    tuc_revision_detalle='Contradiccion 037: existe condicion no_afectacion_uso_comun y tambien bienes clasificados TUC; requiere revision funcional.'
WHERE EXISTS (
    SELECT 1 FROM afectacion a
    WHERE a.id_proyecto_nucleo=pn.id_proyecto_nucleo
      AND a.activo
      AND a.condicion_especial='no_afectacion_uso_comun'
)
AND EXISTS (
    SELECT 1
    FROM afectacion a
    JOIN bien_afectado b ON b.id_afectacion=a.id_afectacion AND b.activo
    JOIN catalogo_operativo c ON c.id_catalogo_opcion=b.id_tipo_gestion
    WHERE a.id_proyecto_nucleo=pn.id_proyecto_nucleo
      AND a.activo
      AND c.tipo_catalogo='tipo_gestion'
      AND c.codigo='TUC'
);

COMMENT ON COLUMN afectacion.condicion_especial IS
    'Compatibilidad. no_afectacion_uso_comun deja de ser fuente canónica en 037; usar proyecto_nucleo.afecta_tuc + motivo. Expropiacion/comunidad siguen como contexto de afectacion cuando corresponda.';

-- ---------------------------------------------------------------------------
-- 10. Compatibilidad temporal de nuevas escrituras en bien_afectado 036.
--     Mientras el backend migra al API canónico, cada bien legacy recibe/crea
--     una unidad y proyecta su superficie a afectacion_unidad_agraria.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_037_bien_legacy_preparar_unidad()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_nucleo INTEGER;
    v_tipo_tierra BIGINT;
    v_titularidad BIGINT;
    v_tit_persona BIGINT;
    v_tit_cop BIGINT;
    v_tit_nd BIGINT;
    v_tit_nucleo BIGINT;
    v_tipo_afectacion TEXT;
    v_parcela INTEGER;
    v_count INTEGER;
    v_ref TEXT;
BEGIN
    SELECT pn.id_nucleo,a.tipo_afectacion,COALESCE(NEW.id_parcela,a.id_parcela)
      INTO v_nucleo,v_tipo_afectacion,v_parcela
    FROM afectacion a
    JOIN proyecto_nucleo pn ON pn.id_proyecto_nucleo=a.id_proyecto_nucleo
    WHERE a.id_afectacion=NEW.id_afectacion AND a.activo AND pn.activo;
    IF v_nucleo IS NULL THEN
        RAISE EXCEPTION 'El bien legacy requiere una afectacion activa con ProyectoNucleo activo';
    END IF;

    IF NEW.id_unidad_agraria IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1 FROM unidad_agraria u
            WHERE u.id_unidad_agraria=NEW.id_unidad_agraria
              AND u.id_nucleo=v_nucleo AND u.activo
        ) THEN
            RAISE EXCEPTION 'La unidad agraria del bien legacy debe pertenecer al mismo nucleo';
        END IF;
        RETURN NEW;
    END IF;

    SELECT id_catalogo_opcion INTO v_tipo_tierra
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_tierra' AND codigo='no_determinada';
    SELECT id_catalogo_opcion INTO v_tit_nucleo
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_titularidad_unidad' AND codigo='nucleo_agrario';
    SELECT id_catalogo_opcion INTO v_tit_persona
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_titularidad_unidad' AND codigo='persona';
    SELECT id_catalogo_opcion INTO v_tit_cop
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_titularidad_unidad' AND codigo='copropiedad';
    SELECT id_catalogo_opcion INTO v_tit_nd
    FROM catalogo_operativo WHERE tipo_catalogo='tipo_titularidad_unidad' AND codigo='no_determinada';

    IF v_tipo_afectacion='colectivo' THEN
        v_titularidad:=v_tit_nucleo;
    ELSIF v_parcela IS NOT NULL THEN
        SELECT count(*) INTO v_count FROM parcela_titular WHERE id_parcela=v_parcela AND activo;
        v_titularidad:=CASE WHEN v_count=1 THEN v_tit_persona WHEN v_count>1 THEN v_tit_cop ELSE v_tit_nd END;
    ELSE
        v_titularidad:=v_tit_nd;
    END IF;

    v_ref:=fn_037_normalizar_referencia(NEW.referencia_alfanumerica);

    IF v_parcela IS NOT NULL THEN
        SELECT id_unidad_agraria INTO NEW.id_unidad_agraria
        FROM unidad_agraria
        WHERE id_nucleo=v_nucleo AND id_parcela=v_parcela
          AND id_tipo_titularidad=v_titularidad AND activo
        ORDER BY id_unidad_agraria LIMIT 1;
    ELSIF v_ref IS NOT NULL THEN
        SELECT id_unidad_agraria INTO NEW.id_unidad_agraria
        FROM unidad_agraria
        WHERE id_nucleo=v_nucleo AND id_parcela IS NULL
          AND referencia_normalizada=v_ref
          AND id_tipo_titularidad=v_titularidad AND activo
        ORDER BY id_unidad_agraria LIMIT 1;
    END IF;

    IF NEW.id_unidad_agraria IS NULL THEN
        INSERT INTO unidad_agraria (
            id_nucleo,id_tipo_tierra,id_tipo_gestion,id_destino_superficie,
            id_tipo_titularidad,id_parcela,referencia_alfanumerica,detalle,fuente,
            requiere_revision,motivo_revision,creado_por,observaciones
        ) VALUES (
            v_nucleo,v_tipo_tierra,NEW.id_tipo_gestion,NEW.id_destino_superficie,
            v_titularidad,v_parcela,NEW.referencia_alfanumerica,NEW.detalle,
            COALESCE(NEW.fuente,'compatibilidad_bien_afectado_036'),
            (v_parcela IS NULL AND v_ref IS NULL),
            CASE WHEN v_parcela IS NULL AND v_ref IS NULL
                 THEN 'Unidad creada por compatibilidad 036 sin identificador estable; revisar.' END,
            COALESCE(NEW.creado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER),
            'Creada automaticamente por compatibilidad temporal de bien_afectado.'
        ) RETURNING id_unidad_agraria INTO NEW.id_unidad_agraria;
    END IF;

    -- Completa valores faltantes, pero nunca sobreescribe silenciosamente una
    -- clasificacion canónica distinta: en conflicto marca revision.
    UPDATE unidad_agraria u
    SET id_tipo_gestion=COALESCE(u.id_tipo_gestion,NEW.id_tipo_gestion),
        id_destino_superficie=COALESCE(u.id_destino_superficie,NEW.id_destino_superficie),
        requiere_revision=u.requiere_revision OR
            (u.id_tipo_gestion IS NOT NULL AND NEW.id_tipo_gestion IS NOT NULL AND u.id_tipo_gestion<>NEW.id_tipo_gestion) OR
            (u.id_destino_superficie IS NOT NULL AND NEW.id_destino_superficie IS NOT NULL AND u.id_destino_superficie<>NEW.id_destino_superficie),
        motivo_revision=CASE
            WHEN (u.id_tipo_gestion IS NOT NULL AND NEW.id_tipo_gestion IS NOT NULL AND u.id_tipo_gestion<>NEW.id_tipo_gestion)
              OR (u.id_destino_superficie IS NOT NULL AND NEW.id_destino_superficie IS NOT NULL AND u.id_destino_superficie<>NEW.id_destino_superficie)
            THEN concat_ws(' ',u.motivo_revision,'Conflicto detectado desde escritura legacy bien_afectado.')
            ELSE u.motivo_revision END,
        actualizado_en=now(),
        actualizado_por=COALESCE(NEW.actualizado_por,NEW.creado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER)
    WHERE u.id_unidad_agraria=NEW.id_unidad_agraria;

    -- Si la unidad individual se resolvio a persona/copropiedad, reutiliza
    -- los titulares parcelarios existentes; no crea personas duplicadas.
    IF v_tipo_afectacion='individual' AND v_parcela IS NOT NULL THEN
        INSERT INTO unidad_agraria_titular (
            id_unidad_agraria,id_parcela_titular,porcentaje_participacion,es_principal,
            creado_por,observaciones
        )
        SELECT NEW.id_unidad_agraria,pt.id_parcela_titular,pt.porcentaje_participacion,
               row_number() OVER (ORDER BY pt.id_parcela_titular)=1,
               COALESCE(NEW.creado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER),
               'Sincronizacion temporal desde ParcelaTitular por compatibilidad 036.'
        FROM parcela_titular pt
        WHERE pt.id_parcela=v_parcela AND pt.activo
          AND NOT EXISTS (
              SELECT 1 FROM unidad_agraria_titular ut
              WHERE ut.id_unidad_agraria=NEW.id_unidad_agraria
                AND ut.id_parcela_titular=pt.id_parcela_titular
                AND ut.activo
          );
    END IF;

    RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_037_bien_legacy_preparar_unidad
    BEFORE INSERT OR UPDATE OF id_afectacion,id_tipo_gestion,id_destino_superficie,
        id_parcela,referencia_alfanumerica,id_unidad_agraria
    ON bien_afectado
    FOR EACH ROW EXECUTE FUNCTION fn_037_bien_legacy_preparar_unidad();

CREATE OR REPLACE FUNCTION fn_037_bien_legacy_proyectar()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
DECLARE
    v_count INTEGER;
    v_actual BIGINT;
BEGIN
    IF NEW.activo AND NEW.id_unidad_agraria IS NOT NULL THEN
        SELECT count(*), min(id_afectacion_unidad)
          INTO v_count,v_actual
        FROM afectacion_unidad_agraria
        WHERE id_afectacion=NEW.id_afectacion
          AND id_unidad_agraria=NEW.id_unidad_agraria
          AND activo;

        IF v_count=0 THEN
            INSERT INTO afectacion_unidad_agraria (
                id_afectacion,id_unidad_agraria,superficie_preliminar_ha,
                superficie_afectada_ha,superficie_valor_original,
                superficie_formato_origen,fuente,creado_por,observaciones
            ) VALUES (
                NEW.id_afectacion,NEW.id_unidad_agraria,NEW.superficie_preliminar_ha,
                NEW.superficie_afectada_ha,NEW.superficie_valor_original,
                NEW.superficie_formato_origen,COALESCE(NEW.fuente,'compatibilidad_bien_afectado_036'),
                COALESCE(NEW.creado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER),
                'Proyeccion automatica desde bien_afectado legacy.'
            );
        ELSE
            UPDATE afectacion_unidad_agraria
            SET superficie_preliminar_ha=NEW.superficie_preliminar_ha,
                superficie_afectada_ha=NEW.superficie_afectada_ha,
                superficie_valor_original=NEW.superficie_valor_original,
                superficie_formato_origen=NEW.superficie_formato_origen,
                actualizado_en=now(),
                actualizado_por=COALESCE(NEW.actualizado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER)
            WHERE id_afectacion_unidad=v_actual;
        END IF;

        IF NEW.id_tipo_cop_operativo IS NOT NULL THEN
            UPDATE afectacion
            SET id_tipo_cop_operativo=CASE
                    WHEN id_tipo_cop_operativo IS NULL THEN NEW.id_tipo_cop_operativo
                    ELSE id_tipo_cop_operativo END,
                tipo_cop_revision_pendiente=CASE
                    WHEN id_tipo_cop_operativo IS NOT NULL
                     AND id_tipo_cop_operativo<>NEW.id_tipo_cop_operativo THEN TRUE
                    ELSE tipo_cop_revision_pendiente END,
                tipo_cop_revision_detalle=CASE
                    WHEN id_tipo_cop_operativo IS NOT NULL
                     AND id_tipo_cop_operativo<>NEW.id_tipo_cop_operativo
                    THEN 'Conflicto generado por escritura legacy bien_afectado: mas de un TIPO COP para la misma Afectacion.'
                    ELSE tipo_cop_revision_detalle END,
                actualizado_en=now(),
                actualizado_por=COALESCE(NEW.actualizado_por,NULLIF(current_setting('app.current_user_id',TRUE),'')::INTEGER)
            WHERE id_afectacion=NEW.id_afectacion;
        END IF;
    END IF;
    RETURN NEW;
END;
$fn$;

CREATE TRIGGER trg_037_bien_legacy_proyectar
    AFTER INSERT OR UPDATE OF id_afectacion,id_unidad_agraria,id_tipo_cop_operativo,
        superficie_preliminar_ha,superficie_afectada_ha,superficie_valor_original,
        superficie_formato_origen,activo
    ON bien_afectado
    FOR EACH ROW EXECUTE FUNCTION fn_037_bien_legacy_proyectar();

-- ---------------------------------------------------------------------------
-- 11. Objetivos documentales y trazabilidad: agregar nuevas entidades.
-- ---------------------------------------------------------------------------

ALTER TABLE documento_vinculo DROP CONSTRAINT chk_documento_vinculo_tipo;
ALTER TABLE documento_vinculo ADD CONSTRAINT chk_documento_vinculo_tipo CHECK (entidad_tipo IN (
    'proyecto_nucleo','nucleo_agrario','orv','padron_historial','parcela','afectacion',
    'bien_afectado','unidad_agraria','afectacion_unidad_agraria',
    'asamblea','asamblea_convocatoria','convenio','tramite_ran','tramite_ran_evento',
    'tramite_fifonafe','tramite_fifonafe_evento','indemnizacion','pago','expediente_requisito'
));

CREATE OR REPLACE FUNCTION fn_objetivo_controlado_existe(p_tipo TEXT, p_id BIGINT)
RETURNS BOOLEAN LANGUAGE plpgsql STABLE AS $fn$
DECLARE v_pk TEXT; v_exists BOOLEAN;
BEGIN
    v_pk := CASE p_tipo
        WHEN 'proyecto' THEN 'id_proyecto' WHEN 'proyecto_nucleo' THEN 'id_proyecto_nucleo'
        WHEN 'proyecto_nucleo_referencia' THEN 'id_referencia' WHEN 'proyecto_nucleo_responsable' THEN 'id_responsable'
        WHEN 'nucleo_agrario' THEN 'id_nucleo' WHEN 'persona' THEN 'id_persona'
        WHEN 'orv' THEN 'id_orv' WHEN 'orv_integrante' THEN 'id_orv_integrante'
        WHEN 'padron_historial' THEN 'id_padron' WHEN 'parcela' THEN 'id_parcela'
        WHEN 'parcela_titular' THEN 'id_parcela_titular' WHEN 'actividad_campo' THEN 'id_actividad'
        WHEN 'afectacion' THEN 'id_afectacion' WHEN 'bien_afectado' THEN 'id_bien_afectado'
        WHEN 'unidad_agraria' THEN 'id_unidad_agraria'
        WHEN 'unidad_agraria_titular' THEN 'id_unidad_titular'
        WHEN 'afectacion_unidad_agraria' THEN 'id_afectacion_unidad'
        WHEN 'asamblea' THEN 'id_asamblea' WHEN 'asamblea_convocatoria' THEN 'id_convocatoria'
        WHEN 'convenio' THEN 'id_convenio' WHEN 'tramite_ran' THEN 'id_tramite_ran'
        WHEN 'tramite_ran_evento' THEN 'id_evento_ran' WHEN 'tramite_fifonafe' THEN 'id_tramite_fifonafe'
        WHEN 'tramite_fifonafe_evento' THEN 'id_evento_fifonafe'
        WHEN 'indemnizacion' THEN 'id_indemnizacion' WHEN 'pago' THEN 'id_pago'
        WHEN 'documento' THEN 'id_documento' WHEN 'expediente_requisito' THEN 'id_expediente_requisito'
        WHEN 'importacion_tabular' THEN 'id_importacion_tabular' ELSE NULL END;
    IF v_pk IS NULL OR to_regclass('public.'||p_tipo) IS NULL THEN RETURN FALSE; END IF;
    EXECUTE format('SELECT EXISTS (SELECT 1 FROM %I WHERE %I=$1)',p_tipo,v_pk)
       INTO v_exists USING p_id;
    RETURN v_exists;
END;
$fn$;

-- ---------------------------------------------------------------------------
-- 12. Prohibicion de DELETE fisico para nuevas tablas.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION fn_037_prevenir_delete_fisico()
RETURNS TRIGGER LANGUAGE plpgsql AS $fn$
BEGIN
    RAISE EXCEPTION 'La tabla % no admite DELETE fisico; utilice baja logica',TG_TABLE_NAME;
END;
$fn$;

CREATE TRIGGER trg_037_unidad_no_delete
    BEFORE DELETE ON unidad_agraria
    FOR EACH ROW EXECUTE FUNCTION fn_037_prevenir_delete_fisico();
CREATE TRIGGER trg_037_unidad_titular_no_delete
    BEFORE DELETE ON unidad_agraria_titular
    FOR EACH ROW EXECUTE FUNCTION fn_037_prevenir_delete_fisico();
CREATE TRIGGER trg_037_afectacion_unidad_no_delete
    BEFORE DELETE ON afectacion_unidad_agraria
    FOR EACH ROW EXECUTE FUNCTION fn_037_prevenir_delete_fisico();

-- ---------------------------------------------------------------------------
-- 13. Auditoria y privilegios runtime.
-- ---------------------------------------------------------------------------

CREATE TRIGGER trg_audit_unidad_agraria
    AFTER INSERT OR UPDATE ON unidad_agraria
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_unidad_agraria');
CREATE TRIGGER trg_audit_unidad_agraria_titular
    AFTER INSERT OR UPDATE ON unidad_agraria_titular
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_unidad_titular');
CREATE TRIGGER trg_audit_afectacion_unidad_agraria
    AFTER INSERT OR UPDATE ON afectacion_unidad_agraria
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('id_afectacion_unidad');

GRANT SELECT, INSERT, UPDATE ON unidad_agraria,unidad_agraria_titular,
    afectacion_unidad_agraria TO software_pa_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO software_pa_app;
REVOKE DELETE, TRUNCATE, REFERENCES, TRIGGER ON unidad_agraria,unidad_agraria_titular,
    afectacion_unidad_agraria FROM software_pa_app;
REVOKE INSERT,UPDATE,DELETE,TRUNCATE ON schema_migrations FROM software_pa_app;

INSERT INTO schema_migrations (version,descripcion)
VALUES ('037','Normalizacion de unidad agraria, afectacion y alcance TUC');

COMMIT;
