import React from 'react';
import { Pencil, Plus, UserRoundCheck } from 'lucide-react';
import api from '../api/axios';
import { Empty, Field, Modal, Notice, PageHeader, SubmitBar, UnavailableBajaButton } from '../components/TargetUI';
import { apiMessage } from '../utils/target';

const EMPTY = { nombre: '', apellido_paterno: '', apellido_materno: '', correo: '', rol: 'operador', contrasena: '' };
export default function UserAdministration() {
  const [users, setUsers] = React.useState([]); const [projects, setProjects] = React.useState([]); const [assignments, setAssignments] = React.useState({}); const [modal, setModal] = React.useState(null); const [error, setError] = React.useState(''); const success = '';
  const load = React.useCallback(async () => { try { const [userResponse, projectResponse] = await Promise.all([api.get('/usuarios'), api.get('/proyectos')]); setUsers(userResponse.data); setProjects(projectResponse.data); const entries = await Promise.all(projectResponse.data.map(async (project) => [project.id_proyecto, (await api.get(`/proyectos/${project.id_proyecto}/usuarios`)).data])); setAssignments(Object.fromEntries(entries)); setError(''); } catch (requestError) { setError(apiMessage(requestError)); } }, []);
  React.useEffect(() => { load(); }, [load]);
  return <section><PageHeader eyebrow="RBAC por proyecto" title="Usuarios y accesos" description="Admin tiene acceso global; los demás perfiles sólo operan los proyectos asignados." action={<button className="button" type="button" onClick={() => setModal({ type: 'user' })}><Plus />Nuevo usuario</button>} /><Notice error={error} success={success} />{users.length === 0 ? <Empty /> : <div className="table-wrap card"><table><thead><tr><th>Usuario</th><th>Rol</th><th>Proyectos asignados</th><th>Acciones</th></tr></thead><tbody>{users.map((user) => { const assigned = projects.filter((project) => assignments[project.id_proyecto]?.some((item) => item.id_usuario === user.id_usuario)); return <tr key={user.id_usuario}><td><strong>{user.nombre} {user.apellido_paterno}</strong><small>{user.correo}</small></td><td><span className="pill">{user.rol}</span></td><td>{user.rol === 'admin' ? 'Acceso global' : assigned.length ? assigned.map((item) => item.nombre_proyecto).join(', ') : 'Sin asignación'}</td><td><div className="record-actions"><button className="icon-button" type="button" title="Editar" onClick={() => setModal({ type: 'user', user })}><Pencil /></button>{user.rol !== 'admin' && <button className="icon-button" type="button" title="Asignar proyecto" onClick={() => setModal({ type: 'assignment', user })}><UserRoundCheck /></button>}<UnavailableBajaButton label={`Dar de baja a ${user.nombre}`} /></div></td></tr>; })}</tbody></table></div>}{modal?.type === 'user' && <UserForm current={modal.user} onClose={() => setModal(null)} onDone={async () => { setModal(null); await load(); }} />}{modal?.type === 'assignment' && <AssignmentForm user={modal.user} projects={projects.filter((project) => !assignments[project.id_proyecto]?.some((item) => item.id_usuario === modal.user.id_usuario))} onClose={() => setModal(null)} onDone={async () => { setModal(null); await load(); }} />}</section>;
}

function UserForm({ current, onClose, onDone }) { const [form, setForm] = React.useState(current ? { nombre: current.nombre, apellido_paterno: current.apellido_paterno, apellido_materno: current.apellido_materno || '', correo: current.correo, rol: current.rol, contrasena: '' } : EMPTY); const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState(''); const submit = async (event) => { event.preventDefault(); setSaving(true); try { if (current) await api.patch(`/usuarios/${current.id_usuario}`, { nombre: form.nombre, apellido_paterno: form.apellido_paterno, apellido_materno: form.apellido_materno || null, rol: form.rol }); else await api.post('/usuarios', { ...form, apellido_materno: form.apellido_materno || null }); await onDone(); } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); } }; return <Modal title={current ? 'Editar usuario' : 'Nuevo usuario'} onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={error} /><Field label="Nombre"><input required value={form.nombre} onChange={(e) => setForm({ ...form, nombre: e.target.value })} /></Field><Field label="Apellido paterno"><input required value={form.apellido_paterno} onChange={(e) => setForm({ ...form, apellido_paterno: e.target.value })} /></Field><Field label="Apellido materno"><input value={form.apellido_materno} onChange={(e) => setForm({ ...form, apellido_materno: e.target.value })} /></Field><Field label="Correo"><input type="email" disabled={Boolean(current)} required value={form.correo} onChange={(e) => setForm({ ...form, correo: e.target.value })} /></Field><Field label="Rol"><select value={form.rol} onChange={(e) => setForm({ ...form, rol: e.target.value })}><option value="admin">Administrador</option><option value="operador">Operador</option><option value="visualizador">Visualizador</option><option value="geografo">Geógrafo</option></select></Field>{!current && <Field label="Contraseña temporal" hint="12+ caracteres, mayúscula, minúscula, número y símbolo"><input type="password" autoComplete="new-password" minLength="12" required value={form.contrasena} onChange={(e) => setForm({ ...form, contrasena: e.target.value })} /></Field>}<SubmitBar saving={saving} onCancel={onClose} /></form></Modal>; }
function AssignmentForm({ user, projects, onClose, onDone }) { const [projectId, setProjectId] = React.useState(''); const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState(''); const submit = async (event) => { event.preventDefault(); setSaving(true); try { await api.post(`/proyectos/${projectId}/usuarios`, { id_usuario: user.id_usuario }); await onDone(); } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); } }; return <Modal title={`Asignar proyecto a ${user.nombre}`} onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={error} /><Field label="Proyecto"><select required value={projectId} onChange={(e) => setProjectId(e.target.value)}><option value="">Selecciona</option>{projects.map((project) => <option key={project.id_proyecto} value={project.id_proyecto}>{project.nombre_proyecto}</option>)}</select></Field><SubmitBar saving={saving} onCancel={onClose} label="Asignar" /></form></Modal>; }
