import React from 'react';
import { ArrowLeft, Link2, Pencil, Plus, ReceiptText, WalletCards } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import api from '../api/axios';
import AuthContext from '../contexts/auth-context';
import DocumentsPanel from '../components/DocumentsPanel';
import { Empty, Field, Modal, Notice, PageHeader, SubmitBar, UnavailableBajaButton } from '../components/TargetUI';
import { apiMessage, dateLabel, formatNumber } from '../utils/target';

const AGREEMENT_LABELS = {
  cop_original: 'Convenio de Ocupación Previa',
  modificatorio: 'Convenio Modificatorio',
  superficie_adicional: 'Convenio de Superficie Adicional',
  obras_complementarias: 'Obras Complementarias',
  ampliacion: 'Convenio de Ampliación',
  ampliacion_remanente: 'Convenio de Ampliación - Remanente',
};

export default function AffectationDetail() {
  const { idAfectacion } = useParams();
  const { user } = React.useContext(AuthContext);
  const id = Number(idAfectacion);
  const canCapture = ['admin', 'operador'].includes(user?.rol);
  const [affectation, setAffectation] = React.useState(null);
  const [projectNucleus, setProjectNucleus] = React.useState(null);
  const [agreements, setAgreements] = React.useState([]);
  const [allAffectations, setAllAffectations] = React.useState([]);
  const [assemblies, setAssemblies] = React.useState([]);
  const [fifonafe, setFifonafe] = React.useState([]);
  const [indemnity, setIndemnity] = React.useState(null);
  const [payments, setPayments] = React.useState([]);
  const [parcel, setParcel] = React.useState(null);
  const [holders, setHolders] = React.useState([]);
  const [modal, setModal] = React.useState(null);
  const [error, setError] = React.useState('');
  const [loading, setLoading] = React.useState(true);

  const load = React.useCallback(async () => {
    setLoading(true);
    try {
      const affectationResponse = await api.get(`/afectaciones/${id}`);
      const current = affectationResponse.data;
      const [pn, agreementResponse, affectationsResponse, assemblyResponse, fifonafeResponse, indemnityResponse, parcelResponse] = await Promise.all([
        api.get(`/proyecto-nucleo/${current.id_proyecto_nucleo}`), api.get(`/afectaciones/${id}/convenios`), api.get(`/proyecto-nucleo/${current.id_proyecto_nucleo}/afectaciones`),
        api.get(`/proyecto-nucleo/${current.id_proyecto_nucleo}/asambleas`), api.get(`/proyecto-nucleo/${current.id_proyecto_nucleo}/fifonafe`), api.get(`/afectaciones/${id}/indemnizacion`), api.get(`/proyecto-nucleo/${current.id_proyecto_nucleo}/parcelas`),
      ]);
      const indemnityRecord = indemnityResponse.data;
      let paymentRecords = [];
      if (indemnityRecord) paymentRecords = (await api.get(`/indemnizaciones/${indemnityRecord.id_indemnizacion}/pagos`)).data;
      const parcelRecord = parcelResponse.data.find((item) => item.id_parcela === current.id_parcela) || null;
      const holderRecords = parcelRecord ? (await api.get(`/parcelas/${parcelRecord.id_parcela}/titulares`)).data : [];
      setAffectation(current); setProjectNucleus(pn.data); setAgreements(agreementResponse.data); setAllAffectations(affectationsResponse.data); setAssemblies(assemblyResponse.data); setFifonafe(fifonafeResponse.data.filter((item) => item.afectaciones.some((link) => link.id_afectacion === id))); setIndemnity(indemnityRecord); setPayments(paymentRecords); setParcel(parcelRecord); setHolders(holderRecords); setError('');
    } catch (requestError) { setError(apiMessage(requestError)); }
    finally { setLoading(false); }
  }, [id]);
  React.useEffect(() => { load(); }, [load]);
  const done = async () => { setModal(null); await load(); };
  if (loading && !affectation) return <div className="card">Cargando afectación…</div>;
  if (!affectation) return <Notice error={error || 'Afectación no encontrada'} />;
  const eligibleAdditional = allAffectations.filter((item) => item.tipo_afectacion === affectation.tipo_afectacion && item.id_afectacion !== id);

  return <section>
    <Link className="back-link" to={`/proyecto-nucleo/${affectation.id_proyecto_nucleo}`}><ArrowLeft />Volver al núcleo</Link>
    <PageHeader eyebrow={`${projectNucleus?.nombre_proyecto} · ${projectNucleus?.entidad} · ${projectNucleus?.municipio} · ${projectNucleus?.nombre_nucleo}`} title={`Afectación ${affectation.tipo_afectacion === 'colectivo' ? 'colectiva' : 'individual'}`} description="Convenios, FIFONAFE y cadena financiera derivados desde la afectación canónica." />
    <Notice error={error} />
    <div className="card"><div className="section-heading"><h3>Datos de la afectación</h3>{canCapture && <div className="record-actions"><button className="icon-button" type="button" title="Editar afectación" onClick={() => setModal('afectacion')}><Pencil /></button><UnavailableBajaButton label="Dar de baja afectación" /></div>}</div><dl className="detail-grid"><div><dt>Destino</dt><dd>{affectation.destino_superficie || '—'}</dd></div><div><dt>Parcela / solar</dt><dd>{affectation.no_parcela_solar || '—'}</dd></div><div><dt>Superficie preliminar</dt><dd>{formatNumber(affectation.superficie_preliminar_ha, ' ha')}</dd></div><div><dt>Superficie afectada</dt><dd>{formatNumber(affectation.superficie_afectada_ha, ' ha')}</dd></div><div><dt>Situación</dt><dd>{affectation.situacion || '—'}</dd></div><div><dt>Condición especial</dt><dd>{affectation.condicion_especial || '—'}</dd></div><div><dt>Avalúo</dt><dd>{formatNumber(affectation.avaluo_monto, ' MXN')}</dd></div><div><dt>Referencia de avalúo</dt><dd>{affectation.avaluo_referencia || '—'}</dd></div><div><dt>Institución valuadora</dt><dd>{affectation.avaluo_institucion || '—'}</dd></div><div><dt>Observaciones</dt><dd>{affectation.observaciones || '—'}</dd></div>{affectation.tipo_afectacion === 'individual' && <><div><dt>Tipo de parcela (individual)</dt><dd>{parcel?.tipo_parcela || '—'}</dd></div><div><dt>No. de parcela / PPT</dt><dd>{[parcel?.no_parcela, parcel?.no_parcela_ppt].filter(Boolean).join(' / ') || '—'}</dd></div><div><dt>Persona titular de la parcela</dt><dd>{holders.map((holder) => [holder.nombre, holder.apellido_paterno, holder.apellido_materno].filter(Boolean).join(' ')).join(', ') || '—'}</dd></div><div><dt>Constancia de vigencia de derechos (fecha)</dt><dd>{dateLabel(parcel?.constancia_vigencia_fecha)}</dd></div><div><dt>Certificado parcelario</dt><dd>{parcel?.certificado_parcelario || '—'}</dd></div><div><dt>Folio de derechos</dt><dd>{parcel?.folio_derechos || '—'}</dd></div></>}</dl></div>

    <div className="card"><SectionHead title="Convenios" copy="La creación normal genera convenio y vínculo principal en una sola transacción." action={canCapture ? () => setModal('convenio') : null} label="Nuevo convenio" />
      {agreements.length === 0 ? <Empty title="Sin convenios" /> : <div className="record-list">{agreements.map((agreement) => <article className="record record-expanded" key={agreement.id_convenio}><div><strong>{AGREEMENT_LABELS[agreement.tipo_convenio] || agreement.descripcion_instrumento}</strong><span>{agreement.modalidad_especial ? `${agreement.modalidad_especial} · ` : ''}Firma: {dateLabel(agreement.fecha_firma)} · {formatNumber(agreement.superficie_ha, ' ha')}</span><p>Ingreso RAN: {dateLabel(agreement.ingreso_ran_fecha)} · Inscripción: {dateLabel(agreement.fecha_inscripcion_ran)} · {agreement.afectaciones.length} afectación(es) vinculada(s)</p></div>{canCapture && <div className="record-actions"><button className="icon-button" type="button" title="Editar convenio" onClick={() => setModal({ type: 'convenio', agreement })}><Pencil /></button>{eligibleAdditional.length > 0 && <button className="link-button" type="button" onClick={() => setModal({ type: 'asociacion', agreement })}><Link2 />Asociar otra afectación</button>}<UnavailableBajaButton label="Dar de baja convenio" /></div>}<DocumentsPanel targetType="convenio" targetId={agreement.id_convenio} /></article>)}</div>}
    </div>

    <div className="card"><SectionHead title="FIFONAFE relacionado" copy="El trámite pertenece al ProyectoNucleo y puede cubrir varias afectaciones sin duplicar oficios." />{fifonafe.length === 0 ? <Empty /> : <div className="record-list">{fifonafe.map((item) => <article className="record" key={item.id_tramite_fifonafe}><div><strong>{item.estatus} · {item.ambito}</strong><span>{item.afectaciones.length} afectaciones · {item.hay_conflictos === false ? 'sin conflictos' : item.hay_conflictos === true ? 'con conflictos' : 'conflictos por determinar'} · Acuse: {dateLabel(item.acuse_fifonafe_fecha)}</span></div></article>)}</div>}</div>

    <div className="card"><SectionHead title="Indemnización y pagos" copy="Pago → Indemnización → Afectación → ProyectoNucleo; FIFONAFE no es padre financiero." action={canCapture && !indemnity ? () => setModal('indemnizacion') : canCapture ? () => setModal('pago') : null} label={indemnity ? 'Registrar pago' : 'Crear indemnización'} />
      {!indemnity ? <Empty title="Sin indemnización" /> : <><div className="finance-status"><ReceiptText /><div><strong>{indemnity.estatus}</strong><span>Resolución: {dateLabel(indemnity.fecha_resolucion)} · Entrega SICT–PA: {dateLabel(indemnity.fecha_entrega_expediente_pa)}</span></div><b>{formatNumber(payments.reduce((sum, item) => sum + Number(item.monto), 0), ' MXN pagados')}</b>{canCapture && <button className="icon-button" type="button" title="Editar indemnización" onClick={() => setModal({ type: 'indemnizacion', item: indemnity })}><Pencil /></button>}</div>{payments.length === 0 ? <Empty title="Sin pagos" /> : <div className="record-list">{payments.map((payment) => <article className="record" key={payment.id_pago}><div><strong>{formatNumber(payment.monto, ' MXN')}</strong><span>{dateLabel(payment.fecha_pago)} · {payment.beneficiario_nombre}</span><p>{payment.medio_pago || 'medio no indicado'} · {payment.referencia || 'sin referencia'}</p></div><div className="record-actions"><WalletCards />{canCapture && <button className="icon-button" type="button" title="Editar pago" onClick={() => setModal({ type: 'pago', item: payment })}><Pencil /></button>}<UnavailableBajaButton label="Dar de baja pago" /></div></article>)}</div>}</>}
    </div>
    <DocumentsPanel targetType="afectacion" targetId={id} />

    {modal === 'afectacion' && <AffectationEditForm current={affectation} onClose={() => setModal(null)} onDone={done} />}
    {(modal === 'convenio' || modal?.type === 'convenio') && <AgreementForm affectation={affectation} current={modal.agreement} assemblies={assemblies} agreements={agreements} onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'asociacion' && <AdditionalLinkForm agreement={modal.agreement} candidates={eligibleAdditional} onClose={() => setModal(null)} onDone={done} />}
    {(modal === 'indemnizacion' || modal?.type === 'indemnizacion') && <IndemnityForm affectationId={id} current={modal.item} onClose={() => setModal(null)} onDone={done} />}
    {(modal === 'pago' || modal?.type === 'pago') && <PaymentForm indemnityId={indemnity.id_indemnizacion} current={modal.item} onClose={() => setModal(null)} onDone={done} />}
  </section>;
}

function SectionHead({ title, copy, action, label }) { return <div className="section-heading"><div><h3>{title}</h3><p>{copy}</p></div>{action && <button className="button" type="button" onClick={action}><Plus />{label}</button>}</div>; }

function AffectationEditForm({ current, onClose, onDone }) {
  const [form, setForm] = React.useState({ destino_superficie: current.destino_superficie || '', no_parcela_solar: current.no_parcela_solar || '', superficie_preliminar_ha: current.superficie_preliminar_ha ?? '', superficie_afectada_ha: current.superficie_afectada_ha ?? '', situacion: current.situacion || '', condicion_especial: current.condicion_especial || '', descripcion_condicion: current.descripcion_condicion || '', avaluo_monto: current.avaluo_monto ?? '', avaluo_fecha: current.avaluo_fecha || '', avaluo_referencia: current.avaluo_referencia || '', avaluo_institucion: current.avaluo_institucion || '', observaciones: current.observaciones || '' });
  const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState('');
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); const payload = { ...form, condicion_especial: form.condicion_especial || null, avaluo_fecha: form.avaluo_fecha || null }; ['superficie_preliminar_ha', 'superficie_afectada_ha', 'avaluo_monto'].forEach((key) => { payload[key] = payload[key] === '' ? null : Number(payload[key]); }); try { await api.patch(`/afectaciones/${current.id_afectacion}`, payload); await onDone(); } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); } };
  return <Modal title="Editar afectación" onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={error} /><Field label="Destino de superficie"><input value={form.destino_superficie} onChange={(e) => setForm({ ...form, destino_superficie: e.target.value })} /></Field><Field label="Número de parcela / solar"><input value={form.no_parcela_solar} onChange={(e) => setForm({ ...form, no_parcela_solar: e.target.value })} /></Field><Field label="Superficie preliminar (ha)"><input type="number" min="0" step="0.0001" value={form.superficie_preliminar_ha} onChange={(e) => setForm({ ...form, superficie_preliminar_ha: e.target.value })} /></Field><Field label="Superficie afectada (ha)"><input type="number" min="0" step="0.0001" value={form.superficie_afectada_ha} onChange={(e) => setForm({ ...form, superficie_afectada_ha: e.target.value })} /></Field><Field label="Situación"><input value={form.situacion} onChange={(e) => setForm({ ...form, situacion: e.target.value })} /></Field><Field label="Condición especial"><select value={form.condicion_especial} onChange={(e) => setForm({ ...form, condicion_especial: e.target.value })}><option value="">Ninguna</option><option value="expropiacion_directa">Expropiación directa</option><option value="comunidad_indigena">Comunidad indígena</option><option value="no_afectacion_uso_comun">No afectación de uso común</option><option value="otro">Otra</option></select></Field>{form.condicion_especial === 'otro' && <Field label="Descripción de condición"><textarea required value={form.descripcion_condicion} onChange={(e) => setForm({ ...form, descripcion_condicion: e.target.value })} /></Field>}<Field label="Avalúo"><input type="number" min="0" step="0.01" value={form.avaluo_monto} onChange={(e) => setForm({ ...form, avaluo_monto: e.target.value })} /></Field><Field label="Fecha de avalúo"><input type="date" value={form.avaluo_fecha} onChange={(e) => setForm({ ...form, avaluo_fecha: e.target.value })} /></Field><Field label="Referencia de avalúo"><input value={form.avaluo_referencia} onChange={(e) => setForm({ ...form, avaluo_referencia: e.target.value })} /></Field><Field label="Institución valuadora"><input value={form.avaluo_institucion} onChange={(e) => setForm({ ...form, avaluo_institucion: e.target.value })} /></Field><Field label="Observaciones"><textarea value={form.observaciones} onChange={(e) => setForm({ ...form, observaciones: e.target.value })} /></Field><SubmitBar saving={saving} onCancel={onClose} /></form></Modal>;
}

function AgreementForm({ affectation, current, assemblies, agreements, onClose, onDone }) {
  const typeValues = affectation.tipo_afectacion === 'colectivo' ? ['cop_original', 'modificatorio', 'superficie_adicional', 'obras_complementarias'] : ['cop_original', 'modificatorio', 'ampliacion', 'ampliacion_remanente'];
  const [form, setForm] = React.useState({ tipo_instrumento: current?.tipo_instrumento || 'convenio', tipo_convenio: current?.tipo_convenio || 'cop_original', descripcion_instrumento: current?.descripcion_instrumento || '', modalidad_especial: current?.modalidad_especial || '', descripcion_modalidad: current?.descripcion_modalidad || '', consecutivo: String(current?.consecutivo || 1), id_convenio_padre: current?.id_convenio_padre || '', id_asamblea_autorizacion: current?.id_asamblea_autorizacion || '', fecha_programada_firma: current?.fecha_programada_firma || '', fecha_firma: current?.fecha_firma || '', monto_90: current?.monto_90 ?? '', monto_100: current?.monto_100 ?? '', monto_bdt: current?.monto_bdt ?? '', superficie_ha: current?.superficie_ha ?? '', fecha_programada_ingreso_ran: current?.fecha_programada_ingreso_ran || '', ingreso_ran_fecha: current?.ingreso_ran_fecha || '', numero_solicitud_ingreso: current?.numero_solicitud_ingreso || '', calificacion_registral: current?.calificacion_registral || '', fecha_inscripcion_ran: current?.fecha_inscripcion_ran || '', observaciones: current?.observaciones || '' });
  const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState('');
  const isAgreement = form.tipo_instrumento === 'convenio'; const isCop = form.tipo_convenio === 'cop_original'; const showBdt = form.tipo_convenio !== 'obras_complementarias';
  const submit = async (event) => { event.preventDefault(); setSaving(true); const payload = { ...form, tipo_convenio: isAgreement ? form.tipo_convenio : null, descripcion_instrumento: form.descripcion_instrumento || null, modalidad_especial: isCop ? form.modalidad_especial || null : null, descripcion_modalidad: isCop ? form.descripcion_modalidad || null : null, consecutivo: Number(form.consecutivo), id_convenio_padre: isCop || !isAgreement ? null : form.id_convenio_padre ? Number(form.id_convenio_padre) : null, id_asamblea_autorizacion: form.id_asamblea_autorizacion ? Number(form.id_asamblea_autorizacion) : null }; ['fecha_programada_firma', 'fecha_firma', 'fecha_programada_ingreso_ran', 'ingreso_ran_fecha', 'fecha_inscripcion_ran'].forEach((key) => { payload[key] = payload[key] || null; }); ['monto_90', 'monto_100', 'monto_bdt', 'superficie_ha'].forEach((key) => { payload[key] = payload[key] === '' ? null : Number(payload[key]); }); if (!showBdt) payload.monto_bdt = null; try { if (current) await api.patch(`/convenios/${current.id_convenio}`, payload); else await api.post(`/afectaciones/${affectation.id_afectacion}/convenios`, payload); await onDone(); } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); } };
  return <Modal title={current ? 'Editar convenio' : 'Registrar convenio'} onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={error} />
    <p className="form-context">Ámbito {affectation.tipo_afectacion}. El sistema crea el convenio y su vínculo principal con esta afectación en una sola operación.</p>
    <Field label="Tipo de instrumento"><select value={form.tipo_instrumento} onChange={(event) => setForm({ ...form, tipo_instrumento: event.target.value })}><option value="convenio">Convenio</option><option value="otro">Otro instrumento</option></select></Field>
    {isAgreement ? <Field label="Tipo de convenio"><select value={form.tipo_convenio} onChange={(event) => setForm({ ...form, tipo_convenio: event.target.value })}>{typeValues.map((value) => <option key={value} value={value}>{AGREEMENT_LABELS[value]}</option>)}</select></Field> : <Field label="Descripción del instrumento"><input required value={form.descripcion_instrumento} onChange={(event) => setForm({ ...form, descripcion_instrumento: event.target.value })} /></Field>}
    {isCop && <><Field label="Modalidad especial"><select value={form.modalidad_especial} onChange={(event) => setForm({ ...form, modalidad_especial: event.target.value })}><option value="">Ninguna</option><option value="permuta">Permuta</option><option value="otra">Otra</option></select></Field>{form.modalidad_especial === 'otra' && <Field label="Descripción de modalidad"><input required value={form.descripcion_modalidad} onChange={(event) => setForm({ ...form, descripcion_modalidad: event.target.value })} /></Field>}</>}
    <Field label="Consecutivo"><input type="number" min="1" required value={form.consecutivo} onChange={(event) => setForm({ ...form, consecutivo: event.target.value })} /></Field>
    {isAgreement && !isCop && <Field label="Convenio antecedente"><select value={form.id_convenio_padre} onChange={(event) => setForm({ ...form, id_convenio_padre: event.target.value })}><option value="">Sin antecedente relacionado</option>{agreements.map((item) => <option key={item.id_convenio} value={item.id_convenio}>{AGREEMENT_LABELS[item.tipo_convenio] || item.descripcion_instrumento} · consecutivo {item.consecutivo}</option>)}</select></Field>}
    {affectation.tipo_afectacion === 'colectivo' && <Field label="Asamblea de autorización"><select value={form.id_asamblea_autorizacion} onChange={(event) => setForm({ ...form, id_asamblea_autorizacion: event.target.value })}><option value="">Sin Asamblea relacionada</option>{assemblies.map((item) => <option key={item.id_asamblea} value={item.id_asamblea}>{item.contexto_proceso ? AGREEMENT_LABELS[item.contexto_proceso] || item.contexto_proceso : item.tipo_asamblea} · celebrada {dateLabel(item.fecha_realizada)}</option>)}</select></Field>}
    <h3>Firma y contraprestación</h3>
    <Field label="Fecha programada para firma de convenio"><input type="date" value={form.fecha_programada_firma} onChange={(event) => setForm({ ...form, fecha_programada_firma: event.target.value })} /></Field><Field label="Convenio firmado (fecha)"><input type="date" value={form.fecha_firma} onChange={(event) => setForm({ ...form, fecha_firma: event.target.value })} /></Field><Field label="Convenio monto 90% (MXN)"><input type="number" min="0" step="0.01" value={form.monto_90} onChange={(event) => setForm({ ...form, monto_90: event.target.value })} /></Field><Field label="Convenio monto 100% (MXN)"><input type="number" min="0" step="0.01" value={form.monto_100} onChange={(event) => setForm({ ...form, monto_100: event.target.value })} /></Field>{showBdt && <Field label="Monto BDT (MXN)"><input type="number" min="0" step="0.01" value={form.monto_bdt} onChange={(event) => setForm({ ...form, monto_bdt: event.target.value })} /></Field>}<Field label={form.tipo_convenio === 'superficie_adicional' || form.tipo_convenio?.startsWith('ampliacion') ? 'Superficie de ampliación / adicional (ha)' : 'Superficie total (ha)'}><input type="number" min="0" step="0.0001" value={form.superficie_ha} onChange={(event) => setForm({ ...form, superficie_ha: event.target.value })} /></Field>
    <h3>Seguimiento ante el RAN</h3>
    <Field label="Fecha programada de ingreso al RAN"><input type="date" value={form.fecha_programada_ingreso_ran} onChange={(event) => setForm({ ...form, fecha_programada_ingreso_ran: event.target.value })} /></Field><Field label="Convenio ingresado al RAN (fecha)"><input type="date" value={form.ingreso_ran_fecha} onChange={(event) => setForm({ ...form, ingreso_ran_fecha: event.target.value })} /></Field><Field label="Número de solicitud de ingreso"><input value={form.numero_solicitud_ingreso} onChange={(event) => setForm({ ...form, numero_solicitud_ingreso: event.target.value })} /></Field><Field label="Calificación registral"><textarea value={form.calificacion_registral} onChange={(event) => setForm({ ...form, calificacion_registral: event.target.value })} /></Field><Field label="Convenio inscrito en el RAN (fecha)"><input type="date" value={form.fecha_inscripcion_ran} onChange={(event) => setForm({ ...form, fecha_inscripcion_ran: event.target.value })} /></Field>
    {isCop && <p className="form-context">La superficie, consentimiento, carácter gratuito u oneroso, rescisión, daños, vigencia, contraprestación, modalidad de pago y garantía deben acreditarse en el instrumento y su soporte documental.</p>}
    <Field label="Observaciones / acuerdos"><textarea value={form.observaciones} onChange={(event) => setForm({ ...form, observaciones: event.target.value })} /></Field><SubmitBar saving={saving} onCancel={onClose} label={current ? 'Guardar cambios' : 'Crear convenio'} />
  </form></Modal>;
}



function AdditionalLinkForm({ agreement, candidates, onClose, onDone }) {
  const [id, setId] = React.useState(''); const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState(''); const eligible = candidates.filter((item) => !agreement.afectaciones.some((link) => link.id_afectacion === item.id_afectacion));
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await api.post(`/convenios/${agreement.id_convenio}/afectaciones`, { id_afectacion: Number(id) }); await onDone(); } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); } };
  return <Modal title="Asociar otra afectación" onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={error} /><p className="form-context">Sólo se muestran afectaciones activas del mismo expediente y ámbito.</p><Field label="Afectación adicional"><select required value={id} onChange={(event) => setId(event.target.value)}><option value="">Selecciona</option>{eligible.map((item) => <option key={item.id_afectacion} value={item.id_afectacion}>{item.destino_superficie || item.no_parcela_solar || (item.tipo_afectacion === 'individual' ? 'Afectación individual' : 'Afectación colectiva')}</option>)}</select></Field><SubmitBar saving={saving || eligible.length === 0} onCancel={onClose} label="Asociar" /></form></Modal>;
}

function IndemnityForm({ affectationId, current, onClose, onDone }) {
  const [form, setForm] = React.useState({ estatus: current?.estatus || 'pendiente', descripcion_estatus: current?.descripcion_estatus || '', fecha_programada: current?.fecha_programada || '', fecha_resolucion: current?.fecha_resolucion || '', fecha_entrega_expediente_pa: current?.fecha_entrega_expediente_pa || '', observaciones: current?.observaciones || '' }); const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState('');
  const submit = async (event) => { event.preventDefault(); setSaving(true); const payload = { ...form, descripcion_estatus: form.descripcion_estatus || null, fecha_programada: form.fecha_programada || null, fecha_resolucion: form.fecha_resolucion || null, fecha_entrega_expediente_pa: form.fecha_entrega_expediente_pa || null }; try { if (current) await api.patch(`/indemnizaciones/${current.id_indemnizacion}`, payload); else await api.post(`/afectaciones/${affectationId}/indemnizacion`, payload); await onDone(); } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); } };
  return <Modal title={current ? 'Editar indemnización' : 'Crear indemnización'} onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={error} /><Field label="Estatus"><select value={form.estatus} onChange={(event) => setForm({ ...form, estatus: event.target.value })}><option value="pendiente">Pendiente</option><option value="programado">Programado</option><option value="completo">Completo</option><option value="otro">Otro</option></select></Field>{form.estatus === 'otro' && <Field label="Descripción del estatus"><input required value={form.descripcion_estatus} onChange={(event) => setForm({ ...form, descripcion_estatus: event.target.value })} /></Field>}<Field label="Fecha programada"><input type="date" value={form.fecha_programada} onChange={(event) => setForm({ ...form, fecha_programada: event.target.value })} /></Field><Field label="Fecha de resolución"><input type="date" value={form.fecha_resolucion} onChange={(event) => setForm({ ...form, fecha_resolucion: event.target.value })} /></Field><Field label="Entrega de expediente SICT - Procuraduría Agraria (fecha)"><input type="date" value={form.fecha_entrega_expediente_pa} onChange={(event) => setForm({ ...form, fecha_entrega_expediente_pa: event.target.value })} /></Field><Field label="Observaciones"><textarea value={form.observaciones} onChange={(event) => setForm({ ...form, observaciones: event.target.value })} /></Field><SubmitBar saving={saving} onCancel={onClose} /></form></Modal>;
}

function PaymentForm({ indemnityId, current, onClose, onDone }) { const [form, setForm] = React.useState({ fecha_pago: current?.fecha_pago || '', monto: current?.monto ?? '', beneficiario_nombre: current?.beneficiario_nombre || '', referencia: current?.referencia || '', medio_pago: current?.medio_pago || 'transferencia', observaciones: current?.observaciones || '' }); const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState(''); const submit = async (e) => { e.preventDefault(); setSaving(true); const payload = { ...form, monto: Number(form.monto), referencia: form.referencia || null }; try { if (current) await api.patch(`/pagos/${current.id_pago}`, payload); else await api.post(`/indemnizaciones/${indemnityId}/pagos`, payload); await onDone(); } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); } }; return <Modal title={current ? 'Editar pago' : 'Registrar pago'} onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={error} /><Field label="Fecha de pago"><input required type="date" value={form.fecha_pago} onChange={(e) => setForm({ ...form, fecha_pago: e.target.value })} /></Field><Field label="Monto"><input required type="number" min="0.01" step="0.01" value={form.monto} onChange={(e) => setForm({ ...form, monto: e.target.value })} /></Field><Field label="Beneficiario"><input required value={form.beneficiario_nombre} onChange={(e) => setForm({ ...form, beneficiario_nombre: e.target.value })} /></Field><Field label="Referencia"><input value={form.referencia} onChange={(e) => setForm({ ...form, referencia: e.target.value })} /></Field><Field label="Medio de pago"><select value={form.medio_pago} onChange={(e) => setForm({ ...form, medio_pago: e.target.value })}><option value="transferencia">Transferencia</option><option value="cheque">Cheque</option><option value="efectivo">Efectivo</option><option value="deposito">Depósito</option><option value="otro">Otro</option></select></Field><Field label="Observaciones"><textarea value={form.observaciones} onChange={(e) => setForm({ ...form, observaciones: e.target.value })} /></Field><SubmitBar saving={saving} onCancel={onClose} /></form></Modal>; }
