import React from 'react';
import { ArrowLeft, CalendarDays, ClipboardList, LandPlot, Pencil, Plus, Users } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import api from '../api/axios';
import AuthContext from '../contexts/auth-context';
import DocumentsPanel from '../components/DocumentsPanel';
import { Empty, Field, Modal, Notice, PageHeader, SubmitBar, UnavailableBajaButton } from '../components/TargetUI';
import { apiMessage, dateLabel, formatNumber } from '../utils/target';

const TABS = [
  ['general', 'General'], ['orv_padron', 'ORV y Padrón'], ['actividades', 'Actividades'],
  ['afectacion', 'Afectación'], ['asambleas', 'Asambleas'], ['convenios', 'Convenios'],
  ['fifonafe', 'FIFONAFE'], ['financieros', 'Indemnización y Pagos'], ['documentos', 'Documentos'],
];

const ASSEMBLY_CONTEXT_LABELS = {
  cop_original: 'Convenio de Ocupación Previa',
  modificatorio: 'Convenio Modificatorio',
  superficie_adicional: 'Convenio de Superficie Adicional',
  obras_complementarias: 'Obras Complementarias',
  retiro_fondos: 'Retiro de fondos',
  otro: 'Otro proceso',
};
const ORV_ROLE_OPTIONS = [
  ['COMISARIADO_PRESIDENTE', 'Comisariado · Presidente'],
  ['COMISARIADO_SECRETARIO', 'Comisariado · Secretario'],
  ['COMISARIADO_TESORERO', 'Comisariado · Tesorero'],
  ['CONSEJO_VIGILANCIA_PRESIDENTE', 'Consejo de Vigilancia · Presidente'],
  ['CONSEJO_VIGILANCIA_SECRETARIO1', 'Consejo de Vigilancia · Secretario 1'],
  ['CONSEJO_VIGILANCIA_SECRETARIO2', 'Consejo de Vigilancia · Secretario 2'],
];
const orvRoleLabel = (value) => ORV_ROLE_OPTIONS.find(([key]) => key === value)?.[1] || value?.replaceAll('_', ' ') || 'Cargo no indicado';

export default function ProjectNucleus() {
  const { idProyectoNucleo } = useParams();
  const { user } = React.useContext(AuthContext);
  const id = Number(idProyectoNucleo);
  const canCapture = ['admin', 'operador'].includes(user?.rol);
  const [tab, setTab] = React.useState('general');
  const [data, setData] = React.useState(null);
  const [collections, setCollections] = React.useState({ referencias: [], orv: [], padrones: [], actividades: [], afectaciones: [], asambleas: [], parcelas: [], fifonafe: [] });
  const [modal, setModal] = React.useState(null);
  const [error, setError] = React.useState('');
  const [loading, setLoading] = React.useState(true);

  const load = React.useCallback(async () => {
    setLoading(true);
    try {
      const [summary, references, orv, registers, activities, affectations, assemblies, parcels, fifonafe] = await Promise.all([
        api.get(`/proyecto-nucleo/${id}`), api.get(`/proyecto-nucleo/${id}/referencias`), api.get(`/proyecto-nucleo/${id}/orv`),
        api.get(`/proyecto-nucleo/${id}/padrones`), api.get(`/proyecto-nucleo/${id}/actividades`), api.get(`/proyecto-nucleo/${id}/afectaciones`),
        api.get(`/proyecto-nucleo/${id}/asambleas`), api.get(`/proyecto-nucleo/${id}/parcelas`), api.get(`/proyecto-nucleo/${id}/fifonafe`),
      ]);
      setData(summary.data); setCollections({ referencias: references.data, orv: orv.data, padrones: registers.data, actividades: activities.data, afectaciones: affectations.data, asambleas: assemblies.data, parcelas: parcels.data, fifonafe: fifonafe.data }); setError('');
    } catch (requestError) { setError(apiMessage(requestError)); }
    finally { setLoading(false); }
  }, [id]);
  React.useEffect(() => { load(); }, [load]);
  const done = async () => { setModal(null); await load(); };

  if (loading && !data) return <div className="card">Cargando expediente…</div>;
  if (!data) return <Notice error={error || 'No se encontró el expediente.'} />;
  const activities = (type) => collections.actividades.filter((item) => item.tipo_actividad === type);
  const collective = collections.afectaciones.filter((item) => item.tipo_afectacion === 'colectivo');

  return <section>
    <Link className="back-link" to={`/proyectos?id_proyecto=${data.id_proyecto}`}><ArrowLeft />Volver a núcleos</Link>
    <PageHeader eyebrow={`${data.nombre_proyecto} · ${data.entidad} · ${data.municipio}`} title={data.nombre_nucleo} description={`${data.tipo_nucleo} · Expediente de seguimiento del núcleo agrario`} />
    <div className="breadcrumb context-bar" aria-label="Contexto del expediente"><strong>{data.nombre_proyecto}</strong><span>›</span><span>{data.entidad}</span><span>›</span><span>{data.municipio}</span><span>›</span><strong>{data.nombre_nucleo}</strong></div>
    <Notice error={error} />
    <div className="tabs" role="tablist">{TABS.map(([key, label]) => <button type="button" role="tab" aria-selected={tab === key} className={tab === key ? 'active' : ''} key={key} onClick={() => setTab(key)}>{label}</button>)}</div>

    {tab === 'general' && <div className="stack"><div className="metric-grid"><Metric label="Actividades" value={data.actividades} icon={<CalendarDays />} /><Metric label="Asambleas" value={data.asambleas} icon={<Users />} /><Metric label="Afectaciones colectivas" value={data.afectaciones_colectivas} icon={<ClipboardList />} /><Metric label="Afectaciones individuales" value={data.afectaciones_individuales} icon={<LandPlot />} /><Metric label="Convenios" value={data.convenios} /><Metric label="FIFONAFE" value={data.tramites_fifonafe} /></div><GeneralTab data={data} references={collections.referencias} destinations={collective.map((item) => item.destino_superficie).filter(Boolean)} canCapture={canCapture} onCreate={() => setModal('referencia')} onEdit={() => setModal({ type: 'generales', item: data })} onEditReference={(item) => setModal({ type: 'referencia', item })} /></div>}
    {tab === 'orv_padron' && <div className="stack"><OrvTab items={collections.orv} canCapture={canCapture} onCreate={() => setModal('orv')} onEdit={(item) => setModal({ type: 'orv', item })} onMember={(item) => setModal({ type: 'integrante', item })} onEditMember={(item) => setModal({ type: 'editar_integrante', item })} /><RegisterTab items={collections.padrones} canCapture={canCapture} onCreate={() => setModal('padron')} onEdit={(item) => setModal({ type: 'padron', item })} /></div>}
    {tab === 'actividades' && <div className="stack"><ActivityTab type="sensibilizacion" items={activities('sensibilizacion')} canCapture={canCapture} onCreate={() => setModal({ type: 'actividad', activityType: 'sensibilizacion' })} onEdit={(item) => setModal({ type: 'actividad', activityType: 'sensibilizacion', item })} /><ActivityTab type="caminamiento" items={activities('caminamiento')} canCapture={canCapture} onCreate={() => setModal({ type: 'actividad', activityType: 'caminamiento' })} onEdit={(item) => setModal({ type: 'actividad', activityType: 'caminamiento', item })} /></div>}
    {tab === 'afectacion' && <AffectationWorkspace collective={collective} parcels={collections.parcelas} individual={collections.afectaciones.filter((item) => item.tipo_afectacion === 'individual')} canCapture={canCapture} onCollective={() => setModal('afectacion_colectiva')} onParcel={() => setModal('parcela')} onEditParcel={(item) => setModal({ type: 'parcela', item })} onHolder={(item) => setModal({ type: 'titular', item })} onEditHolder={(item) => setModal({ type: 'editar_titular', item })} onIndividual={(item) => setModal({ type: 'afectacion_individual', item })} />}
    {tab === 'asambleas' && <AssembliesTab items={collections.asambleas} canCapture={canCapture} onCreate={() => setModal('asamblea')} onEdit={(item) => setModal({ type: 'asamblea', item })} />}
    {tab === 'convenios' && <RelatedFactsTab title="Convenios" copy="Abra una afectación para registrar convenios, montos, superficies y seguimiento RAN." affectations={collections.afectaciones} />}
    {tab === 'fifonafe' && <div className="stack"><FifonafeSection items={collections.fifonafe.filter((item) => item.ambito === 'colectivo')} canCapture={canCapture} onCreate={() => setModal({ type: 'fifonafe', scope: 'colectivo' })} onEdit={(item) => setModal({ type: 'fifonafe', scope: 'colectivo', item })} onLink={(item) => setModal({ type: 'vinculo_fifonafe', item })} /><FifonafeSection items={collections.fifonafe.filter((item) => item.ambito === 'individual')} canCapture={canCapture} onCreate={() => setModal({ type: 'fifonafe', scope: 'individual' })} onEdit={(item) => setModal({ type: 'fifonafe', scope: 'individual', item })} onLink={(item) => setModal({ type: 'vinculo_fifonafe', item })} /></div>}
    {tab === 'financieros' && <RelatedFactsTab title="Indemnización y Pagos" copy="Consulte la cadena Pago → Indemnización → Afectación desde cada afectación." affectations={collections.afectaciones} />}
    {tab === 'documentos' && <div className="card"><DocumentsPanel targetType="proyecto_nucleo" targetId={id} /></div>}

    {(modal === 'referencia' || modal?.type === 'referencia') && <ReferenceForm id={id} current={modal?.item} onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'generales' && <GeneralForm id={id} current={modal.item} onClose={() => setModal(null)} onDone={done} />}
    {(modal === 'orv' || modal?.type === 'orv') && <OrvForm id={id} current={modal.item} onClose={() => setModal(null)} onDone={done} />}
    {(modal === 'padron' || modal?.type === 'padron') && <RegisterForm id={id} current={modal.item} onClose={() => setModal(null)} onDone={done} />}
    {modal === 'afectacion_colectiva' && <AffectationForm id={id} scope="colectivo" onClose={() => setModal(null)} onDone={done} />}
    {(modal === 'asamblea' || modal?.type === 'asamblea') && <AssemblyForm id={id} current={modal.item} registers={collections.padrones} onClose={() => setModal(null)} onDone={done} />}
    {(modal === 'parcela' || modal?.type === 'parcela') && <ParcelForm id={id} current={modal.item} onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'actividad' && <ActivityForm id={id} type={modal.activityType} current={modal.item} onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'integrante' && <PersonLinkForm projectId={data.id_proyecto} endpoint={`/orv/${modal.item.id_orv}/integrantes`} roleField="cargo" roleLabel="Cargo" onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'titular' && <PersonLinkForm projectId={data.id_proyecto} endpoint={`/parcelas/${modal.item.id_parcela}/titulares`} roleField="tipo_derecho" roleLabel="Tipo de derecho" onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'editar_integrante' && <RelationEditForm current={modal.item} endpoint={`/orv-integrantes/${modal.item.id_orv_integrante}`} roleField="cargo" roleLabel="Cargo" onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'editar_titular' && <RelationEditForm current={modal.item} endpoint={`/parcela-titulares/${modal.item.id_parcela_titular}`} roleField="tipo_derecho" roleLabel="Tipo de derecho" onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'afectacion_individual' && <AffectationForm id={id} scope="individual" parcel={modal.item} onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'fifonafe' && <FifonafeForm id={id} scope={modal.scope} current={modal.item} affectations={collections.afectaciones.filter((item) => item.tipo_afectacion === modal.scope)} onClose={() => setModal(null)} onDone={done} />}
    {modal?.type === 'vinculo_fifonafe' && <FifonafeLinkForm item={modal.item} affectations={collections.afectaciones} onClose={() => setModal(null)} onDone={done} />}
  </section>;
}

function Metric({ label, value, icon }) { return <article className="metric"><span>{icon}</span><strong>{value ?? 0}</strong><p>{label}</p></article>; }
function SectionHead({ title, copy, canCapture, action, actionLabel }) { return <div className="section-heading"><div><h3>{title}</h3><p>{copy}</p></div>{canCapture && <button className="button" type="button" onClick={action}><Plus />{actionLabel}</button>}</div>; }
function RecordActions({ onEdit, label = 'registro' }) { return <div className="record-actions"><button className="icon-button" type="button" title="Editar" aria-label={`Editar ${label}`} onClick={onEdit}><Pencil /></button><UnavailableBajaButton label={`Dar de baja ${label}`} /></div>; }

function GeneralTab({ data, references, destinations, canCapture, onCreate, onEdit, onEditReference }) { return <div className="card"><SectionHead title="Datos generales" copy="Identificación territorial, responsable agrario y consecutivos del expediente." canCapture={canCapture} action={onCreate} actionLabel="Agregar consecutivo o referencia" />{canCapture && <RecordActions onEdit={onEdit} label="datos generales" />}<dl className="detail-grid"><div><dt>Proyecto</dt><dd>{data.nombre_proyecto}</dd></div><div><dt>Entidad federativa</dt><dd>{data.entidad || '—'}</dd></div><div><dt>Municipio</dt><dd>{data.municipio || '—'}</dd></div><div><dt>Núcleo agrario</dt><dd>{data.nombre_nucleo}</dd></div><div><dt>E/C</dt><dd>{data.tipo_nucleo === 'ejido' ? 'E · Ejido' : data.tipo_nucleo === 'comunidad' ? 'C · Comunidad' : data.tipo_nucleo || '—'}</dd></div><div><dt>Residencia</dt><dd>{data.residencia || '—'}</dd></div><div><dt>Nombre de la persona organizadora agraria responsable</dt><dd>{data.responsable_nombre || '—'}</dd></div><div><dt>Datos de contacto (teléfono)</dt><dd>{data.contacto || '—'}</dd></div><div><dt>Observaciones</dt><dd>{data.observaciones || '—'}</dd></div><div><dt>Destino de la superficie</dt><dd>{[...new Set(destinations)].join(', ') || 'Por registrar en Afectación'}</dd></div></dl><h4>Consecutivos y referencias de fuente</h4>{references.length === 0 ? <Empty title="Sin consecutivos o referencias" /> : <div className="record-list">{references.map((item) => <article className="record" key={item.id_referencia}><div><strong>{item.tipo_referencia === 'consecutivo' ? 'Consecutivo' : item.tipo_referencia.replaceAll('_', ' ')}</strong><span>{item.valor}{item.es_principal ? ' · principal' : ''}</span></div>{canCapture && <RecordActions onEdit={() => onEditReference(item)} label="referencia" />}</article>)}</div>}</div>; }
function OrvTab({ items, canCapture, onCreate, onEdit, onMember, onEditMember }) {
  return <div className="card"><SectionHead title="ORV: órganos de representación y vigilancia" copy="Integración nominal, vigencia y evidencia registral del núcleo agrario." canCapture={canCapture} action={onCreate} actionLabel="Registrar ORV" />
    {items.length === 0 ? <Empty /> : <div className="record-list">{items.map((item) => <article className="record record-expanded" key={item.id_orv}>
      <div><strong>{item.numero_orv ? `ORV ${item.numero_orv}` : 'Órgano de representación y vigilancia'}</strong><span>{item.estado_derivado || 'Estado por determinar'} · Vigencia: {dateLabel(item.inicio_vigencia)} a {dateLabel(item.fin_vigencia)}</span><p>Acta de elección inscrita en el RAN: {item.acta_eleccion_inscrita_ran === true ? 'Sí' : item.acta_eleccion_inscrita_ran === false ? 'No' : 'No disponible'} · {dateLabel(item.fecha_inscripcion_acta_ran)}</p></div>
      {canCapture && <div className="record-actions"><button className="link-button" type="button" onClick={() => onMember(item)}>Agregar integrante</button><RecordActions onEdit={() => onEdit(item)} label="ORV" /></div>}
      <PersonLinks endpoint={`/orv/${item.id_orv}/integrantes`} roleField="cargo" canCapture={canCapture} onEdit={onEditMember} />
      <DocumentsPanel targetType="orv" targetId={item.id_orv} />
    </article>)}</div>}
  </div>;
}

function RegisterTab({ items, canCapture, onCreate, onEdit }) {
  return <div className="card"><SectionHead title="Padrón de ejidatarios / comuneros" copy="Cada corte conserva su fecha, número de sujetos agrarios y soporte documental." canCapture={canCapture} action={onCreate} actionLabel="Nuevo corte" />
    {items.length === 0 ? <Empty /> : <div className="record-list">{items.map((item) => <article className="record record-expanded" key={item.id_padron}>
      <div><strong>{formatNumber(item.numero_ejidatarios_comuneros)} ejidatarios / comuneros</strong><span>Fecha de padrón: {dateLabel(item.fecha_padron)}</span><p>{item.observaciones || 'Sin observaciones'}</p></div>
      {canCapture && <RecordActions onEdit={() => onEdit(item)} label="padrón" />}
      <DocumentsPanel targetType="padron_historial" targetId={item.id_padron} />
    </article>)}</div>}
  </div>;
}

function ActivityTab({ type, items, canCapture, onCreate, onEdit }) { return <div className="card"><SectionHead title={type === 'sensibilizacion' ? 'Sensibilización' : 'Caminamiento'} copy="Actividad común del ProyectoNucleo, sin ciclos ni dependencia de afectación." canCapture={canCapture} action={onCreate} actionLabel="Registrar actividad" />{items.length === 0 ? <Empty title="Sin actividades" /> : <div className="record-list">{items.map((item) => <article className="record" key={item.id_actividad}><div><strong>{item.contexto_actividad.replaceAll('_', ' ')}</strong><span>Programada {dateLabel(item.fecha_programada)} · Realizada {dateLabel(item.fecha_realizada)}</span><p>{item.responsable || 'Sin responsable'} · {item.resultado || item.observaciones || 'Sin resultado capturado'}</p></div>{canCapture && <RecordActions onEdit={() => onEdit(item)} label="actividad" />}</article>)}</div>}</div>; }

function AffectationWorkspace({ collective, parcels, individual, canCapture, onCollective, onParcel, onEditParcel, onHolder, onEditHolder, onIndividual }) { return <div className="stack"><div className="card"><SectionHead title="Afectación colectiva" copy="Tierras de uso común y otros derechos colectivos; no requiere parcela." canCapture={canCapture} action={onCollective} actionLabel="Nueva afectación colectiva" /><AffectationList items={collective} /></div><div className="card"><SectionHead title="Afectación individual" copy="Parte de una parcela y conserva certificado, folio, constancia y titulares nominales." canCapture={canCapture} action={onParcel} actionLabel="Nueva parcela" />{parcels.length === 0 ? <Empty title="Sin parcelas" /> : <div className="record-list">{parcels.map((parcel) => { const affectation = individual.find((item) => item.id_parcela === parcel.id_parcela); return <article className="record" key={parcel.id_parcela}><div><strong>Parcela {parcel.no_parcela || parcel.no_parcela_ppt || 'Sin número registrado'}</strong><span>Certificado parcelario: {parcel.certificado_parcelario || '—'} · Folio de derechos: {parcel.folio_derechos || '—'}</span><p>Constancia de vigencia: {dateLabel(parcel.constancia_vigencia_fecha)} · {parcel.geometria_wkt ? 'Con geometría' : 'Sin geometría (no bloquea)'}</p></div><div className="record-actions">{canCapture && <button className="link-button" type="button" onClick={() => onHolder(parcel)}>Agregar titular</button>}{affectation ? <Link className="link-button" to={`/afectaciones/${affectation.id_afectacion}`}>Abrir afectación individual</Link> : canCapture && <button className="button small" type="button" onClick={() => onIndividual(parcel)}>Crear afectación individual</button>}{canCapture && <RecordActions onEdit={() => onEditParcel(parcel)} label="parcela" />}</div><PersonLinks endpoint={`/parcelas/${parcel.id_parcela}/titulares`} roleField="tipo_derecho" canCapture={canCapture} onEdit={onEditHolder} /></article>; })}</div>}</div></div>; }

function AssembliesTab({ items, canCapture, onCreate, onEdit }) { return <div className="card"><SectionHead title="Asambleas" copy="Tipo jurídico, motivo operativo, convocatorias, padrón relacionado y seguimiento registral ante el RAN." canCapture={canCapture} action={onCreate} actionLabel="Nueva asamblea" />{items.length === 0 ? <Empty title="Sin asambleas" /> : <div className="record-list">{items.map((item) => <article className="record record-expanded" key={item.id_asamblea}><div><strong>{assemblyLabel(item.tipo_asamblea)}</strong><span>{item.contexto_proceso ? `Motivo: ${ASSEMBLY_CONTEXT_LABELS[item.contexto_proceso] || item.contexto_proceso} · ` : ''}Primera convocatoria: {dateLabel(item.fecha_programada_primera)} · Segunda: {dateLabel(item.fecha_programada_segunda)}</span><p>Celebrada: {dateLabel(item.fecha_realizada)} · Ingreso RAN: {dateLabel(item.fecha_ingreso_ran)} · Inscripción: {dateLabel(item.fecha_inscripcion_ran)}</p></div>{canCapture && <RecordActions onEdit={() => onEdit(item)} label="asamblea" />}<DocumentsPanel targetType="asamblea" targetId={item.id_asamblea} /></article>)}</div>}</div>; }

function RelatedFactsTab({ title, copy, affectations }) { return <div className="card"><SectionHead title={title} copy={copy} />{affectations.length === 0 ? <Empty title="Sin afectaciones relacionadas" /> : <div className="record-list">{affectations.map((item) => <Link className="record interactive" to={`/afectaciones/${item.id_afectacion}`} key={item.id_afectacion}><div><strong>{item.tipo_afectacion === 'colectivo' ? 'Colectiva' : 'Individual'} · {item.destino_superficie || item.no_parcela_solar || `Afectación #${item.id_afectacion}`}</strong><span>{formatNumber(item.superficie_afectada_ha, ' ha')} · {item.situacion || 'Sin situación'}</span></div><span>Abrir seguimiento →</span></Link>)}</div>}</div>; }

function assemblyLabel(value) { return ({ anuencia: 'Asamblea de anuencia', modificatorio: 'Asamblea para convenio modificatorio', superficie_adicional: 'Asamblea de superficie adicional', obras_complementarias: 'Asamblea de obras complementarias', retiro_fondos: 'Asamblea de retiro de fondos', otra: 'Otra asamblea' })[value] || value; }

function CollectiveTab({ affectations, assemblies, fifonafe, canCapture, onAffectation, onAssembly, onEditAssembly, onFifonafe, onEditFifonafe, onLinkFifonafe }) { return <div className="stack"><div className="card"><SectionHead title="Afectaciones colectivas" copy="Superficies administrativas sin geometría y sin parcela." canCapture={canCapture} action={onAffectation} actionLabel="Nueva afectación" /><AffectationList items={affectations} /></div><div className="card"><SectionHead title="Asambleas del núcleo" copy="Hechos colectivos compartibles por varios convenios del expediente." canCapture={canCapture} action={onAssembly} actionLabel="Nueva asamblea" />{assemblies.length === 0 ? <Empty /> : <div className="record-list">{assemblies.map((item) => <article className="record" key={item.id_asamblea}><div><strong>{item.tipo_asamblea.replaceAll('_', ' ')}</strong><span>{dateLabel(item.fecha_realizada)} · RAN {dateLabel(item.fecha_inscripcion_ran)}</span><p>{item.proposito || 'Sin propósito capturado'} · {item.resultado || 'sin resultado'}</p></div>{canCapture && <RecordActions onEdit={() => onEditAssembly(item)} label="asamblea" />}</article>)}</div>}</div><FifonafeSection items={fifonafe} canCapture={canCapture} onCreate={onFifonafe} onEdit={onEditFifonafe} onLink={onLinkFifonafe} /></div>; }
function AffectationList({ items }) { return items.length === 0 ? <Empty /> : <div className="record-list">{items.map((item) => <Link className="record interactive" to={`/afectaciones/${item.id_afectacion}`} key={item.id_afectacion}><div><strong>{item.destino_superficie || `Afectación #${item.id_afectacion}`}</strong><span>{formatNumber(item.superficie_afectada_ha, ' ha')} · {item.situacion || 'sin situación'}</span><p>Avalúo: {formatNumber(item.avaluo_monto, ' MXN')}</p></div><span>Abrir expediente financiero →</span></Link>)}</div>; }
function FifonafeSection({ items, canCapture, onCreate, onEdit, onLink }) { return <div className="card"><SectionHead title="FIFONAFE" copy="Un trámite conserva sus cuatro oficios y puede cubrir varias afectaciones del mismo ámbito." canCapture={canCapture} action={onCreate} actionLabel="Nuevo trámite" />{items.length === 0 ? <Empty /> : <div className="record-list">{items.map((item) => <article className="record record-expanded" key={item.id_tramite_fifonafe}><div><strong>{item.ambito} · {item.estatus}</strong><span>{item.afectaciones.length} afectación(es) · {item.hay_conflictos === false ? 'Sin conflictos' : item.hay_conflictos === true ? 'Con conflictos' : 'Conflictos por determinar'}</span><p>Acuse: {dateLabel(item.acuse_fifonafe_fecha)} · Oficios: {[item.no_oficio_fifonafe_a_dgaopr, item.no_oficio_dgaopr_a_representacion, item.no_oficio_respuesta_representacion_a_dgaopr, item.no_oficio_respuesta_dgaopr_a_fifonafe].filter(Boolean).length}/4 · {item.resultado_no_conflictos || 'sin resultado'}</p></div>{canCapture && <div className="record-actions"><button className="link-button" type="button" onClick={() => onLink(item)}>Asociar otra afectación</button><RecordActions onEdit={() => onEdit(item)} label="trámite FIFONAFE" /></div>}<DocumentsPanel targetType="tramite_fifonafe" targetId={item.id_tramite_fifonafe} /></article>)}</div>}</div>; }

function ParcelTab({ parcels, affectations, fifonafe, canCapture, onParcel, onEditParcel, onHolder, onEditHolder, onAffectation, onFifonafe, onEditFifonafe, onLinkFifonafe }) { return <div className="stack"><div className="card"><SectionHead title="Parcelas y derechos individuales" copy="La geometría es opcional y su ausencia no bloquea captura administrativa." canCapture={canCapture} action={onParcel} actionLabel="Nueva parcela" />{parcels.length === 0 ? <Empty title="Sin parcelas" /> : <div className="record-list">{parcels.map((parcel) => { const affectation = affectations.find((item) => item.id_parcela === parcel.id_parcela); return <article className="record" key={parcel.id_parcela}><div><strong>Parcela {parcel.no_parcela || parcel.no_parcela_ppt || 'Sin número registrado'}</strong><span>{parcel.tipo_parcela} · Certificado {parcel.certificado_parcelario || '—'} · Folio {parcel.folio_derechos || '—'} · {parcel.geometria_wkt ? 'con geometría' : 'sin geometría'}</span></div><div className="record-actions">{canCapture && <button className="link-button" type="button" onClick={() => onHolder(parcel)}>Agregar titular</button>}{affectation ? <Link className="link-button" to={`/afectaciones/${affectation.id_afectacion}`}>Abrir afectación</Link> : canCapture && <button className="button small" type="button" onClick={() => onAffectation(parcel)}>Crear afectación</button>}{canCapture && <RecordActions onEdit={() => onEditParcel(parcel)} label="parcela" />}</div><PersonLinks endpoint={`/parcelas/${parcel.id_parcela}/titulares`} roleField="tipo_derecho" canCapture={canCapture} onEdit={onEditHolder} /></article>; })}</div>}</div><FifonafeSection items={fifonafe} canCapture={canCapture} onCreate={onFifonafe} onEdit={onEditFifonafe} onLink={onLinkFifonafe} /></div>; }

function useSubmit(endpoint, onDone, method = 'post') { const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState(''); const submit = async (payload) => { setSaving(true); setError(''); try { await api.request({ method, url: endpoint, data: payload }); await onDone(); } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); } }; return { submit, saving, error }; }
function GeneralForm({ id, current, onClose, onDone }) { const [form, setForm] = React.useState({ residencia: current.residencia || '', responsable_nombre: current.responsable_nombre || '', contacto: current.contacto || '', observaciones: current.observaciones || '' }); const state = useSubmit(`/proyecto-nucleo/${id}`, onDone, 'patch'); return <Modal title="Editar datos generales" onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); state.submit(form); }}><Notice error={state.error} /><Field label="Residencia"><input value={form.residencia} onChange={(e) => setForm({ ...form, residencia: e.target.value })} /></Field><Field label="Responsable"><input value={form.responsable_nombre} onChange={(e) => setForm({ ...form, responsable_nombre: e.target.value })} /></Field><Field label="Contacto"><input value={form.contacto} onChange={(e) => setForm({ ...form, contacto: e.target.value })} /></Field><Field label="Observaciones"><textarea value={form.observaciones} onChange={(e) => setForm({ ...form, observaciones: e.target.value })} /></Field><SubmitBar saving={state.saving} onCancel={onClose} /></form></Modal>; }
function ReferenceForm({ id, current, onClose, onDone }) { const [form, setForm] = React.useState({ tipo_referencia: current?.tipo_referencia || 'consecutivo', valor: current?.valor || '', es_principal: current?.es_principal || false }); const state = useSubmit(current ? `/referencias/${current.id_referencia}` : `/proyecto-nucleo/${id}/referencias`, onDone, current ? 'patch' : 'post'); return <Modal title={current ? 'Editar referencia histórica' : 'Agregar referencia histórica'} onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); const payload = current ? { valor: form.valor, es_principal: form.es_principal } : form; state.submit(payload); }}><Notice error={state.error} /><Field label="Tipo"><select disabled={Boolean(current)} value={form.tipo_referencia} onChange={(e) => setForm({ ...form, tipo_referencia: e.target.value })}><option value="consecutivo">Consecutivo</option><option value="clave_tramo">Clave histórica</option><option value="numero_tramo">Número histórico</option><option value="otro">Otra</option></select></Field><Field label="Valor"><input required value={form.valor} onChange={(e) => setForm({ ...form, valor: e.target.value })} /></Field><label className="checkbox"><input type="checkbox" checked={form.es_principal} onChange={(e) => setForm({ ...form, es_principal: e.target.checked })} />Referencia principal activa</label><SubmitBar saving={state.saving} onCancel={onClose} /></form></Modal>; }
function OrvForm({ id, current, onClose, onDone }) { const [form, setForm] = React.useState({ numero_orv: current?.numero_orv || '', inicio_vigencia: current?.inicio_vigencia || '', fin_vigencia: current?.fin_vigencia || '', estatus_fuente: current?.estatus_fuente || '', acta_eleccion_inscrita_ran: current?.acta_eleccion_inscrita_ran ?? false, fecha_inscripcion_acta_ran: current?.fecha_inscripcion_acta_ran || '', observaciones: current?.observaciones || '' }); const state = useSubmit(current ? `/orv/${current.id_orv}` : `/proyecto-nucleo/${id}/orv`, onDone, current ? 'patch' : 'post'); return <Modal title={current ? 'Editar ORV' : 'Registrar ORV'} onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); state.submit({ ...form, inicio_vigencia: form.inicio_vigencia || null, fin_vigencia: form.fin_vigencia || null, fecha_inscripcion_acta_ran: form.fecha_inscripcion_acta_ran || null }); }}><Notice error={state.error} /><Field label="Número ORV"><input value={form.numero_orv} onChange={(e) => setForm({ ...form, numero_orv: e.target.value })} /></Field><Field label="Inicio de vigencia"><input type="date" value={form.inicio_vigencia} onChange={(e) => setForm({ ...form, inicio_vigencia: e.target.value })} /></Field><Field label="Fin de vigencia"><input type="date" value={form.fin_vigencia} onChange={(e) => setForm({ ...form, fin_vigencia: e.target.value })} /></Field><Field label="Estatus de fuente"><input value={form.estatus_fuente} onChange={(e) => setForm({ ...form, estatus_fuente: e.target.value })} /></Field><label className="checkbox"><input type="checkbox" checked={form.acta_eleccion_inscrita_ran} onChange={(e) => setForm({ ...form, acta_eleccion_inscrita_ran: e.target.checked })} />Acta inscrita en RAN</label><Field label="Fecha de inscripción del acta"><input type="date" value={form.fecha_inscripcion_acta_ran} onChange={(e) => setForm({ ...form, fecha_inscripcion_acta_ran: e.target.value })} /></Field><Field label="Observaciones"><textarea value={form.observaciones} onChange={(e) => setForm({ ...form, observaciones: e.target.value })} /></Field><SubmitBar saving={state.saving} onCancel={onClose} /></form></Modal>; }
function RegisterForm({ id, current, onClose, onDone }) { const [form, setForm] = React.useState({ fecha_padron: current?.fecha_padron || '', numero_ejidatarios_comuneros: current?.numero_ejidatarios_comuneros ?? '', observaciones: current?.observaciones || '' }); const state = useSubmit(current ? `/padrones/${current.id_padron}` : `/proyecto-nucleo/${id}/padrones`, onDone, current ? 'patch' : 'post'); return <Modal title={current ? 'Editar corte de padrón' : 'Registrar corte de padrón'} onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); state.submit({ fecha_padron: form.fecha_padron || null, numero_ejidatarios_comuneros: form.numero_ejidatarios_comuneros === '' ? null : Number(form.numero_ejidatarios_comuneros), observaciones: form.observaciones || null }); }}><Notice error={state.error} /><Field label="Fecha"><input type="date" value={form.fecha_padron} onChange={(e) => setForm({ ...form, fecha_padron: e.target.value })} /></Field><Field label="Ejidatarios / comuneros"><input type="number" min="0" value={form.numero_ejidatarios_comuneros} onChange={(e) => setForm({ ...form, numero_ejidatarios_comuneros: e.target.value })} /></Field><Field label="Observaciones"><textarea value={form.observaciones} onChange={(e) => setForm({ ...form, observaciones: e.target.value })} /></Field><SubmitBar saving={state.saving} onCancel={onClose} /></form></Modal>; }
function ActivityForm({ id, type, current, onClose, onDone }) { const [form, setForm] = React.useState({ contexto_actividad: current?.contexto_actividad || 'general', fecha_programada: current?.fecha_programada || '', fecha_realizada: current?.fecha_realizada || '', responsable: current?.responsable || '', resultado: current?.resultado || '', observaciones: current?.observaciones || '' }); const state = useSubmit(current ? `/actividades/${current.id_actividad}` : `/proyecto-nucleo/${id}/actividades`, onDone, current ? 'patch' : 'post'); return <Modal title={`${current ? 'Editar' : 'Registrar'} ${type}`} onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); state.submit({ tipo_actividad: type, ...form, fecha_programada: form.fecha_programada || null, fecha_realizada: form.fecha_realizada || null }); }}><Notice error={state.error} /><Field label="Contexto"><select value={form.contexto_actividad} onChange={(e) => setForm({ ...form, contexto_actividad: e.target.value })}><option value="general">General</option><option value="superficie_adicional">Superficie adicional</option><option value="obras_complementarias">Obras complementarias</option><option value="otro">Otro</option></select></Field><Field label="Fecha programada"><input type="date" value={form.fecha_programada} onChange={(e) => setForm({ ...form, fecha_programada: e.target.value })} /></Field><Field label="Fecha realizada"><input type="date" value={form.fecha_realizada} onChange={(e) => setForm({ ...form, fecha_realizada: e.target.value })} /></Field><Field label="Responsable"><input value={form.responsable} onChange={(e) => setForm({ ...form, responsable: e.target.value })} /></Field><Field label="Resultado"><textarea value={form.resultado} onChange={(e) => setForm({ ...form, resultado: e.target.value })} /></Field><Field label="Observaciones"><textarea value={form.observaciones} onChange={(e) => setForm({ ...form, observaciones: e.target.value })} /></Field><SubmitBar saving={state.saving} onCancel={onClose} /></form></Modal>; }
function AffectationForm({ id, scope, parcel, onClose, onDone }) { const [form, setForm] = React.useState({ destino_superficie: '', superficie_preliminar_ha: '', superficie_afectada_ha: '', situacion: '', avaluo_monto: '', avaluo_fecha: '', avaluo_referencia: '', avaluo_institucion: '' }); const state = useSubmit(`/proyecto-nucleo/${id}/afectaciones`, onDone); return <Modal title={`Nueva afectación ${scope}`} onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); const payload = { tipo_afectacion: scope, id_parcela: parcel?.id_parcela || null, ...form }; ['superficie_preliminar_ha', 'superficie_afectada_ha', 'avaluo_monto'].forEach((key) => { payload[key] = payload[key] === '' ? null : Number(payload[key]); }); payload.avaluo_fecha = payload.avaluo_fecha || null; state.submit(payload); }}><Notice error={state.error} />{parcel && <p className="form-context">Parcela {parcel.no_parcela || parcel.id_parcela} · la geometría no es requisito</p>}<Field label="Destino de superficie"><select value={form.destino_superficie} onChange={(e) => setForm({ ...form, destino_superficie: e.target.value })}><option value="">Selecciona</option><option value="tierras_uso_comun">Tierras de uso común</option><option value="parcela_escolar">Parcela escolar</option><option value="solar">Solar</option><option value="otro">Otro</option></select></Field><Field label="Superficie preliminar (ha)"><input type="number" step="0.0001" min="0" value={form.superficie_preliminar_ha} onChange={(e) => setForm({ ...form, superficie_preliminar_ha: e.target.value })} /></Field><Field label="Superficie afectada (ha)"><input type="number" step="0.0001" min="0" value={form.superficie_afectada_ha} onChange={(e) => setForm({ ...form, superficie_afectada_ha: e.target.value })} /></Field><Field label="Situación"><input value={form.situacion} onChange={(e) => setForm({ ...form, situacion: e.target.value })} /></Field><Field label="Avalúo"><input type="number" step="0.01" min="0" value={form.avaluo_monto} onChange={(e) => setForm({ ...form, avaluo_monto: e.target.value })} /></Field><Field label="Fecha de avalúo"><input type="date" value={form.avaluo_fecha} onChange={(e) => setForm({ ...form, avaluo_fecha: e.target.value })} /></Field><Field label="Referencia de avalúo"><input value={form.avaluo_referencia} onChange={(e) => setForm({ ...form, avaluo_referencia: e.target.value })} /></Field><Field label="Institución"><input value={form.avaluo_institucion} onChange={(e) => setForm({ ...form, avaluo_institucion: e.target.value })} /></Field><SubmitBar saving={state.saving} onCancel={onClose} label="Crear afectación" /></form></Modal>; }
function AssemblyForm({ id, current, registers, onClose, onDone }) {
  const currentLegacyType = ['modificatorio', 'superficie_adicional', 'obras_complementarias'].includes(current?.tipo_asamblea);
  const [form, setForm] = React.useState({
    tipo_asamblea: currentLegacyType ? 'anuencia' : current?.tipo_asamblea || 'anuencia',
    contexto_proceso: current?.contexto_proceso || (currentLegacyType ? current.tipo_asamblea : current?.tipo_asamblea === 'retiro_fondos' ? 'retiro_fondos' : 'cop_original'),
    id_padron: current?.id_padron || '', proposito: current?.proposito || '',
    fecha_expedicion_primera: current?.fecha_expedicion_primera || '', fecha_programada_primera: current?.fecha_programada_primera || '',
    fecha_expedicion_segunda: current?.fecha_expedicion_segunda || '', fecha_programada_segunda: current?.fecha_programada_segunda || '',
    fecha_realizada: current?.fecha_realizada || '', resultado: current?.resultado || '',
    fecha_programada_ingreso_ran: current?.fecha_programada_ingreso_ran || '', fecha_ingreso_ran: current?.fecha_ingreso_ran || '',
    numero_solicitud_ran: current?.numero_solicitud_ran || '', calificacion_registral_ran: current?.calificacion_registral_ran || '',
    fecha_inscripcion_ran: current?.fecha_inscripcion_ran || '', observaciones: current?.observaciones || '',
  });
  const state = useSubmit(current ? `/asambleas/${current.id_asamblea}` : `/proyecto-nucleo/${id}/asambleas`, onDone, current ? 'patch' : 'post');
  const submit = (event) => {
    event.preventDefault();
    const payload = { ...form, id_padron: form.id_padron ? Number(form.id_padron) : null, contexto_proceso: form.contexto_proceso || null };
    ['fecha_expedicion_primera', 'fecha_programada_primera', 'fecha_expedicion_segunda', 'fecha_programada_segunda', 'fecha_realizada', 'fecha_programada_ingreso_ran', 'fecha_ingreso_ran', 'fecha_inscripcion_ran'].forEach((key) => { payload[key] = payload[key] || null; });
    state.submit(payload);
  };
  return <Modal title={current ? 'Editar asamblea' : 'Registrar asamblea'} onClose={onClose}><form className="form-grid" onSubmit={submit}>
    <Notice error={state.error} />
    <p className="form-context">El tipo jurídico de la Asamblea se registra separado del convenio o proceso que la motiva.</p>
    <Field label="Tipo de Asamblea"><select value={form.tipo_asamblea} onChange={(event) => { const type = event.target.value; setForm({ ...form, tipo_asamblea: type, contexto_proceso: type === 'retiro_fondos' ? 'retiro_fondos' : form.contexto_proceso }); }}><option value="anuencia">Asamblea de anuencia</option><option value="retiro_fondos">Asamblea de retiro de fondos</option><option value="otra">Otra Asamblea</option></select></Field>
    <Field label="Motivo / contexto del proceso"><select value={form.contexto_proceso} onChange={(event) => setForm({ ...form, contexto_proceso: event.target.value })}><option value="cop_original">Convenio de Ocupación Previa</option><option value="modificatorio">Convenio Modificatorio</option><option value="superficie_adicional">Convenio de Superficie Adicional</option><option value="obras_complementarias">Obras Complementarias</option><option value="retiro_fondos">Retiro de fondos</option><option value="otro">Otro proceso</option></select></Field>
    <Field label="Padrón relacionado"><select value={form.id_padron} onChange={(event) => setForm({ ...form, id_padron: event.target.value })}><option value="">Sin relación</option>{registers.map((item) => <option key={item.id_padron} value={item.id_padron}>{dateLabel(item.fecha_padron)} · {item.numero_ejidatarios_comuneros} sujetos</option>)}</select></Field>
    <Field label="Propósito"><textarea value={form.proposito} onChange={(event) => setForm({ ...form, proposito: event.target.value })} /></Field>
    <h3>Convocatorias y celebración</h3>
    <Field label="Fecha de expedición de 1a convocatoria"><input type="date" value={form.fecha_expedicion_primera} onChange={(event) => setForm({ ...form, fecha_expedicion_primera: event.target.value })} /></Field>
    <Field label="Asamblea programada 1a (fecha)"><input type="date" value={form.fecha_programada_primera} onChange={(event) => setForm({ ...form, fecha_programada_primera: event.target.value })} /></Field>
    <Field label="Fecha de expedición de 2a convocatoria"><input type="date" value={form.fecha_expedicion_segunda} onChange={(event) => setForm({ ...form, fecha_expedicion_segunda: event.target.value })} /></Field>
    <Field label="Asamblea programada 2a (fecha)"><input type="date" value={form.fecha_programada_segunda} onChange={(event) => setForm({ ...form, fecha_programada_segunda: event.target.value })} /></Field>
    <Field label="Asamblea realizada (fecha)"><input type="date" value={form.fecha_realizada} onChange={(event) => setForm({ ...form, fecha_realizada: event.target.value })} /></Field>
    <Field label="Resultado / anuencia"><input value={form.resultado} onChange={(event) => setForm({ ...form, resultado: event.target.value })} /></Field>
    <h3>Seguimiento ante el RAN</h3>
    <Field label="Fecha programada de ingreso al RAN"><input type="date" value={form.fecha_programada_ingreso_ran} onChange={(event) => setForm({ ...form, fecha_programada_ingreso_ran: event.target.value })} /></Field>
    <Field label="Ingresado al RAN (fecha)"><input type="date" value={form.fecha_ingreso_ran} onChange={(event) => setForm({ ...form, fecha_ingreso_ran: event.target.value })} /></Field>
    <Field label="Número de solicitud de ingreso"><input value={form.numero_solicitud_ran} onChange={(event) => setForm({ ...form, numero_solicitud_ran: event.target.value })} /></Field>
    <Field label="Calificación registral"><textarea value={form.calificacion_registral_ran} onChange={(event) => setForm({ ...form, calificacion_registral_ran: event.target.value })} /></Field>
    <Field label="Acta inscrita en el RAN (fecha)"><input type="date" value={form.fecha_inscripcion_ran} onChange={(event) => setForm({ ...form, fecha_inscripcion_ran: event.target.value })} /></Field>
    <Field label="Observaciones"><textarea value={form.observaciones} onChange={(event) => setForm({ ...form, observaciones: event.target.value })} /></Field>
    <SubmitBar saving={state.saving} onCancel={onClose} />
  </form></Modal>;
}

function ParcelForm({ id, current, onClose, onDone }) { const [form, setForm] = React.useState({ tipo_parcela: current?.tipo_parcela || 'individual', no_parcela: current?.no_parcela || '', no_parcela_ppt: current?.no_parcela_ppt || '', certificado_parcelario: current?.certificado_parcelario || '', folio_derechos: current?.folio_derechos || '', constancia_vigencia_fecha: current?.constancia_vigencia_fecha || '', observaciones: current?.observaciones || '' }); const state = useSubmit(current ? `/parcelas/${current.id_parcela}` : `/proyecto-nucleo/${id}/parcelas`, onDone, current ? 'patch' : 'post'); return <Modal title={current ? 'Editar parcela' : 'Nueva parcela'} onClose={onClose}><form className="form-grid" onSubmit={(e) => { e.preventDefault(); state.submit({ ...form, constancia_vigencia_fecha: form.constancia_vigencia_fecha || null }); }}><Notice error={state.error} /><p className="form-context">La geometría es opcional y se gestiona por el perfil geográfico.</p><Field label="Tipo"><select value={form.tipo_parcela} onChange={(e) => setForm({ ...form, tipo_parcela: e.target.value })}><option value="individual">Individual</option><option value="copropiedad">Copropiedad</option><option value="otro">Otro</option><option value="no_determinado">No determinado</option></select></Field><Field label="Número de parcela"><input value={form.no_parcela} onChange={(e) => setForm({ ...form, no_parcela: e.target.value })} /></Field><Field label="Número PPT"><input value={form.no_parcela_ppt} onChange={(e) => setForm({ ...form, no_parcela_ppt: e.target.value })} /></Field><Field label="Certificado parcelario"><input value={form.certificado_parcelario} onChange={(e) => setForm({ ...form, certificado_parcelario: e.target.value })} /></Field><Field label="Folio de derechos"><input value={form.folio_derechos} onChange={(e) => setForm({ ...form, folio_derechos: e.target.value })} /></Field><Field label="Constancia de vigencia"><input type="date" value={form.constancia_vigencia_fecha} onChange={(e) => setForm({ ...form, constancia_vigencia_fecha: e.target.value })} /></Field><Field label="Observaciones"><textarea value={form.observaciones} onChange={(e) => setForm({ ...form, observaciones: e.target.value })} /></Field><SubmitBar saving={state.saving} onCancel={onClose} /></form></Modal>; }
function PersonLinkForm({ projectId, endpoint, roleField, roleLabel, onClose, onDone }) {
  const [form, setForm] = React.useState({ nombre: '', apellido_paterno: '', apellido_materno: '', role: '' });
  const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState('');
  const submit = async (event) => {
    event.preventDefault(); setSaving(true);
    try {
      const person = (await api.post(`/proyectos/${projectId}/personas`, { nombre: form.nombre, apellido_paterno: form.apellido_paterno || null, apellido_materno: form.apellido_materno || null, datos_identidad_incompletos: true, origen_registro: 'captura_sistema' })).data;
      await api.post(endpoint, { id_persona: person.id_persona, [roleField]: form.role }); await onDone();
    } catch (requestError) { setError(apiMessage(requestError)); } finally { setSaving(false); }
  };
  return <Modal title={roleField === 'cargo' ? 'Registrar integrante del ORV' : 'Registrar titular de parcela'} onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={error} />
    <Field label="Nombre"><input required value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /></Field>
    <Field label="Apellido paterno"><input value={form.apellido_paterno} onChange={(event) => setForm({ ...form, apellido_paterno: event.target.value })} /></Field>
    <Field label="Apellido materno"><input value={form.apellido_materno} onChange={(event) => setForm({ ...form, apellido_materno: event.target.value })} /></Field>
    <Field label={roleLabel}>{roleField === 'cargo' ? <select required value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="">Selecciona el órgano y cargo</option>{ORV_ROLE_OPTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : <input required value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} />}</Field>
    <SubmitBar saving={saving} onCancel={onClose} />
  </form></Modal>;
}

function PersonLinks({ endpoint, roleField, canCapture, onEdit }) {
  const [items, setItems] = React.useState([]); const [error, setError] = React.useState('');
  React.useEffect(() => { let active = true; api.get(endpoint).then((response) => { if (active) setItems(response.data); }).catch((requestError) => { if (active) setError(apiMessage(requestError)); }); return () => { active = false; }; }, [endpoint]);
  const renderItems = (records) => <div className="record-list">{records.map((item) => <div className="record" key={item.id_orv_integrante || item.id_parcela_titular}><div><strong>{[item.nombre, item.apellido_paterno, item.apellido_materno].filter(Boolean).join(' ')}</strong><span>{roleField === 'cargo' ? orvRoleLabel(item.cargo) : item[roleField]}</span>{item.porcentaje_participacion && <p>Participación: {item.porcentaje_participacion}%</p>}</div>{canCapture && <RecordActions onEdit={() => onEdit(item)} label={roleField === 'cargo' ? 'integrante' : 'titular'} />}</div>)}</div>;
  if (roleField !== 'cargo') return <div className="subsection"><h4>Titulares de la parcela</h4><Notice error={error} />{items.length === 0 ? <p>Sin titulares nominales.</p> : renderItems(items)}</div>;
  const council = items.filter((item) => item.cargo?.includes('CONSEJO'));
  const commission = items.filter((item) => !item.cargo?.includes('CONSEJO'));
  return <div className="subsection orv-groups"><Notice error={error} />{items.length === 0 ? <p>Sin integrantes nominales.</p> : <><section><h4>Comisariado</h4>{commission.length ? renderItems(commission) : <p>Sin integrantes registrados.</p>}</section><section><h4>Consejo de Vigilancia</h4>{council.length ? renderItems(council) : <p>Sin integrantes registrados.</p>}</section></>}</div>;
}

function RelationEditForm({ current, endpoint, roleField, roleLabel, onClose, onDone }) { const [form, setForm] = React.useState({ role: current[roleField] || '', fecha_inicio: current.fecha_inicio || '', fecha_fin: current.fecha_fin || '', porcentaje_participacion: current.porcentaje_participacion ?? '' }); const state = useSubmit(endpoint, onDone, 'patch'); return <Modal title={`Editar ${roleLabel.toLowerCase()}`} onClose={onClose}><form className="form-grid" onSubmit={(event) => { event.preventDefault(); const payload = { [roleField]: form.role, fecha_inicio: form.fecha_inicio || null, fecha_fin: form.fecha_fin || null }; if (roleField === 'tipo_derecho') payload.porcentaje_participacion = form.porcentaje_participacion === '' ? null : Number(form.porcentaje_participacion); state.submit(payload); }}><Notice error={state.error} /><p className="form-context">{[current.nombre, current.apellido_paterno, current.apellido_materno].filter(Boolean).join(' ')}</p><Field label={roleLabel}>{roleField === 'cargo' ? <select required value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}>{ORV_ROLE_OPTIONS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select> : <input required value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} />}</Field><Field label="Fecha de inicio"><input type="date" value={form.fecha_inicio} onChange={(e) => setForm({ ...form, fecha_inicio: e.target.value })} /></Field><Field label="Fecha de fin"><input type="date" value={form.fecha_fin} onChange={(e) => setForm({ ...form, fecha_fin: e.target.value })} /></Field>{roleField === 'tipo_derecho' && <Field label="Participación (%)"><input type="number" min="0.01" max="100" step="0.01" value={form.porcentaje_participacion} onChange={(e) => setForm({ ...form, porcentaje_participacion: e.target.value })} /></Field>}<SubmitBar saving={state.saving} onCancel={onClose} /></form></Modal>; }
function FifonafeForm({ id, scope, current, affectations, onClose, onDone }) {
  const [selected, setSelected] = React.useState(current?.afectaciones?.map((item) => item.id_afectacion) || []);
  const [form, setForm] = React.useState({
    estatus: current?.estatus || 'pendiente', acuse_fifonafe_fecha: current?.acuse_fifonafe_fecha || '',
    hay_conflictos: current?.hay_conflictos == null ? '' : String(current.hay_conflictos), resultado_no_conflictos: current?.resultado_no_conflictos || '',
    no_oficio_fifonafe_a_dgaopr: current?.no_oficio_fifonafe_a_dgaopr || '', fecha_oficio_fifonafe_a_dgaopr: current?.fecha_oficio_fifonafe_a_dgaopr || '',
    no_oficio_dgaopr_a_representacion: current?.no_oficio_dgaopr_a_representacion || '', fecha_oficio_dgaopr_a_representacion: current?.fecha_oficio_dgaopr_a_representacion || '',
    no_oficio_respuesta_representacion_a_dgaopr: current?.no_oficio_respuesta_representacion_a_dgaopr || '', fecha_oficio_respuesta_representacion_a_dgaopr: current?.fecha_oficio_respuesta_representacion_a_dgaopr || '',
    no_oficio_respuesta_dgaopr_a_fifonafe: current?.no_oficio_respuesta_dgaopr_a_fifonafe || '', fecha_oficio_respuesta_dgaopr_a_fifonafe: current?.fecha_oficio_respuesta_dgaopr_a_fifonafe || '', observaciones: current?.observaciones || '',
  });
  const state = useSubmit(current ? `/fifonafe/${current.id_tramite_fifonafe}` : `/proyecto-nucleo/${id}/fifonafe`, onDone, current ? 'patch' : 'post');
  const toggle = (affectationId) => setSelected((items) => items.includes(affectationId) ? items.filter((item) => item !== affectationId) : [...items, affectationId]);
  const dateFields = ['acuse_fifonafe_fecha', 'fecha_oficio_fifonafe_a_dgaopr', 'fecha_oficio_dgaopr_a_representacion', 'fecha_oficio_respuesta_representacion_a_dgaopr', 'fecha_oficio_respuesta_dgaopr_a_fifonafe'];
  const submit = (event) => { event.preventDefault(); const payload = { ...form, hay_conflictos: form.hay_conflictos === '' ? null : form.hay_conflictos === 'true' }; dateFields.forEach((key) => { payload[key] = payload[key] || null; }); if (!current) payload.ids_afectacion = selected; state.submit(payload); };
  const offices = [
    ['no_oficio_fifonafe_a_dgaopr', 'fecha_oficio_fifonafe_a_dgaopr', '1. FIFONAFE → DGAOPR / Representación'],
    ['no_oficio_dgaopr_a_representacion', 'fecha_oficio_dgaopr_a_representacion', '2. DGAOPR → Representación'],
    ['no_oficio_respuesta_representacion_a_dgaopr', 'fecha_oficio_respuesta_representacion_a_dgaopr', '3. Representación → DGAOPR'],
    ['no_oficio_respuesta_dgaopr_a_fifonafe', 'fecha_oficio_respuesta_dgaopr_a_fifonafe', '4. DGAOPR / Representación → FIFONAFE'],
  ];
  return <Modal title={`${current ? 'Editar' : 'Registrar'} informe de no conflictos`} onClose={onClose}><form className="form-grid" onSubmit={submit}><Notice error={state.error} />
    <p className="form-context"><strong>Tipo de trámite:</strong> Informe de no conflictos · ámbito {scope === 'colectivo' ? 'colectivo' : 'individual'}.</p>
    {!current && <fieldset className="check-group"><legend>Afectaciones cubiertas</legend>{affectations.map((item) => <label key={item.id_afectacion}><input type="checkbox" checked={selected.includes(item.id_afectacion)} onChange={() => toggle(item.id_afectacion)} />{item.destino_superficie || item.no_parcela_solar || (item.tipo_afectacion === 'individual' ? 'Afectación individual' : 'Afectación colectiva')}</label>)}</fieldset>}
    <Field label="Estatus"><select value={form.estatus} onChange={(event) => setForm({ ...form, estatus: event.target.value })}><option value="pendiente">Pendiente</option><option value="programado">Programado</option><option value="completo">Completo</option><option value="cancelado">Cancelado</option><option value="otro">Otro</option></select></Field>
    <Field label="Acuse FIFONAFE (fecha)"><input type="date" value={form.acuse_fifonafe_fecha} onChange={(event) => setForm({ ...form, acuse_fifonafe_fecha: event.target.value })} /></Field>
    <Field label="¿Hay conflictos?"><select value={form.hay_conflictos} onChange={(event) => setForm({ ...form, hay_conflictos: event.target.value })}><option value="">Por determinar</option><option value="false">No hay conflictos</option><option value="true">Hay conflictos</option></select></Field>
    <Field label="Resultado / informe de no conflictos"><textarea value={form.resultado_no_conflictos} onChange={(event) => setForm({ ...form, resultado_no_conflictos: event.target.value })} /></Field>
    <h3>Secuencia operativa de oficios</h3>
    {offices.map(([numberKey, dateKey, label]) => <React.Fragment key={numberKey}><Field label={`${label}: número de oficio`}><input value={form[numberKey]} onChange={(event) => setForm({ ...form, [numberKey]: event.target.value })} /></Field><Field label={`${label}: fecha`}><input type="date" value={form[dateKey]} onChange={(event) => setForm({ ...form, [dateKey]: event.target.value })} /></Field></React.Fragment>)}
    <Field label="Observaciones / acuerdos"><textarea value={form.observaciones} onChange={(event) => setForm({ ...form, observaciones: event.target.value })} /></Field>
    <SubmitBar saving={state.saving || (!current && selected.length === 0)} onCancel={onClose} label={current ? 'Guardar cambios' : 'Crear trámite'} />
  </form></Modal>;
}

function FifonafeLinkForm({ item, affectations, onClose, onDone }) { const linked = new Set(item.afectaciones.map((link) => link.id_afectacion)); const candidates = affectations.filter((affectation) => affectation.tipo_afectacion === item.ambito && !linked.has(affectation.id_afectacion)); const [selected, setSelected] = React.useState(''); const state = useSubmit(`/fifonafe/${item.id_tramite_fifonafe}/afectaciones`, onDone); return <Modal title="Asociar otra afectación a FIFONAFE" onClose={onClose}><form className="form-grid" onSubmit={(event) => { event.preventDefault(); state.submit({ id_afectacion: Number(selected) }); }}><Notice error={state.error} /><p className="form-context">Sólo se muestran afectaciones activas del mismo ProyectoNucleo y ámbito {item.ambito}.</p><Field label="Afectación"><select required value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Selecciona</option>{candidates.map((affectation) => <option key={affectation.id_afectacion} value={affectation.id_afectacion}>{affectation.destino_superficie || affectation.no_parcela_solar || (affectation.tipo_afectacion === 'individual' ? 'Afectación individual' : 'Afectación colectiva')}</option>)}</select></Field>{candidates.length === 0 && <p>No hay afectaciones adicionales elegibles.</p>}<SubmitBar saving={state.saving || candidates.length === 0} onCancel={onClose} label="Asociar" /></form></Modal>; }
